import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { RateLimitShard } from "../worker/src/durable/RateLimitShard.js";
import { ChatSession } from "../worker/src/durable/ChatSession.js";
import { AccountPrivacyService } from "../worker/src/services/AccountPrivacyService.js";
import { AdminService } from "../worker/src/services/AdminService.js";
import worker,{ allowedOrigin,secureResponse } from "../worker/src/index.js";

function rateState(){const values=new Map();return{storage:{get:key=>values.get(key),put:(key,value)=>values.set(key,structuredClone(value)),list:({prefix})=>new Map([...values].filter(([key])=>key.startsWith(prefix))),delete:keys=>keys.forEach(key=>values.delete(key)),setAlarm:()=>{}},values};}
function socket(id){return{sent:[],send(value){this.sent.push(JSON.parse(value))},deserializeAttachment(){return{participantId:id,resumeToken:`token-${id}`}}};}

describe("production rate limits",()=>{
  it("rejects the 21st anonymous session request in a minute",async()=>{const shard=new RateLimitShard(rateState()),request=()=>new Request("https://rate/check",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bucket:"anonymous_session",key:"1234567890123456"})});for(let index=0;index<20;index++)assert.equal((await shard.fetch(request())).status,200);const blocked=await shard.fetch(request());assert.equal(blocked.status,429);assert.equal((await blocked.json()).allowed,false);});
  it("rejects the 21st chat message in ten seconds without storing message text",async()=>{const a=socket("a"),b=socket("b"),values=new Map([["session",{sessionId:"rate-room",participants:{a:{lastActivityAt:0},b:{lastActivityAt:0}},disconnects:{},startedAt:Date.now(),ended:false}]]),state={getWebSockets:()=>[a,b],storage:{get:key=>values.get(key),put:(key,value)=>values.set(key,structuredClone(value)),setAlarm:()=>{}}},room=new ChatSession(state,{});for(let index=0;index<21;index++)await room.webSocketMessage(a,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:`event-${index}`,payload:{text:"hello"}}));assert.equal(a.sent.at(-1).type,"RATE_LIMITED");assert.equal(b.sent.filter(event=>event.type==="MESSAGE_RECEIVED").length,20);assert.equal(JSON.stringify(values.get("session")).includes("hello"),false);});
});

describe("HTTP security boundary",()=>{
  it("allows configured and same-site origins while rejecting unknown origins",()=>{assert.equal(allowedOrigin(new Request("https://api.example.test/x",{headers:{origin:"https://web.example.test"}}),{ALLOWED_ORIGIN:"https://web.example.test"}),"https://web.example.test");assert.equal(allowedOrigin(new Request("https://api.example.test/x",{headers:{origin:"https://api.example.test"}}),{}),"https://api.example.test");assert.equal(allowedOrigin(new Request("https://api.example.test/x",{headers:{origin:"https://evil.example"}}),{}),false);assert.equal(allowedOrigin(new Request("https://api.example.test/x",{headers:{origin:"http://127.0.0.1:5173"}}),{ALLOWED_ORIGIN:"https://web.example.test"}),false);assert.equal(allowedOrigin(new Request("http://127.0.0.1:8787/x",{headers:{origin:"http://127.0.0.1:5173"}}),{ALLOWED_ORIGIN:"http://127.0.0.1:5173"}),"http://127.0.0.1:5173");});
  it("adds browser defenses and disables caching for private APIs",()=>{const request=new Request("https://api.example.test/api/v1/me/profile",{headers:{origin:"https://web.example.test"}}),response=secureResponse(Response.json({ok:true}),request,{ALLOWED_ORIGIN:"https://web.example.test"});assert.equal(response.headers.get("access-control-allow-origin"),"https://web.example.test");assert.equal(response.headers.get("x-content-type-options"),"nosniff");assert.equal(response.headers.get("x-frame-options"),"DENY");assert.equal(response.headers.get("cache-control"),"no-store");});
  it("keeps first-party geolocation available for explicit radius matching",async()=>{const headers=await readFile(new URL("../web/public/_headers",import.meta.url),"utf8");assert.match(headers,/Permissions-Policy: camera=\(\), microphone=\(\), geolocation=\(self\)/);assert.doesNotMatch(headers,/geolocation=\(\)/);});
  it("rejects oversized chunked JSON before routing or buffering the full API body",async()=>{const body=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(64*1024));controller.enqueue(new Uint8Array(1));controller.close();}}),request=new Request("https://api.example.test/api/v1/match/search",{method:"POST",headers:{"content-type":"application/json"},body,duplex:"half"}),response=await worker.fetch(request,{});assert.equal(response.status,413);assert.deepEqual(await response.json(),{error:"payload_too_large"});});
  it("reports the exact deployed release revision from health",async()=>{const revision="a".repeat(40),response=await worker.fetch(new Request("https://api.example.test/api/v1/health"),{RELEASE_REVISION:revision}),body=await response.json();assert.equal(body.revision,revision);});
});

describe("privacy operations",()=>{
  it("exports business data but never a server chat transcript",async()=>{const service=new AccountPrivacyService({SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service"},async url=>Response.json(url.includes("/profiles?")?[{public_id:"RC-1"}]:[])),data=await service.export("user-id");assert.equal(data.profile.public_id,"RC-1");assert.equal("messages" in data,false);assert.match(data.chatHistory,/browser/i);});
  it("uses an audited RPC for grievance transitions",async()=>{let call;const service=new AdminService({SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service"},async(url,options)=>{call={url,body:JSON.parse(options.body)};return Response.json({status:"resolved"});});await service.updateGrievance({adminId:"admin",id:"grievance",status:"resolved"});assert.match(call.url,/rpc\/admin_update_grievance$/);assert.deepEqual(call.body,{admin_id:"admin",target_id:"grievance",new_status:"resolved"});});
  it("uses an audited RPC for deletion request transitions",async()=>{let call;const service=new AdminService({SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service"},async(url,options)=>{call={url,body:JSON.parse(options.body)};return Response.json({status:"processing"});});await service.updateDeletion({adminId:"admin",id:"request",status:"processing",note:"Identity verified"});assert.match(call.url,/rpc\/admin_update_deletion_request$/);assert.equal(call.body.decision_note,"Identity verified");});
  it("defines RLS, deletion, grievances and retention without a messages table",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608250010_phase23_hardening.sql",import.meta.url),"utf8");assert.match(sql,/account_deletion_requests/i);assert.match(sql,/admin_update_grievance/i);assert.match(sql,/cleanup_operational_retention/i);assert.match(sql,/enable row level security/i);assert.match(sql,/service_role/i);assert.doesNotMatch(sql,/create table[^;]*messages/i);});
});
