import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { launchReportFingerprint } from "../scripts/launch-report.mjs";
import { validateLaunchEvidence,validateLaunchEvidenceFiles } from "../scripts/validate-launch-evidence.mjs";

const evidence={
  revision:"a".repeat(40),
  release:{frontendVersion:"pages-v1",workerVersion:"worker-v1",migrationVersion:"202608250013",backupReference:"backup-1",restoreDrillAt:"2026-08-25T11:50:00Z"},
  staging:{webUrl:"https://staging.random.in",apiUrl:"https://api-staging.random.in/api/v1",smokeReportReference:"SMOKE-1",smokeReportPath:"reports/smoke.json",smokeReportSha256:"b".repeat(64),smokePassedAt:"2026-08-25T12:00:00Z",browserFlowReference:"BROWSER-1",browserFlowVerifiedAt:"2026-08-25T12:02:00Z",browsersTested:["Chrome Android","Safari iOS"],matchVerified:true,oneActiveIdentityVerified:true,reconnectVerified:true,idleVerified:true,reportBlockVerified:true,virtualDisclosureVerified:true,dataExportVerified:true,deletionRequestVerified:true,noTranscriptPersistenceVerified:true},
  payment:{liveOrderReference:"order_ref",livePaymentReference:"payment_ref",refundReference:"refund_ref",ledgerReference:"LEDGER-1",amountPaise:5000,currency:"INR",paymentCaptured:true,refundAmountPaise:5000,refundProcessed:true,creditedCredits:5000,reversedCredits:5000,duplicateWebhookIdempotent:true,ledgerReconciled:true,reconciledAt:"2026-08-25T12:05:00Z"},
  advertising:{provider:"reviewed-network",reviewReference:"ADS-REVIEW-1",tiersVerifiedAt:"2026-08-25T12:10:00Z",policyReviewed:true,privacyReviewed:true,consentReviewed:true,cspReviewed:true,providerFailureFallbackVerified:true,mobilePlacementVerified:true,desktopPlacementVerified:true,freeTierVerified:true,midTierVerified:true,adFreeTierVerified:true,interstitialCadenceVerified:true,killSwitchVerified:true},
  load:{reportReference:"LOAD-1",reportPath:"reports/realtime.json",reportSha256:"c".repeat(64),peakVirtualUsers:100,p95Milliseconds:300,p99Milliseconds:700,failureRate:0.005,queuesClean:true,noTranscriptPersistenceVerified:true,completedAt:"2026-08-25T12:20:00Z"},
  reddit:{postUrl:"https://www.reddit.com/r/india/comments/abc/launch/",monitoringOwner:"operations",postedAt:"2026-08-25T12:30:00Z"}
};
describe("Phase 24 evidence gate",()=>{const now=Date.parse("2026-08-25T13:00:00Z");it("accepts evidence bound to the expected release revision",()=>assert.deepEqual(validateLaunchEvidence(evidence,{expectedRevision:"a".repeat(40),now}),{ok:true,errors:[]}));it("rejects the untouched template",()=>{const result=validateLaunchEvidence({}, {now});assert.equal(result.ok,false);assert.ok(result.errors.length>=8);});it("rejects a different release revision and future evidence",()=>{const result=validateLaunchEvidence({...evidence,reddit:{...evidence.reddit,postedAt:"2026-08-26T12:00:00Z"}},{expectedRevision:"b".repeat(40),now});assert.match(result.errors.join("\n"),/expected release commit/);assert.match(result.errors.join("\n"),/future/);});it("rejects missing operational evidence references",()=>{const result=validateLaunchEvidence({...evidence,release:{...evidence.release,backupReference:"replace"},staging:{...evidence.staging,smokeReportReference:""},advertising:{...evidence.advertising,reviewReference:null}},{now});assert.match(result.errors.join("\n"),/backupReference/);assert.match(result.errors.join("\n"),/smoke report/);assert.match(result.errors.join("\n"),/provider review/);});it("rejects load results outside the release budget",()=>{const result=validateLaunchEvidence({...evidence,load:{...evidence.load,p95Milliseconds:600,failureRate:0.02}},{now});assert.equal(result.ok,false);assert.match(result.errors.join("\n"),/threshold/);});});
describe("Phase 24 evidence fingerprints",()=>{it("rejects missing report hashes",()=>{const result=validateLaunchEvidence({...evidence,staging:{...evidence.staging,smokeReportSha256:""},load:{...evidence.load,reportSha256:"replace"}},{now:Date.parse("2026-08-25T13:00:00Z")});assert.match(result.errors.join("\n"),/SHA-256/);});});
describe("Phase 24 evidence files",()=>{it("verifies report contents, kinds, revisions and fingerprints",async()=>{const smoke=JSON.stringify({kind:"staging-smoke",revision:evidence.revision}),load=JSON.stringify({kind:"staging-realtime",revision:evidence.revision}),complete={...evidence,staging:{...evidence.staging,smokeReportSha256:launchReportFingerprint(smoke)},load:{...evidence.load,reportSha256:launchReportFingerprint(load)}},readFile=async path=>String(path).endsWith("smoke.json")?smoke:load,result=await validateLaunchEvidenceFiles(complete,{expectedRevision:evidence.revision,now:Date.parse("2026-08-25T13:00:00Z"),baseDir:"C:/evidence",readFile});assert.deepEqual(result,{ok:true,errors:[]});});
it("rejects a report file that was changed after fingerprinting",async()=>{const result=await validateLaunchEvidenceFiles(evidence,{expectedRevision:evidence.revision,now:Date.parse("2026-08-25T13:00:00Z"),readFile:async()=>JSON.stringify({kind:"staging-smoke",revision:evidence.revision})});assert.equal(result.ok,false);assert.match(result.errors.join("\n"),/fingerprint does not match|kind does not match/);});});
describe("Phase 24 payment evidence",()=>{it("rejects non-INR 50, partial, non-idempotent or unreconciled live payment evidence",()=>{const payment={...evidence.payment,amountPaise:6000,refundAmountPaise:2500,reversedCredits:2500,duplicateWebhookIdempotent:false,ledgerReconciled:false},result=validateLaunchEvidence({...evidence,payment},{now:Date.parse("2026-08-25T13:00:00Z")});assert.equal(result.ok,false);assert.match(result.errors.join("\n"),/5000 paise/);assert.match(result.errors.join("\n"),/full live refund/);assert.match(result.errors.join("\n"),/idempotency/);assert.match(result.errors.join("\n"),/ledger reconciliation/);});});
describe("Phase 24 advertising evidence",()=>{it("rejects an incomplete provider review and tier matrix",()=>{const advertising={...evidence.advertising,consentReviewed:false,providerFailureFallbackVerified:false,midTierVerified:false,killSwitchVerified:false},result=validateLaunchEvidence({...evidence,advertising},{now:Date.parse("2026-08-25T13:00:00Z")});assert.equal(result.ok,false);assert.match(result.errors.join("\n"),/advertising review, placement, tier, fallback or kill-switch/);});});
describe("Phase 24 staging browser evidence",()=>{it("rejects a single-browser or incomplete acceptance matrix",()=>{const staging={...evidence.staging,browsersTested:["Chrome Android"],oneActiveIdentityVerified:false,noTranscriptPersistenceVerified:false},result=validateLaunchEvidence({...evidence,staging},{now:Date.parse("2026-08-25T13:00:00Z")});assert.equal(result.ok,false);assert.match(result.errors.join("\n"),/two distinct browsers/);assert.match(result.errors.join("\n"),/browser-flow acceptance matrix/);});});
