import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { isEligibleRandomPair,selectRandomCandidate } from "../worker/src/policies/randomMatchPolicy.js";
import { MatchmakingService } from "../worker/src/services/MatchmakingService.js";
import { PresenceShard } from "../worker/src/durable/PresenceShard.js";

const user=(identityId,extra={})=>({identityId,blockedPeerIds:[],queuedAt:0,...extra});

describe("random match policy",()=>{
  it("never matches an identity to itself",()=>assert.equal(isEligibleRandomPair(user("identity-a"),user("identity-a")),false));
  it("excludes blocks, inactive candidates, and active identities",()=>{assert.equal(isEligibleRandomPair(user("identity-a",{blockedPeerIds:["identity-b"]}),user("identity-b")),false);assert.equal(isEligibleRandomPair(user("identity-a"),user("identity-b",{idle:true})),false);assert.equal(isEligibleRandomPair(user("identity-a"),user("identity-b"),{"identity-b":{sessionId:"s"}}),false);});
  it("enforces registered blocks through opaque public references",()=>assert.equal(isEligibleRandomPair(user("identity-a",{blockedRefs:["public-b"]}),user("identity-b",{accountUserId:"user-b",accountPublicId:"public-b"})),false));
  it("selects the longest-waiting eligible person",()=>{const found=selectRandomCandidate(user("identity-a"),[user("identity-new",{queuedAt:20}),user("identity-old",{queuedAt:10})],{});assert.equal(found.identityId,"identity-old");});
});

describe("matchmaking lifecycle",()=>{
  it("queues the first person and matches the second",()=>{const service=new MatchmakingService();assert.equal(service.search(user("identity-a"),()=>1).status,"searching");const match=service.search(user("identity-b"),()=>2,()=>"session-1");assert.deepEqual(match,{status:"matched",sessionId:"session-1",peerId:"identity-a"});assert.deepEqual(service.result("identity-a"),{status:"matched",sessionId:"session-1",peerId:"identity-b"});});
  it("enforces one active chat per identity",()=>{const service=new MatchmakingService();service.search(user("identity-a"),()=>1);service.search(user("identity-b"),()=>2,()=>"session-1");assert.equal(service.search(user("identity-a")).status,"already_active");});
  it("cleans both active claims when a session ends",()=>{const service=new MatchmakingService();service.search(user("identity-a"),()=>1);service.search(user("identity-b"),()=>2,()=>"session-1");assert.equal(service.end("identity-a","session-1").status,"ended");assert.deepEqual(service.active,{});assert.equal(service.result("identity-b").status,"idle");});
  it("replaces duplicate waiting searches without restarting the timeout",()=>{const service=new MatchmakingService();service.search(user("identity-a"),()=>1);service.search(user("identity-a"),()=>2);assert.equal(service.queue.length,1);assert.equal(service.queue[0].queuedAt,1);});
  it("returns a registered peer public reference without replacing the session identity",()=>{const service=new MatchmakingService();service.search(user("identity-a",{accountPublicId:"public-a"}),()=>1);const match=service.search(user("identity-b",{accountPublicId:"public-b"}),()=>2,()=>"session-public");assert.equal(match.peerId,"identity-a");assert.equal(match.peerRef,"public-a");assert.equal(service.result("identity-a").peerRef,"public-b");});
  it("moves an active registered account claim to its newest browser identity",()=>{const service=new MatchmakingService();service.search(user("identity-old",{accountUserId:"account-a",accountPublicId:"public-a"}),()=>1);service.search(user("identity-peer",{accountUserId:"account-b",accountPublicId:"public-b"}),()=>2,()=>"session-account");const takeover=service.search(user("identity-new",{accountUserId:"account-a",accountPublicId:"public-a"}),()=>3);assert.equal(takeover.accountTakeover,true);assert.equal(takeover.sessionId,"session-account");assert.equal(service.active["identity-old"],undefined);assert.equal(service.active["identity-new"].peerId,"identity-peer");assert.equal(service.active["identity-peer"].peerId,"identity-new");assert.equal(service.result("identity-old").status,"idle");});
});

describe("ephemeral presence",()=>{
  it("tracks real statuses without persistent storage",async()=>{const shard=new PresenceShard();await shard.fetch(new Request("https://presence/status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId:"identity-a",status:"waiting",anonymous:true})}));const response=await shard.fetch(new Request("https://presence/stats"));const stats=await response.json();assert.equal(stats.waiting,1);assert.equal(stats.anonymousOnline,1);assert.equal(Object.hasOwn(shard,"state"),false);});
  it("resolves a registered public reference to the current ephemeral identity",async()=>{const shard=new PresenceShard();await shard.fetch(new Request("https://presence/status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId:"identity-device",status:"online",anonymous:false,accountUserId:"account-user",publicRef:"public-user"})}));const found=await(await shard.fetch(new Request("https://presence/identity/public-user"))).json();assert.deepEqual(found,{online:true,status:"online",identityId:"identity-device",publicRef:"public-user",accountUserId:"account-user"});});
  it("resolves a public reference to its newest device heartbeat",async()=>{const shard=new PresenceShard(),now=Date.now();shard.presence.set("identity-old",{status:"offline",publicRef:"public-user",accountUserId:"account-user",lastSeen:now-1});shard.presence.set("identity-new",{status:"chatting",publicRef:"public-user",accountUserId:"account-user",lastSeen:now});const found=await(await shard.fetch(new Request("https://presence/identity/public-user"))).json();assert.equal(found.identityId,"identity-new");assert.equal(found.online,true);});
});
