import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { RazorpayService,razorpayInternals } from "../worker/src/services/RazorpayService.js";
import { PaymentService } from "../worker/src/services/PaymentService.js";
import { readTextBody } from "../worker/src/index.js";

describe("Razorpay cryptographic boundary",()=>{
  it("verifies checkout signatures over the server order id and payment id",async()=>{const signature=await razorpayInternals.hmac("order_123|pay_456","key-secret"),service=new RazorpayService({keySecret:"key-secret"});assert.equal(await service.verifyCheckout({orderId:"order_123",paymentId:"pay_456",signature}),true);assert.equal(await service.verifyCheckout({orderId:"order_tampered",paymentId:"pay_456",signature}),false);});
  it("verifies webhooks over the exact raw request body",async()=>{const raw='{"event":"payment.captured", "spacing":"preserved"}',signature=await razorpayInternals.hmac(raw,"hook-secret"),service=new RazorpayService({webhookSecret:"hook-secret"});assert.equal(await service.verifyWebhook(raw,signature),true);assert.equal(await service.verifyWebhook(JSON.stringify(JSON.parse(raw)),signature),false);});
  it("enforces the ₹50 floor before calling Razorpay",()=>{let called=false;const service=new RazorpayService({fetcher:async()=>{called=true;return Response.json({});}});assert.throws(()=>service.createOrder({amountPaise:4999}),/minimum_recharge_50/);assert.equal(called,false);});
});

describe("payment reconciliation",()=>{
  const env={SUPABASE_URL:"https://project.supabase.co",SUPABASE_SERVICE_ROLE_KEY:"service",RAZORPAY_KEY_ID:"rzp_test",RAZORPAY_KEY_SECRET:"secret",RAZORPAY_WEBHOOK_SECRET:"hook"};
  it("creates a provider order before requesting a server-side offer quote",async()=>{const calls=[];const fetcher=async(url,options={})=>{calls.push({url,options});if(url.includes("api.razorpay.com"))return Response.json({id:"order_1",status:"created"});return Response.json([{credit_amount:10000,offer_name:"Launch 2X Credits",coupon_code:null}]);};const order=await new PaymentService(env,fetcher).createOrder({id:"user-1",emailVerified:true},5000);assert.equal(order.credits,10000);assert.equal(order.offer,"Launch 2X Credits");assert.match(calls[0].url,/razorpay\.com\/v1\/orders/);assert.match(calls[1].url,/rpc\/prepare_payment_order$/);const saved=JSON.parse(calls[1].options.body);assert.equal(saved.target_user_id,"user-1");assert.equal(saved.target_amount_paise,5000);});
  it("rejects order creation for unverified email",async()=>{await assert.rejects(()=>new PaymentService(env,async()=>Response.json({})).createOrder({id:"u",emailVerified:false},5000),/email_verification_required/);});
  it("accepts a signed captured webhook and credits via the database RPC",async()=>{const body=JSON.stringify({event:"payment.captured",payload:{payment:{entity:{id:"pay_1",order_id:"order_1",status:"captured"}}}}),signature=await razorpayInternals.hmac(body,"hook"),calls=[];const fetcher=async(url,options={})=>{calls.push({url,options});return Response.json([{balance:5000,idempotent:false}]);};await new PaymentService(env,fetcher).webhook(body,signature,"event-1");assert.match(calls[0].url,/rpc\/record_payment_credit$/);assert.equal(JSON.parse(calls[0].options.body).target_provider_event_id,"event-1");});
  it("rejects a tampered webhook without writing",async()=>{let called=false;const service=new PaymentService(env,async()=>{called=true;return Response.json([]);});await assert.rejects(()=>service.webhook('{"event":"payment.captured"}',"bad","event-1"),/invalid_webhook_signature/);assert.equal(called,false);});
  it("rejects oversized webhook bodies and malformed provider event ids before verification",async()=>{const service=new PaymentService(env,async()=>{throw new Error("database_must_not_be_called")});await assert.rejects(()=>service.webhook("x".repeat(256*1024+1),"0".repeat(64),"event-1"),/webhook_payload_too_large/);const body=JSON.stringify({event:"ignored"}),signature=await razorpayInternals.hmac(body,"hook");await assert.rejects(()=>service.webhook(body,signature,"event id with spaces"),/invalid_webhook_event_id/);});
  it("stops reading a chunked webhook once the byte limit is exceeded",async()=>{const body=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(5));controller.enqueue(new Uint8Array(6));controller.close();}}),request=new Request("https://api.test/payments/webhook",{method:"POST",body,duplex:"half"});await assert.rejects(()=>readTextBody(request,10),/webhook_payload_too_large/);});
  it("maps processed refunds to append-only reversal RPCs",async()=>{const body=JSON.stringify({event:"refund.processed",payload:{refund:{entity:{id:"rfnd_1",payment_id:"pay_1",amount:2500}}}}),signature=await razorpayInternals.hmac(body,"hook"),calls=[];await new PaymentService(env,async(url,options)=>{calls.push({url,options});return Response.json([{balance:2500}]);}).webhook(body,signature,"event-refund");assert.match(calls[0].url,/rpc\/record_payment_refund$/);assert.equal(JSON.parse(calls[0].options.body).refund_amount_paise,2500);});
  it("rejects malformed refund paise before any database write",async()=>{for(const amount of [undefined,0,-1,1.5,Number.MAX_SAFE_INTEGER+1]){const entity={id:"rfnd_bad",payment_id:"pay_1",...(amount===undefined?{}:{amount})},body=JSON.stringify({event:"refund.processed",payload:{refund:{entity}}}),signature=await razorpayInternals.hmac(body,"hook");let called=false;await assert.rejects(()=>new PaymentService(env,async()=>{called=true;return Response.json([]);}).webhook(body,signature,"event-refund-bad"),/invalid_refund_event/);assert.equal(called,false);}});
});

describe("phase 9 database safeguards",()=>{
  it("deduplicates provider events and payment wallet entries",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608240003_phase9_payments.sql",import.meta.url),"utf8");assert.match(sql,/provider_event_id text not null unique/i);assert.match(sql,/provider_order_id text not null unique/i);assert.match(sql,/for update/i);assert.match(sql,/razorpay:payment:/i);assert.match(sql,/razorpay:refund:/i);assert.match(sql,/grant execute on function public\.record_payment_credit[\s\S]*service_role/i);assert.doesNotMatch(sql,/create table(?: if not exists)? public\.messages/i);});
});

describe("cumulative refund safeguards",()=>{
  it("deduplicates refund references and caps cumulative refund paise under the payment lock",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608250011_refund_reconciliation.sql",import.meta.url),"utf8");assert.match(sql,/payment_events_provider_refund_idx[\s\S]*where provider_refund_id is not null/i);assert.match(sql,/provider_payment_id=target_provider_payment_id for update/i);assert.match(sql,/refunded_paise\+refund_amount_paise>target_order\.amount_paise/i);assert.match(sql,/cumulative_refund_exceeds_payment/i);assert.match(sql,/idempotency_conflict/i);});
  it("uses cumulative proportional rounding so a full multi-part refund reverses all credited Credits",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608250011_refund_reconciliation.sql",import.meta.url),"utf8");assert.match(sql,/prior_reversal:=floor\(\(target_order\.credit_amount::numeric\*refunded_paise\)\/target_order\.amount_paise\)/i);assert.match(sql,/cumulative_reversal:=floor\(\(target_order\.credit_amount::numeric\*\(refunded_paise\+refund_amount_paise\)\)\/target_order\.amount_paise\)/i);assert.match(sql,/credit_reversal:=cumulative_reversal-prior_reversal/i);assert.match(sql,/when refunded_paise\+refund_amount_paise=amount_paise then 'refunded'/i);});
});

describe("payment credit reconciliation safeguards",()=>{
  it("locks the order and rejects event-id or payment-id conflicts",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608250012_payment_credit_reconciliation.sql",import.meta.url),"utf8");assert.match(sql,/provider_order_id=target_provider_order_id for update/i);assert.match(sql,/provider_payment_id<>target_provider_payment_id[\s\S]*payment_order_already_paid/i);assert.match(sql,/existing_event\.event_type<>target_event_type[\s\S]*idempotency_conflict/i);});
  it("runs coupon redemption only for the initial credit and preserves refund states",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608250012_payment_credit_reconciliation.sql",import.meta.url),"utf8");assert.match(sql,/if target_order\.status='created' and target_order\.coupon_id is not null/i);assert.match(sql,/status=case when status in \('partially_refunded','refunded'\) then status else 'paid' end/i);assert.match(sql,/razorpay:payment:'\|\|target_provider_payment_id/i);});
});

describe("phase 10 offer safeguards",()=>{
  it("stores the launch multiplier and exact IST expiry as configuration",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608250001_phase10_offers.sql",import.meta.url),"utf8");assert.match(sql,/Launch 2X Credits',20000/);assert.match(sql,/2026-09-30 23:59:59\+05:30/);assert.match(sql,/max_redemptions integer/);assert.match(sql,/max_uses_per_account integer/);assert.match(sql,/for update/i);assert.match(sql,/coupon_redemptions/);assert.match(sql,/grant execute on function public\.prepare_payment_order[\s\S]*service_role/i);assert.doesNotMatch(sql,/create table(?: if not exists)? public\.messages/i);});
});
