import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { chatSocketUrl,issueAnonymousSession,pollMatchResult } from "../web/js/match-api.js";
import { RealtimeChatClient } from "../web/js/realtime-client.js";

class FakeSocket{constructor(url,protocols){this.url=url;this.protocols=protocols;this.readyState=1;this.listeners={};this.sent=[];FakeSocket.instances.push(this)}addEventListener(type,callback){this.listeners[type]=callback}send(value){this.sent.push(JSON.parse(value))}close(){this.closed=true}emit(type,value={}){this.listeners[type]?.(value)}}FakeSocket.instances=[];
describe("browser matchmaking transport",()=>{
  it("issues a signed anonymous session and polls with its bearer token",async()=>{const calls=[],fetcher=async(url,options)=>{calls.push({url,options});return Response.json(url.endsWith("anonymous/session")?{token:"signed"}:{status:"searching"});};assert.equal((await issueAnonymousSession({id:"identity-123",secret:"secret-123456789"},{fetcher,apiBase:"https://api.test/api/v1"})).token,"signed");await pollMatchResult("signed",{fetcher,apiBase:"https://api.test/api/v1"});assert.equal(calls[1].options.headers.authorization,"Bearer signed");});
  it("converts the API origin to a WebSocket URL without placing the bearer token in it",()=>{const url=chatSocketUrl("session-123",{apiBase:"https://api.test/api/v1",resumeToken:"resume"});assert.match(url,/^wss:\/\/api\.test\/api\/v1\/chat\/session-123\/socket\?resumeToken=resume$/);assert.doesNotMatch(url,/Bearer|signed/);});
  it("uses a subprotocol token, records resume state and sends versioned events",()=>{FakeSocket.instances=[];const events=[],client=new RealtimeChatClient({WebSocketImpl:FakeSocket,onEvent:event=>events.push(event),apiBase:"https://api.test/api/v1"});client.connect({sessionId:"session-123",token:"signed-token"});const socket=FakeSocket.instances[0];assert.deepEqual(socket.protocols,["random-chat.v1","rc-auth.signed-token"]);socket.emit("message",{data:JSON.stringify({v:1,type:"READY",payload:{resumeToken:"resume-1"}})});assert.equal(client.resumeToken,"resume-1");assert.equal(client.send("CHAT_MESSAGE",{text:"hello"},"event-1"),true);assert.deepEqual(socket.sent[0],{v:1,type:"CHAT_MESSAGE",eventId:"event-1",payload:{text:"hello"}});assert.equal(events[0].type,"READY");});
  it("reconnects with the temporary resume token and stops after explicit close",()=>{FakeSocket.instances=[];let retry;const client=new RealtimeChatClient({WebSocketImpl:FakeSocket,setTimer:callback=>{retry=callback;return 1},clearTimer:()=>{},apiBase:"https://api.test/api/v1"});client.connect({sessionId:"session-123",token:"signed-token"});FakeSocket.instances[0].emit("message",{data:JSON.stringify({v:1,type:"READY",payload:{resumeToken:"resume-1"}})});FakeSocket.instances[0].emit("close");retry();assert.match(FakeSocket.instances[1].url,/resumeToken=resume-1/);client.stop();assert.equal(FakeSocket.instances[1].closed,true);});
});
