import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { MatchmakingService } from "../worker/src/services/MatchmakingService.js";
import { MatchmakingShard } from "../worker/src/durable/MatchmakingShard.js";

describe("favourite reconnect lifecycle",()=>{
  it("keeps a request pending for an online target and creates a fresh match on acceptance",()=>{const service=new MatchmakingService(),requested=service.requestReconnect({requestId:"request-1",initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"},()=>1000);assert.equal(requested.status,"requested");assert.equal(service.pendingReconnect("identity-b",()=>2000).initiatorId,"identity-a");const accepted=service.activateReconnect("request-1","identity-b",()=>"fresh-session",()=>3000);assert.equal(accepted.status,"accepted");assert.equal(accepted.sessionId,"fresh-session");assert.equal(service.active["identity-a"].peerId,"identity-b");assert.equal(service.results["identity-b"].reconnect,true);});
  it("expires unanswered requests without a charge or queue",()=>{const service=new MatchmakingService();service.requestReconnect({requestId:"request-1",initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"},()=>1000);assert.equal(service.pendingReconnect("identity-b",()=>122000),null);assert.deepEqual(service.active,{});assert.equal(service.queue.length,0);});
  it("lets the initiator cancel before the target accepts",()=>{const service=new MatchmakingService();service.requestReconnect({requestId:"request-2",initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"},()=>1000);assert.deepEqual(service.cancelReconnect("identity-a"),{status:"cancelled",cancelled:1});assert.equal(service.pendingReconnect("identity-b",()=>2000),null);assert.equal(service.cancelReconnect("identity-a").status,"idle");});
});

describe("reconnect shard money boundary",()=>{
  const setup=(initiallyOnline,walletResponse=()=>Response.json([{balance:950,idempotent:false}]))=>{let online=initiallyOnline;const values=new Map(),state={storage:{get:key=>values.get(key),put:(key,value)=>values.set(key,structuredClone(value))}},PRESENCE={idFromName:()=>"presence",get:()=>({fetch:async(_url,options)=>options?.method==="POST"?Response.json({ok:true}):Response.json({online,status:online?"online":"offline"})})};let walletBody;const env={PRESENCE,SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service",FETCHER:async(_url,options)=>{walletBody=JSON.parse(options.body);return walletResponse();}},shard=new MatchmakingShard(state,env),post=(path,body)=>shard.fetch(new Request(`https://match.internal${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}));return{values,shard,post,setOnline:value=>{online=value;},wallet:()=>walletBody};};
  it("returns offline without creating a request or debit",async()=>{const{post,values,wallet}=setup(false),response=await post("/reconnect/request",{initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"});assert.equal((await response.json()).status,"offline");assert.equal(values.size,0);assert.equal(wallet(),undefined);});
  it("charges only the initiator after acceptance",async()=>{const{post,shard,wallet}=setup(true),requested=await(await post("/reconnect/request",{initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"})).json(),inbox=await(await shard.fetch(new Request("https://match.internal/reconnect/poll/identity-b"))).json();assert.equal(inbox.request.requestId,requested.requestId);assert.equal(wallet(),undefined);const accepted=await(await post("/reconnect/respond",{targetId:"identity-b",requestId:requested.requestId,accepted:true})).json();assert.equal(accepted.status,"accepted");assert.equal(wallet().credit_delta,-50);assert.equal(wallet().target_user_id,"user-a");assert.match(wallet().ledger_idempotency_key,/^reconnect:/);});
  it("does not charge if either identity goes offline before acceptance",async()=>{const{post,setOnline,wallet}=setup(true),requested=await(await post("/reconnect/request",{initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"})).json();setOnline(false);const response=await post("/reconnect/respond",{targetId:"identity-b",requestId:requested.requestId,accepted:true});assert.equal((await response.json()).status,"offline");assert.equal(wallet(),undefined);});
  it("rolls back the match when the initiator has insufficient Credits",async()=>{const{post,values}=setup(true,()=>Response.json({message:"insufficient_balance"},{status:400})),requested=await(await post("/reconnect/request",{initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"})).json(),response=await post("/reconnect/respond",{targetId:"identity-b",requestId:requested.requestId,accepted:true}),saved=values.get("matchmaking_state");assert.equal(response.status,402);assert.deepEqual(saved.active,{});assert.deepEqual(saved.results,{});});
  it("declines for zero charge",async()=>{const{post,wallet}=setup(true),requested=await(await post("/reconnect/request",{initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"})).json(),declined=await(await post("/reconnect/respond",{targetId:"identity-b",requestId:requested.requestId,accepted:false})).json();assert.equal(declined.status,"declined");assert.equal(wallet(),undefined);});
  it("cancels the pending request without a charge",async()=>{const{post,wallet}=setup(true);await post("/reconnect/request",{initiatorId:"identity-a",initiatorUserId:"user-a",targetId:"identity-b"});const result=await(await post("/reconnect/cancel",{initiatorId:"identity-a"})).json();assert.equal(result.status,"cancelled");assert.equal(wallet(),undefined);});
});
