import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { MatchmakingService } from "../worker/src/services/MatchmakingService.js";
import { MockVirtualParticipantProvider } from "../worker/src/services/VirtualParticipantProvider.js";
import { normalizeVirtualConfig,selectVirtualPersona } from "../worker/src/policies/virtualPolicy.js";
import { ChatSession } from "../worker/src/durable/ChatSession.js";

const persona={personaId:"quiet-river",handle:"QuietRiver482",age:24,gender:"Other",region:"India",languages:["English"],interests:["Music"],tone:"casual",verbosity:"short",curiosity:.7,humor:.4,delayMinMs:0,delayMaxMs:0,activeHours:[]};
const config=normalizeVirtualConfig({enabled:true,provider:"mock",model:"",maxConcurrent:2,fallbackSeconds:15,greetProbability:.5,greetings:["hi","hie","hey"],personas:[persona]});
const user=(identityId,extra={})=>({identityId,blockedPeerIds:[],available:true,profile:{},preferences:{},...extra});
function socket(id){return{sent:[],send(raw){this.sent.push(JSON.parse(raw))},deserializeAttachment(){return{participantId:id,resumeToken:`token-${id}`}}};}
function roomState(socket,session){const values=new Map([["session",session]]);return{getWebSockets:()=>[socket],storage:{get:key=>values.get(key),put:(key,value)=>values.set(key,structuredClone(value)),setAlarm:()=>{}},values};}

describe("virtual fallback matchmaking",()=>{
  it("waits fifteen seconds and still gives an arriving human priority",()=>{const service=new MatchmakingService();service.search(user("identity-a"),()=>0);assert.equal(service.virtualFallback("identity-a",config,()=>14999).status,"searching");const human=service.search(user("identity-b"),()=>15000,()=>"human-session");assert.equal(human.peerId,"identity-a");assert.equal(human.virtual,undefined);});
  it("creates a clearly marked zero-fee virtual match only after fallback, with a fresh reddit-style handle each time",()=>{const service=new MatchmakingService();service.search(user("identity-a"),()=>0);const result=service.virtualFallback("identity-a",config,()=>15000,()=>"virtual-session",()=>0);assert.equal(result.virtual,true);assert.match(result.virtualProfile.handle,/^[A-Za-z]+[A-Za-z]+\d+$/);assert.notEqual(result.virtualProfile.handle,persona.handle);assert.equal(result.preferenceFee,0);assert.equal(service.active["identity-a"].virtualPeer.persona.personaId,"quiet-river");});
  it("waits the full paid preference timeout",()=>{const service=new MatchmakingService();service.search(user("identity-a",{preferences:{gender:"Female"}}),()=>0);assert.equal(service.virtualFallback("identity-a",config,()=>29999).status,"searching");assert.equal(service.virtualFallback("identity-a",config,()=>30000,()=>"virtual-session",()=>0).virtual,true);});
  it("uses persona active hours in IST",()=>{const scheduled=normalizeVirtualConfig({...config,personas:[{...persona,activeHours:[6]}]});assert.equal(selectVirtualPersona(scheduled,()=>0,0),null);assert.equal(selectVirtualPersona(scheduled,()=>0,1800000).personaId,"quiet-river");});
});

describe("natural virtual conversation boundary",()=>{
  it("either waits or sends one short configured greeting",()=>{const waits=new MockVirtualParticipantProvider(config,()=>.9),values=[.1,0],greets=new MockVirtualParticipantProvider(config,()=>values.shift());assert.equal(waits.opening(persona),null);assert.equal(greets.opening(persona),"hi");assert.ok(config.greetings.every(value=>value.length<=8));});
  it("female personas greet far less often than the config default",()=>{const female={...persona,gender:"Female"};const rarely=new MockVirtualParticipantProvider(config,()=>.3);assert.equal(rarely.opening(persona),"hi");assert.equal(rarely.opening(female),null);});
  it("replies only after the human message without charging or persisting text",async()=>{const human=socket("identity-a"),session={sessionId:"virtual-session",participants:{"identity-a":{lastActivityAt:Date.now(),accountUserId:"user-a",virtual:false}},disconnects:{},trialConsumed:{},startedAt:Date.now(),ended:false,virtualOpeningDecided:true,virtualPeer:{identityId:"virtual-quiet-river",persona,config}},state=roomState(human,session);let walletCalls=0;const room=new ChatSession(state,{VIRTUAL_RANDOM:()=>0,VIRTUAL_WAITER:async()=>{},FETCHER:async()=>{walletCalls++;return Response.json([]);}});await room.webSocketMessage(human,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"human-1",payload:{text:"I like programming"}}));assert.deepEqual(human.sent.map(event=>event.type),["MESSAGE_ACCEPTED","MESSAGE_RECEIVED"]);assert.equal(human.sent[1].payload.virtual,true);assert.equal(walletCalls,0);assert.equal(JSON.stringify(state.values.get("session")).includes("I like programming"),false);});
  it("ends at two minutes instead of offering paid continuation",async()=>{const now=Date.now(),human=socket("identity-a"),session={sessionId:"virtual-session",participants:{"identity-a":{lastActivityAt:now}},disconnects:{},trialConsumed:{"identity-a":true},startedAt:now-121000,ended:false,virtualPeer:{identityId:"virtual-quiet-river",persona,config}},state=roomState(human,session),room=new ChatSession(state,{});await room.alarm();assert.equal(state.values.get("session").ended,true);assert.equal(human.sent.some(event=>event.type==="CONTINUE_REQUESTED"),false);assert.equal(human.sent.some(event=>event.payload.reason==="virtual_free_time_complete"),true);});
  it("rejects contact unlock and permits reporting the virtual identity",async()=>{const human=socket("identity-a"),session={sessionId:"virtual-session",participants:{"identity-a":{lastActivityAt:Date.now(),accountUserId:"user-a"}},disconnects:{},startedAt:Date.now(),ended:false,virtualPeer:{identityId:"virtual-quiet-river",persona,config}},state=roomState(human,session);let reportBody;const room=new ChatSession(state,{SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service",FETCHER:async(_url,options)=>{reportBody=JSON.parse(options.body);return Response.json([]);}});await room.webSocketMessage(human,JSON.stringify({v:1,type:"CONTACT_UNLOCK_REQUEST"}));assert.equal(human.sent.at(-1).payload.code,"virtual_contact_unlock_unavailable");await room.webSocketMessage(human,JSON.stringify({v:1,type:"REPORT",payload:{reason:"spam"}}));assert.equal(human.sent.at(-1).type,"REPORT_ACCEPTED");assert.equal(reportBody.target_ref,"virtual-quiet-river");});
  it("ships disabled until explicitly enabled",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608250007_phase20_virtual.sql",import.meta.url),"utf8");assert.match(sql,/"enabled":false/);assert.match(sql,/"provider":"disabled"/);assert.doesNotMatch(sql,/create table[^;]*messages/i);});
});
