import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { parseClientEvent,serverEvent } from "../worker/src/protocol.js";
import { ChatSession } from "../worker/src/durable/ChatSession.js";

function fakeSocket(participantId){return{sent:[],send(value){this.sent.push(JSON.parse(value))},deserializeAttachment(){return{participantId,resumeToken:`token-${participantId}`}}};}
function memoryState(sockets,session={participants:{a:{lastActivityAt:0},b:{lastActivityAt:0}},disconnects:{},startedAt:0}){const values=new Map([["session",session]]);return{getWebSockets:()=>sockets,storage:{get:key=>values.get(key),put:(key,value)=>values.set(key,structuredClone(value)),setAlarm:()=>{}},values};}

describe("WebSocket protocol",()=>{
  it("accepts a versioned text message",()=>{const result=parseClientEvent(JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"e1",payload:{text:"Hi"}}));assert.equal(result.ok,true);assert.equal(result.event.payload.text,"Hi");});
  it("rejects malformed and oversized messages",()=>{assert.equal(parseClientEvent("not json").code,"invalid_json");assert.equal(parseClientEvent(JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"e1",payload:{text:"x".repeat(1001)}})).code,"message_too_large");});
  it("always emits a versioned server envelope",()=>assert.deepEqual(JSON.parse(serverEvent("READY",{ok:true})),{v:1,type:"READY",payload:{ok:true}}));
  it("accepts mutual continuation decisions",()=>{assert.equal(parseClientEvent(JSON.stringify({v:1,type:"CONTINUE_ACCEPT"})).ok,true);assert.equal(parseClientEvent(JSON.stringify({v:1,type:"CONTINUE_DECLINE"})).ok,true);});
});

describe("ChatSession relay",()=>{
  it("acknowledges and relays without persisting message text",async()=>{const sender=fakeSocket("a"),peer=fakeSocket("b"),state=memoryState([sender,peer]);const session=new ChatSession(state);await session.webSocketMessage(sender,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"event-1",payload:{text:"hello"}}));assert.equal(sender.sent[0].type,"MESSAGE_ACCEPTED");assert.equal(peer.sent[0].type,"MESSAGE_RECEIVED");assert.equal(peer.sent[0].payload.text,"hello");assert.equal(JSON.stringify(state.values.get("session")).includes("hello"),false);});
  it("rejects invalid input without relaying",async()=>{const sender=fakeSocket("a"),peer=fakeSocket("b");const session=new ChatSession(memoryState([sender,peer]));await session.webSocketMessage(sender,"bad");assert.equal(sender.sent[0].type,"MESSAGE_REJECTED");assert.equal(peer.sent.length,0);});
  it("announces disconnect and reconnect grace",async()=>{const sender=fakeSocket("a"),peer=fakeSocket("b");const session=new ChatSession(memoryState([sender,peer]));await session.webSocketClose(sender,1006,"gone");assert.deepEqual(peer.sent.map(event=>event.type),["PEER_DISCONNECTED","RECONNECT_GRACE"]);});
});

describe("paid continuation",()=>{
  const paidState=()=>memoryState([],{sessionId:"session-paid",participants:{a:{lastActivityAt:1,accountUserId:"user-a",virtual:false},b:{lastActivityAt:1,accountUserId:"user-b",virtual:false}},disconnects:{},startedAt:1,freeExpiredAt:2,continuationHoldUntil:Date.now()+300000,continueAccepted:{},ended:false});
  it("activates only after both registered participants accept",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=paidState();state.getWebSockets=()=>[a,b];const room=new ChatSession(state,{});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CONTINUE_ACCEPT"}));assert.equal(state.values.get("session").paidActive,undefined);await room.webSocketMessage(b,JSON.stringify({v:1,type:"CONTINUE_ACCEPT"}));assert.equal(state.values.get("session").paidActive,true);assert.equal(a.sent.at(-1).type,"CONTINUE_ACTIVATED");assert.equal(b.sent.at(-1).type,"CONTINUE_ACTIVATED");});
  it("debits 10 Credits idempotently before relaying a paid message",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=paidState();state.getWebSockets=()=>[a,b];const stored=state.values.get("session");stored.paidActive=true;stored.lastPaidMessageAt=Date.now();let walletBody;const room=new ChatSession(state,{SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service",FETCHER:async(_url,options)=>{walletBody=JSON.parse(options.body);return Response.json([{balance:990,idempotent:false}]);}});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"paid-event-1",payload:{text:"still here"}}));assert.equal(walletBody.credit_delta,-10);assert.equal(walletBody.ledger_idempotency_key,"message:session-paid:paid-event-1:user-a");assert.equal(b.sent[0].type,"MESSAGE_RECEIVED");assert.equal(a.sent[0].type,"MESSAGE_ACCEPTED");assert.equal(JSON.stringify(state.values.get("session")).includes("still here"),false);});
  it("holds without relay when the sender cannot pay",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=paidState();state.getWebSockets=()=>[a,b];state.values.get("session").paidActive=true;const room=new ChatSession(state,{SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service",FETCHER:async()=>Response.json({message:"insufficient_credits"},{status:400})});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"paid-event-2",payload:{text:"not delivered"}}));assert.equal(a.sent[0].type,"PAYMENT_HOLD");assert.equal(b.sent[0].type,"PAYMENT_HOLD");assert.equal(b.sent.some(event=>event.type==="MESSAGE_RECEIVED"),false);});
  it("does not charge or relay a duplicate accepted event",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=paidState();state.getWebSockets=()=>[a,b];Object.assign(state.values.get("session"),{paidActive:true,lastPaidMessageAt:Date.now(),acceptedEventIds:{"paid-event-3":Date.now()}});let calls=0;const room=new ChatSession(state,{FETCHER:async()=>{calls++;return Response.json([]);}});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"paid-event-3",payload:{text:"duplicate"}}));assert.equal(calls,0);assert.equal(b.sent.length,0);assert.equal(a.sent[0].payload.idempotent,true);});
  it("ends paid continuation after five minutes without messages",async()=>{const now=Date.now(),a=fakeSocket("a"),b=fakeSocket("b"),state=memoryState([a,b],{sessionId:"session-idle",participants:{a:{lastActivityAt:now,accountUserId:"user-a"},b:{lastActivityAt:now,accountUserId:"user-b"}},disconnects:{},startedAt:now-600000,freeExpiredAt:now-500000,paidActive:true,lastPaidMessageAt:now-301000,ended:false}),room=new ChatSession(state,{});await room.alarm();assert.equal(state.values.get("session").ended,true);assert.equal(a.sent.some(event=>event.payload.reason==="paid_idle_timeout"),true);});
  it("offers a five-minute hold at free expiry instead of ending immediately",async()=>{const now=Date.now(),a=fakeSocket("a"),b=fakeSocket("b"),state=memoryState([a,b],{sessionId:"session-hold",participants:{a:{lastActivityAt:now},b:{lastActivityAt:now}},disconnects:{},trialConsumed:{a:true,b:true},startedAt:now-121000,ended:false}),room=new ChatSession(state,{});await room.alarm();const saved=state.values.get("session");assert.equal(saved.ended,false);assert.ok(saved.continuationHoldUntil>now);assert.equal(a.sent.some(event=>event.type==="CONTINUE_REQUESTED"),true);});
});
