import { describe,it } from "node:test";
import assert from "node:assert/strict";
import { parseClientEvent,serverEvent } from "../worker/src/protocol.js";
import { ChatSession,migrateParticipantIdentity } from "../worker/src/durable/ChatSession.js";

function fakeSocket(participantId,connectionId){return{sent:[],closed:false,send(value){this.sent.push(JSON.parse(value))},close(){this.closed=true},deserializeAttachment(){return{participantId,resumeToken:`token-${participantId}`,...(connectionId?{connectionId}:{})}}};}
function memoryState(sockets,session={participants:{a:{lastActivityAt:0},b:{lastActivityAt:0}},disconnects:{},startedAt:0}){const values=new Map([["session",session],["participants",Object.fromEntries(Object.keys(session.participants||{}).map(id=>[id,{resumeToken:`token-${id}`}]))]]);return{getWebSockets:()=>sockets,storage:{get:key=>values.get(key),put:(key,value)=>values.set(key,structuredClone(value)),delete:key=>values.delete(key),setAlarm:()=>{}},values};}

describe("WebSocket protocol",()=>{
  it("accepts a versioned text message",()=>{const result=parseClientEvent(JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"e1",payload:{text:"Hi"}}));assert.equal(result.ok,true);assert.equal(result.event.payload.text,"Hi");});
  it("rejects malformed and oversized messages",()=>{assert.equal(parseClientEvent("not json").code,"invalid_json");assert.equal(parseClientEvent(JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"e1",payload:{text:"x".repeat(1001)}})).code,"message_too_large");});
  it("always emits a versioned server envelope",()=>assert.deepEqual(JSON.parse(serverEvent("READY",{ok:true})),{v:1,type:"READY",payload:{ok:true}}));
  it("accepts mutual continuation decisions",()=>{assert.equal(parseClientEvent(JSON.stringify({v:1,type:"CONTINUE_ACCEPT"})).ok,true);assert.equal(parseClientEvent(JSON.stringify({v:1,type:"CONTINUE_DECLINE"})).ok,true);});
  it("accepts an explicit safety-first session end",()=>assert.equal(parseClientEvent(JSON.stringify({v:1,type:"SESSION_END"})).ok,true));
});

describe("ChatSession relay",()=>{
  it("moves ephemeral room state to the newest account identity without resetting trial or consent",()=>{const session={participants:{old:{accountUserId:"user-a"},peer:{}},disconnects:{old:10},trialConsumed:{old:true},continueAccepted:{old:true},contactState:{old:{digits:"12"}}};migrateParticipantIdentity(session,"old","new");assert.equal(session.participants.old,undefined);assert.equal(session.participants.new.accountUserId,"user-a");assert.equal(session.trialConsumed.new,true);assert.equal(session.continueAccepted.new,true);assert.deepEqual(session.contactState.new,{digits:"12"});});
  it("ignores delayed close events from an account identity that was replaced",async()=>{const old=fakeSocket("old"),peer=fakeSocket("peer"),state=memoryState([old,peer],{sessionId:"takeover",participants:{new:{accountUserId:"user-a"},peer:{}},disconnects:{},startedAt:Date.now(),ended:false}),room=new ChatSession(state,{});await room.webSocketClose(old,4001,"account_takeover");assert.deepEqual(state.values.get("session").disconnects,{});assert.equal(peer.sent.length,0);});
  it("ignores delayed events from a superseded connection generation",async()=>{const old=fakeSocket("a","old-connection"),peer=fakeSocket("b","peer-connection"),state=memoryState([old,peer],{sessionId:"resume-race",participants:{a:{connectionId:"new-connection",lastActivityAt:1},b:{connectionId:"peer-connection",lastActivityAt:1}},disconnects:{},startedAt:Date.now(),ended:false}),room=new ChatSession(state,{});await room.webSocketMessage(old,JSON.stringify({v:1,type:"SESSION_END"}));await room.webSocketClose(old,1000,"stale_close");assert.equal(old.closed,true);assert.equal(state.values.get("session").ended,false);assert.deepEqual(state.values.get("session").disconnects,{});assert.equal(peer.sent.length,0);});
  it("clears the idle warning when the participant confirms activity",async()=>{const now=Date.now(),a=fakeSocket("a"),state=memoryState([a],{sessionId:"activity",participants:{a:{lastActivityAt:1,idle:true,warned:true}},disconnects:{},startedAt:now,ended:false}),room=new ChatSession(state,{});await room.webSocketMessage(a,JSON.stringify({v:1,type:"ACTIVITY"}));const participant=state.values.get("session").participants.a;assert.equal(participant.idle,false);assert.equal(participant.warned,false);assert.ok(participant.lastActivityAt>=now);});
  it("acknowledges and relays without persisting message text",async()=>{const sender=fakeSocket("a"),peer=fakeSocket("b"),state=memoryState([sender,peer]);const session=new ChatSession(state);await session.webSocketMessage(sender,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"event-1",payload:{text:"hello"}}));assert.equal(sender.sent[0].type,"MESSAGE_ACCEPTED");assert.equal(peer.sent[0].type,"MESSAGE_RECEIVED");assert.equal(peer.sent[0].payload.text,"hello");assert.equal(JSON.stringify(state.values.get("session")).includes("hello"),false);});
  it("rejects invalid input without relaying",async()=>{const sender=fakeSocket("a"),peer=fakeSocket("b");const session=new ChatSession(memoryState([sender,peer]));await session.webSocketMessage(sender,"bad");assert.equal(sender.sent[0].type,"MESSAGE_REJECTED");assert.equal(peer.sent.length,0);});
  it("announces disconnect and reconnect grace",async()=>{const sender=fakeSocket("a"),peer=fakeSocket("b");const session=new ChatSession(memoryState([sender,peer]));await session.webSocketClose(sender,1006,"gone");assert.deepEqual(peer.sent.map(event=>event.type),["PEER_DISCONNECTED","RECONNECT_GRACE"]);});
  it("lets either participant end immediately and notifies both sides",async()=>{const sender=fakeSocket("a"),peer=fakeSocket("b"),state=memoryState([sender,peer]),session=new ChatSession(state,{});await session.webSocketMessage(sender,JSON.stringify({v:1,type:"SESSION_END"}));assert.equal(state.values.get("session").ended,true);assert.equal(peer.sent[0].type,"SESSION_ENDED");assert.equal(peer.sent[0].payload.reason,"peer_ended");});
  it("releases matchmaking claims once when the authoritative room ends",async()=>{const state=memoryState([],{sessionId:"session-release",participants:{a:{lastActivityAt:1},b:{lastActivityAt:1}},disconnects:{},startedAt:1,ended:false}),calls=[],env={MATCHMAKING:{idFromName:name=>name,get:()=>({fetch:async(_url,options)=>{calls.push(JSON.parse(options.body));return Response.json({status:"ended"});}})}},room=new ChatSession(state,env);await room.fetch(new Request("https://chat.internal/admin/end",{method:"POST"}));await room.fetch(new Request("https://chat.internal/admin/end",{method:"POST"}));assert.deepEqual(calls,[{identityId:"a",sessionId:"session-release"}]);assert.equal(state.values.get("session").matchReleased,true);});
  it("discards temporary participant and consent state after a room ends",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=memoryState([a,b],{sessionId:"session-privacy",participants:{a:{lastActivityAt:1},b:{lastActivityAt:1}},disconnects:{},startedAt:1,acceptedEventIds:{event:1},continueAccepted:{a:true},contactState:{a:{digits:"12"}},trialConsumed:{a:true},ended:false}),room=new ChatSession(state,{});await room.webSocketMessage(a,JSON.stringify({v:1,type:"SESSION_END"}));assert.deepEqual(state.values.get("session"),{sessionId:"session-privacy",ended:true,matchReleased:true});assert.equal(state.values.has("participants"),false);});
  it("keeps only release identity while matchmaking cleanup retries",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=memoryState([a,b],{sessionId:"session-retry",participants:{a:{lastActivityAt:1},b:{lastActivityAt:1}},disconnects:{},contactState:{a:{digits:"12"}},startedAt:1,ended:false}),alarms=[],calls=[],env={MATCHMAKING:{idFromName:name=>name,get:()=>({fetch:async(_url,options)=>{calls.push(JSON.parse(options.body));return calls.length===1?new Response(null,{status:503}):Response.json({status:"ended"});}})}};state.storage.setAlarm=value=>alarms.push(value);const room=new ChatSession(state,env);await room.webSocketMessage(a,JSON.stringify({v:1,type:"SESSION_END"}));assert.deepEqual(state.values.get("session"),{sessionId:"session-retry",ended:true,matchReleaseIdentity:"a"});assert.equal(state.values.has("participants"),true);assert.ok(alarms.length>=1);await room.alarm();assert.deepEqual(state.values.get("session"),{sessionId:"session-retry",ended:true,matchReleased:true});assert.equal(state.values.has("participants"),false);assert.equal(calls.length,2);});
});

describe("paid continuation",()=>{
  const paidState=()=>memoryState([],{sessionId:"session-paid",participants:{a:{lastActivityAt:1,accountUserId:"user-a",virtual:false},b:{lastActivityAt:1,accountUserId:"user-b",virtual:false}},disconnects:{},startedAt:1,freeExpiredAt:2,continuationHoldUntil:Date.now()+300000,continueAccepted:{},ended:false});
  it("activates only after both registered participants accept",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=paidState();state.getWebSockets=()=>[a,b];const room=new ChatSession(state,{});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CONTINUE_ACCEPT"}));assert.equal(state.values.get("session").paidActive,undefined);await room.webSocketMessage(b,JSON.stringify({v:1,type:"CONTINUE_ACCEPT"}));assert.equal(state.values.get("session").paidActive,true);assert.equal(a.sent.at(-1).type,"CONTINUE_ACTIVATED");assert.equal(b.sent.at(-1).type,"CONTINUE_ACTIVATED");});
  it("debits 10 Credits idempotently before relaying a paid message",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=paidState();state.getWebSockets=()=>[a,b];const stored=state.values.get("session");stored.paidActive=true;stored.lastPaidMessageAt=Date.now();let walletBody;const room=new ChatSession(state,{SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service",FETCHER:async(_url,options)=>{walletBody=JSON.parse(options.body);return Response.json([{balance:990,idempotent:false}]);}});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"paid-event-1",payload:{text:"still here"}}));assert.equal(walletBody.credit_delta,-10);assert.equal(walletBody.ledger_idempotency_key,"message:session-paid:paid-event-1:user-a");assert.equal(b.sent[0].type,"MESSAGE_RECEIVED");assert.equal(a.sent[0].type,"MESSAGE_ACCEPTED");assert.equal(JSON.stringify(state.values.get("session")).includes("still here"),false);});
  it("holds without relay when the sender cannot pay",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=paidState();state.getWebSockets=()=>[a,b];state.values.get("session").paidActive=true;const room=new ChatSession(state,{SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service",FETCHER:async()=>Response.json({message:"insufficient_credits"},{status:400})});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"paid-event-2",payload:{text:"not delivered"}}));assert.equal(a.sent[0].type,"PAYMENT_HOLD");assert.equal(b.sent[0].type,"PAYMENT_HOLD");assert.equal(b.sent.some(event=>event.type==="MESSAGE_RECEIVED"),false);});
  it("compensates a paid debit when the peer socket cannot accept the relay",async()=>{const a=fakeSocket("a"),b=fakeSocket("b");b.send=()=>{throw new Error("socket closed")};const state=paidState();state.getWebSockets=()=>[a,b];state.values.get("session").paidActive=true;const deltas=[],room=new ChatSession(state,{SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service",FETCHER:async(_url,options)=>{deltas.push(JSON.parse(options.body));return Response.json([{balance:1000,idempotent:false}]);}});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"paid-event-undelivered",payload:{text:"not delivered"}}));assert.deepEqual(deltas.map(item=>item.credit_delta),[-10,10]);assert.match(deltas[1].ledger_idempotency_key,/^message-reversal:/);assert.equal(a.sent.at(-1).type,"MESSAGE_REJECTED");assert.equal(a.sent.at(-1).payload.code,"peer_unavailable");assert.equal(state.values.get("session").pendingMessageReversals,undefined);});
  it("retries a pending paid-message reversal after the room has ended",async()=>{const state=memoryState([],{sessionId:"session-ended-reversal",participants:{a:{accountUserId:"user-a"}},disconnects:{},startedAt:1,ended:true,matchReleased:true,pendingMessageReversals:{"event-pending":{userId:"user-a",participantId:"a",amount:10,createdAt:1}}}),calls=[],room=new ChatSession(state,{SUPABASE_URL:"https://project",SUPABASE_SERVICE_ROLE_KEY:"service",FETCHER:async(_url,options)=>{calls.push(JSON.parse(options.body));return Response.json([{balance:1000,idempotent:false}]);}});await room.alarm();assert.equal(calls[0].credit_delta,10);assert.equal(calls[0].ledger_idempotency_key,"message-reversal:session-ended-reversal:event-pending:user-a");assert.equal(state.values.get("session").pendingMessageReversals,undefined);assert.equal(JSON.stringify(state.values.get("session")).includes("message text"),false);});
  it("does not charge or relay a duplicate accepted event",async()=>{const a=fakeSocket("a"),b=fakeSocket("b"),state=paidState();state.getWebSockets=()=>[a,b];Object.assign(state.values.get("session"),{paidActive:true,lastPaidMessageAt:Date.now(),acceptedEventIds:{"paid-event-3":Date.now()}});let calls=0;const room=new ChatSession(state,{FETCHER:async()=>{calls++;return Response.json([]);}});await room.webSocketMessage(a,JSON.stringify({v:1,type:"CHAT_MESSAGE",eventId:"paid-event-3",payload:{text:"duplicate"}}));assert.equal(calls,0);assert.equal(b.sent.length,0);assert.equal(a.sent[0].payload.idempotent,true);});
  it("ends paid continuation after five minutes without messages",async()=>{const now=Date.now(),a=fakeSocket("a"),b=fakeSocket("b"),state=memoryState([a,b],{sessionId:"session-idle",participants:{a:{lastActivityAt:now,accountUserId:"user-a"},b:{lastActivityAt:now,accountUserId:"user-b"}},disconnects:{},startedAt:now-600000,freeExpiredAt:now-500000,paidActive:true,lastPaidMessageAt:now-301000,ended:false}),room=new ChatSession(state,{});await room.alarm();assert.equal(state.values.get("session").ended,true);assert.equal(a.sent.some(event=>event.payload.reason==="paid_idle_timeout"),true);});
  it("offers a five-minute hold at free expiry instead of ending immediately",async()=>{const now=Date.now(),a=fakeSocket("a"),b=fakeSocket("b"),state=memoryState([a,b],{sessionId:"session-hold",participants:{a:{lastActivityAt:now},b:{lastActivityAt:now}},disconnects:{},trialConsumed:{a:true,b:true},startedAt:now-121000,ended:false}),room=new ChatSession(state,{});await room.alarm();const saved=state.values.get("session");assert.equal(saved.ended,false);assert.ok(saved.continuationHoldUntil>now);assert.equal(a.sent.some(event=>event.type==="CONTINUE_REQUESTED"),true);});
});
