import { ChatSession } from "./durable/ChatSession.js";
import { MatchmakingShard } from "./durable/MatchmakingShard.js";
import { PresenceShard } from "./durable/PresenceShard.js";
import { AnonymousIdentityShard } from "./durable/AnonymousIdentityShard.js";
import { ipPrefix,keyedFingerprint,verifyAnonymousToken } from "./auth/anonymousToken.js";
import { verifySupabaseUser,supabaseRest } from "./auth/supabaseUser.js";
import { DeviceOwnershipShard } from "./durable/DeviceOwnershipShard.js";
import { validUsername } from "./policies/usernamePolicy.js";
import { PaymentService } from "./services/PaymentService.js";
import { hasPaidPreferences,normalizePaidPreferences } from "./policies/preferencePolicy.js";
import { ConfigService } from "./services/ConfigService.js";
import { DEFAULT_AD_CONFIG } from "./policies/adPolicy.js";
import { AdminService } from "./services/AdminService.js";
import { RestrictionService } from "./services/RestrictionService.js";
import { AnalyticsService,CLIENT_ANALYTICS_EVENTS,approximatePublicCount } from "./services/AnalyticsService.js";
import { AccountPrivacyService } from "./services/AccountPrivacyService.js";
import { RateLimitShard } from "./durable/RateLimitShard.js";
import { DailyAccessService } from "./services/DailyAccessService.js";

const MAX_API_BODY_BYTES=64*1024,MAX_WEBHOOK_BODY_BYTES=256*1024;
function shard(env,binding,name="global"){const namespace=env[binding];return namespace.get(namespace.idFromName(name));}
function bearer(request){const value=request.headers.get("authorization")||"";return value.startsWith("Bearer ")?value.slice(7):null}
function webSocketToken(request){return(request.headers.get("sec-websocket-protocol")||"").split(",").map(value=>value.trim()).find(value=>value.startsWith("rc-auth."))?.slice(8)||null}
export async function readTextBody(request,maxBytes,errorCode="payload_too_large"){const declared=request.headers.get("content-length");if(declared&&Number(declared)>maxBytes)throw new Error(errorCode);if(!request.body)return"";const reader=request.body.getReader(),decoder=new TextDecoder();let size=0,result="";try{while(true){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBytes){await reader.cancel();throw new Error(errorCode);}result+=decoder.decode(value,{stream:true});}return result+decoder.decode();}finally{reader.releaseLock();}}
async function anonymousClaims(request,env,token=bearer(request)){return env.ANON_SESSION_SECRET?verifyAnonymousToken(token,env.ANON_SESSION_SECRET):null}
async function anonymousStub(env){return shard(env,"ANONYMOUS")}
async function enforceRateLimit(request,env,bucket,key){if(!env?.RATE_LIMIT||!env?.ANON_SESSION_SECRET)return null;const prefix=ipPrefix(request.headers.get("CF-Connecting-IP")||"unknown"),fingerprint=await keyedFingerprint(`${bucket}:${key||prefix}`,env.ANON_SESSION_SECRET),namespace=env.RATE_LIMIT,stub=namespace.get(namespace.idFromName(`${bucket}:${fingerprint.slice(0,4)}`)),response=await stub.fetch("https://rate.internal/check",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bucket,key:fingerprint})});if(response.ok)return null;const result=await response.json();return Response.json({error:"rate_limited",retryAt:result.retryAt},{status:429,headers:{"retry-after":String(Math.max(1,Math.ceil((result.retryAt-Date.now())/1000)))}});}
async function endMatches(env,targetRef){if(!env?.MATCHMAKING)return null;const response=await shard(env,"MATCHMAKING").fetch("https://match.internal/admin/restrict",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetRef})}),result=await response.json();if(env.CHAT_SESSION)await Promise.all((result.sessionIds||[]).map(sessionId=>{const namespace=env.CHAT_SESSION;return namespace.get(namespace.idFromName(sessionId)).fetch("https://chat.internal/admin/end",{method:"POST"});}));return result;}
export async function activateRequiredDailyAccess({eligibility,user,env,fetcher=env.FETCHER||fetch}){if(!eligibility?.accountRequired)return null;if(!user?.emailVerified)throw new Error("verified_account_required");return new DailyAccessService({url:env.SUPABASE_URL,serviceKey:env.SUPABASE_SERVICE_ROLE_KEY,fetcher}).activate({userId:user.id});}
async function proxyJson(request,env,path,{authorizeSearch=false,activity}={}){
  const claims=await anonymousClaims(request,env);if(!claims)return Response.json({error:"invalid_anonymous_session"},{status:401});if(authorizeSearch){const limited=await enforceRateLimit(request,env,"search",claims.sub);if(limited)return limited;}const anon=await anonymousStub(env),body=await request.json();
  if(authorizeSearch){try{const preferences=normalizePaidPreferences(body.preferences||{});body.preferences=preferences;const accountToken=request.headers.get("x-account-authorization"),accountRequest=new Request(request.url,{headers:{authorization:accountToken||""}}),user=accountToken?await verifySupabaseUser(accountRequest,env):null;if(hasPaidPreferences(preferences)&&!user?.emailVerified)return Response.json({error:"verified_account_required_for_preferences"},{status:403});if(user){const deletions=await new AccountPrivacyService(env,env.FETCHER||fetch).deletionRequested(user.id);if(deletions.length)return Response.json({error:"account_deletion_pending"},{status:403});if(user.emailVerified){body.accountUserId=user.id;const [blocks,profiles]=await Promise.all([supabaseRest(env,user,"/blocks?select=blocked_ref"),supabaseRest(env,user,`/profiles?select=public_id&user_id=eq.${encodeURIComponent(user.id)}&limit=1`)]);if(blocks.ok)body.blockedRefs=(await blocks.json()).map(item=>item.blocked_ref);if(profiles.ok)body.accountPublicId=(await profiles.json())[0]?.public_id||null;}}const restrictions=await new RestrictionService(env,env.FETCHER||fetch).find([claims.sub,user?.id,body.accountPublicId]);if(restrictions.length)return Response.json({error:"account_restricted",status:restrictions[0].status},{status:403});const allowed=await anon.fetch("https://anonymous.internal/authorize-search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId:claims.sub,registered:Boolean(user?.emailVerified)})});if(!allowed.ok)return allowed;await activateRequiredDailyAccess({eligibility:await allowed.json(),user,env});}catch(error){return Response.json({error:error.message},{status:error.message.includes("insufficient")?402:400});}}
  body.identityId=claims.sub;if(activity){await anon.fetch("https://anonymous.internal/activity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:activity})});await recordAnalytics(env,{eventId:`${activity}:${crypto.randomUUID()}`,eventName:activity,dimension:body.accountUserId?"registered":"anonymous"});if(hasPaidPreferences(body.preferences||{}))await recordAnalytics(env,{eventId:`preference-search:${crypto.randomUUID()}`,eventName:"preference_search_started",dimension:"paid"});}return shard(env,"MATCHMAKING").fetch(`https://match.internal${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
}
export async function adminUser(request,env,verify=verifySupabaseUser){const user=await verify(request,env);if(!user)return{error:Response.json({error:"invalid_admin_session"},{status:401})};if(!user.emailVerified||!env.ADMIN_USER_ID||user.id!==env.ADMIN_USER_ID)return{error:Response.json({error:"admin_forbidden"},{status:403})};if(env.ADMIN_REQUIRE_AAL2!=="false"&&user.aal!=="aal2")return{error:Response.json({error:"admin_mfa_required"},{status:403})};return{user};}
async function recordAnalytics(env,event){if(!env?.SUPABASE_URL||!env?.SUPABASE_SERVICE_ROLE_KEY||(env.FETCHER&&!env.ANALYTICS_FETCHER))return;try{return await new AnalyticsService(env,env.ANALYTICS_FETCHER||fetch).record(event)}catch{return null}}
export function allowedOrigin(request,env){const origin=request.headers.get("origin");if(!origin)return null;const configured=String(env.ALLOWED_ORIGINS||env.ALLOWED_ORIGIN||"").split(",").map(value=>value.trim()).filter(Boolean),sameOrigin=new URL(request.url).origin;return new Set([...configured,sameOrigin]).has(origin)?origin:false;}
export function secureResponse(response,request,env){if(response.status===101)return response;const headers=new Headers(response.headers),origin=allowedOrigin(request,env);headers.set("x-content-type-options","nosniff");headers.set("referrer-policy","no-referrer");headers.set("permissions-policy","camera=(), microphone=(), geolocation=()");headers.set("cross-origin-opener-policy","same-origin");headers.set("cross-origin-resource-policy","same-site");headers.set("strict-transport-security","max-age=31536000; includeSubDomains");headers.set("x-frame-options","DENY");headers.set("vary","Origin");headers.set("cache-control",request.method==="GET"&&["/api/v1/config/public","/api/v1/stats/public","/api/v1/compliance/public"].includes(new URL(request.url).pathname)?"public, max-age=30":"no-store");if(origin){headers.set("access-control-allow-origin",origin);headers.set("access-control-allow-credentials","true");}return new Response(response.body,{status:response.status,statusText:response.statusText,headers});}

async function handleRequest(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/api/v1/health") return Response.json({ ok: true, service: "random-chat-worker", phase: 23 });
    if(request.method==="GET"&&url.pathname==="/api/v1/config/public"){try{const ads=await new ConfigService(env).ads();return Response.json({ads:ads.config,version:ads.version});}catch{return Response.json({ads:DEFAULT_AD_CONFIG,version:0});}}
    if(request.method==="POST"&&url.pathname==="/api/v1/analytics/event"){const limited=await enforceRateLimit(request,env,"analytics");if(limited)return limited;const body=await request.json().catch(()=>({}));if(!CLIENT_ANALYTICS_EVENTS.has(body.eventName)||!/^[a-zA-Z0-9_-]{8,160}$/.test(body.eventId||""))return Response.json({error:"invalid_analytics_event"},{status:400});const result=await recordAnalytics(env,{eventId:`client:${body.eventId}`,eventName:body.eventName,dimension:"anonymous"});return result?Response.json(result):Response.json({recorded:false},{status:503});}
    if(request.method==="GET"&&url.pathname==="/api/v1/stats/public"){try{const snapshot=await new AnalyticsService(env,env.ANALYTICS_FETCHER||fetch).publicSnapshot();return Response.json({realConnectionsToday:approximatePublicCount(snapshot.realConnectionsToday),virtualConnectionsToday:approximatePublicCount(snapshot.virtualConnectionsToday),messagesToday:approximatePublicCount(snapshot.messagesToday),asOf:snapshot.asOf,approximate:true});}catch{return Response.json({error:"stats_temporarily_unavailable"},{status:503});}}
    if(url.pathname.startsWith("/api/v1/admin/")){
      const authorization=await adminUser(request,env);if(authorization.error)return authorization.error;const user=authorization.user,config=new ConfigService(env,env.FETCHER||fetch),admin=new AdminService(env,env.FETCHER||fetch);try{
        if(url.pathname==="/api/v1/admin/ads"&&(request.method==="GET"||request.method==="PUT")){if(request.method==="GET")return Response.json(await config.ads());const body=await request.json();if(!Number.isSafeInteger(body.expectedVersion))return Response.json({error:"invalid_config_version"},{status:400});return Response.json(await config.updateAds({adminId:user.id,expectedVersion:body.expectedVersion,config:body.config}));}
        if(url.pathname==="/api/v1/admin/virtual"&&(request.method==="GET"||request.method==="PUT")){if(request.method==="GET")return Response.json(await config.virtual());const body=await request.json();if(!Number.isSafeInteger(body.expectedVersion))return Response.json({error:"invalid_config_version"},{status:400});return Response.json(await config.updateVirtual({adminId:user.id,expectedVersion:body.expectedVersion,config:body.config}));}
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/dashboard"){const [persistent,presenceResponse,matchResponse,analytics]=await Promise.all([admin.dashboard(),shard(env,"PRESENCE").fetch("https://presence.internal/stats"),shard(env,"MATCHMAKING").fetch("https://match.internal/admin/stats"),new AnalyticsService(env,env.ANALYTICS_FETCHER||fetch).adminSnapshot(30)]);return Response.json({persistent:Array.isArray(persistent)?persistent[0]:persistent,presence:await presenceResponse.json(),matchmaking:await matchResponse.json(),analytics});}
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/users")return Response.json({users:await admin.users(Number(url.searchParams.get("limit")||50),Number(url.searchParams.get("offset")||0))});
        const ledgerMatch=url.pathname.match(/^\/api\/v1\/admin\/users\/([0-9a-f-]{36})\/ledger$/i);if(request.method==="GET"&&ledgerMatch)return Response.json({entries:await admin.ledger(ledgerMatch[1])});
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/reports")return Response.json({reports:await admin.reports()});
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/grievances")return Response.json({grievances:await admin.grievances()});
        const grievanceMatch=url.pathname.match(/^\/api\/v1\/admin\/grievances\/([0-9a-f-]{36})$/i);if(request.method==="POST"&&grievanceMatch){const body=await request.json();if(!["acknowledged","in_review","resolved","rejected"].includes(body.status))return Response.json({error:"invalid_grievance_status"},{status:400});return Response.json({grievance:await admin.updateGrievance({adminId:user.id,id:grievanceMatch[1],status:body.status})});}
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/deletions")return Response.json({deletions:await admin.deletions()});
        const deletionMatch=url.pathname.match(/^\/api\/v1\/admin\/deletions\/([0-9a-f-]{36})$/i);if(request.method==="POST"&&deletionMatch){const body=await request.json(),note=String(body.note||"").trim();if(!["processing","completed","rejected"].includes(body.status)||note.length<10)return Response.json({error:"invalid_deletion_transition"},{status:400});return Response.json({deletion:await admin.updateDeletion({adminId:user.id,id:deletionMatch[1],status:body.status,note})});}
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/restrictions")return Response.json({restrictions:await admin.restrictions()});
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/offers")return Response.json({offers:await admin.promotions("offer")});
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/coupons")return Response.json({coupons:await admin.promotions("coupon")});
        if(request.method==="GET"&&url.pathname==="/api/v1/admin/audit")return Response.json({audit:await admin.audit()});
        if(request.method==="POST"&&url.pathname==="/api/v1/admin/wallet"){const body=await request.json(),delta=Number(body.delta);if(!/^[0-9a-f-]{36}$/i.test(body.userId||"")||!Number.isSafeInteger(delta)||delta===0||typeof body.reason!=="string"||!/^[0-9a-f-]{36}$/i.test(body.operationId||""))return Response.json({error:"invalid_wallet_adjustment"},{status:400});return Response.json({result:(await admin.wallet({adminId:user.id,userId:body.userId,delta,reason:body.reason,operationId:body.operationId}))[0]});}
        if(request.method==="POST"&&url.pathname==="/api/v1/admin/restrictions"){const body=await request.json();if(typeof body.targetRef!=="string"||!["restricted","banned","clear"].includes(body.status)||typeof body.reason!=="string")return Response.json({error:"invalid_restriction"},{status:400});const result=await admin.restrict({adminId:user.id,targetRef:body.targetRef,status:body.status,reason:body.reason}),enforcement=body.status!=="clear"?await endMatches(env,body.targetRef):null;return Response.json({restriction:result,enforcement});}
        if(request.method==="POST"&&url.pathname==="/api/v1/admin/promotions"){const body=await request.json();if(!["offer","coupon"].includes(body.type)||!body.payload||typeof body.payload!=="object")return Response.json({error:"invalid_promotion"},{status:400});return Response.json({promotion:await admin.savePromotion({adminId:user.id,type:body.type,payload:body.payload})});}
        return Response.json({error:"admin_route_not_found"},{status:404});
      }catch(error){return Response.json({error:error.message},{status:error.message.includes("version_conflict")||error.message.includes("insufficient")?409:400});}
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/anonymous/session"){
      if(!env.ANON_SESSION_SECRET)return Response.json({error:"anonymous_sessions_not_configured"},{status:503});const limited=await enforceRateLimit(request,env,"anonymous_session");if(limited)return limited;const body=await request.json(),prefix=ipPrefix(request.headers.get("CF-Connecting-IP")||"unknown"),ipHash=await keyedFingerprint(prefix,env.ANON_SESSION_SECRET);return (await anonymousStub(env)).fetch("https://anonymous.internal/issue",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,ipHash})});
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/grievances"){const limited=await enforceRateLimit(request,env,"grievance");if(limited)return limited;const body=await request.json().catch(()=>({})),email=String(body.email||"").trim().toLowerCase(),category=String(body.category||""),description=String(body.description||"").trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!["privacy","safety","account","payment","content","other"].includes(category)||description.length<20||description.length>2000)return Response.json({error:"invalid_grievance"},{status:400});const grievance=await new AccountPrivacyService(env,env.FETCHER||fetch).grievance({email,category,description});return Response.json({received:true,reference:grievance.id,receivedAt:grievance.received_at},{status:201});}
    if(request.method==="GET"&&url.pathname==="/api/v1/compliance/public")return Response.json({grievanceOfficer:{name:env.GRIEVANCE_OFFICER_NAME||null,email:env.GRIEVANCE_EMAIL||null,configured:Boolean(env.GRIEVANCE_OFFICER_NAME&&env.GRIEVANCE_EMAIL)},responseTargets:{acknowledgeHours:24,resolveDays:15},legalReviewRequired:true});
    if(request.method==="GET"&&url.pathname==="/api/v1/me/export"){const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});return Response.json(await new AccountPrivacyService(env,env.FETCHER||fetch).export(user.id),{headers:{"content-disposition":"attachment; filename=random-chat-data.json"}});}
    if(request.method==="DELETE"&&url.pathname==="/api/v1/me/account"){const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});const body=await request.json().catch(()=>({}));if(body.confirm!=="DELETE")return Response.json({error:"deletion_confirmation_required"},{status:400});const result=await new AccountPrivacyService(env,env.FETCHER||fetch).requestDeletion(user.id,String(body.reason||""));await endMatches(env,user.id);return Response.json({requested:true,request:Array.isArray(result)?result[0]:result},{status:202});}
    if(request.method==="GET"&&url.pathname==="/api/v1/me/profile"){
      const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});const response=await supabaseRest(env,user,`/profiles?select=public_id,username,username_change_count,username_changed_at&user_id=eq.${encodeURIComponent(user.id)}&limit=1`);if(!response.ok)return Response.json({error:"profile_lookup_failed"},{status:502});const [profile]=await response.json();return Response.json({user:{id:user.id,email:user.email,emailVerified:user.emailVerified},profile:profile||null});
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/username"){
      const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});if(!user.emailVerified)return Response.json({error:"email_verification_required"},{status:403});const body=await request.json(),username=String(body.username||"").trim();if(!validUsername(username))return Response.json({error:"invalid_username"},{status:400});const response=await supabaseRest(env,user,"/rpc/claim_username",{method:"POST",body:JSON.stringify({desired_username:username})});if(!response.ok){const error=await response.json().catch(()=>({}));return Response.json({error:error.message||"username_update_failed"},{status:response.status===409?409:400});}return Response.json({profile:(await response.json())[0]||null});
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/account/device/claim"){
      const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});const body=await request.json(),stub=shard(env,"DEVICE_OWNERSHIP",user.id);return stub.fetch("https://device.internal/claim",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deviceId:body.deviceId})});
    }
    if(request.method==="GET"&&url.pathname==="/api/v1/wallet"){
      const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});const response=await supabaseRest(env,user,`/wallets?select=balance,version,updated_at&user_id=eq.${encodeURIComponent(user.id)}&limit=1`);if(!response.ok)return Response.json({error:"wallet_lookup_failed"},{status:502});const [wallet]=await response.json();return Response.json({wallet:wallet||{balance:0,version:0}});
    }
    if(request.method==="GET"&&url.pathname==="/api/v1/wallet/ledger"){
      const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});const response=await supabaseRest(env,user,"/wallet_ledger?select=id,delta,balance_after,entry_type,reason,created_at&order=created_at.desc&limit=50");if(!response.ok)return Response.json({error:"ledger_lookup_failed"},{status:502});return Response.json({entries:await response.json()});
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/payments/orders"){
      const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});if(!user.emailVerified)return Response.json({error:"email_verification_required"},{status:403});const limited=await enforceRateLimit(request,env,"payment",user.id);if(limited)return limited;try{const body=await request.json(),order=await new PaymentService(env).createOrder(user,Number(body.amountPaise),body.couponCode?String(body.couponCode):null);await recordAnalytics(env,{eventId:`recharge-started:${order.orderId}`,eventName:"recharge_started",dimension:"registered",value:order.amountPaise});return Response.json(order);}catch(error){await recordAnalytics(env,{eventId:`recharge-failed:${crypto.randomUUID()}`,eventName:"recharge_failed",dimension:"registered"});return Response.json({error:error.message},{status:error.message.includes("coupon")||error.message==="minimum_recharge_50"?400:502});}
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/payments/verify"){
      const user=await verifySupabaseUser(request,env);if(!user)return Response.json({error:"invalid_account_session"},{status:401});const limited=await enforceRateLimit(request,env,"payment",user.id);if(limited)return limited;try{const body=await request.json(),paymentId=String(body.razorpay_payment_id||""),result=await new PaymentService(env).verifyCheckout({user,orderId:String(body.razorpay_order_id||""),paymentId,signature:String(body.razorpay_signature||"")});await recordAnalytics(env,{eventId:`recharge-success:${paymentId}`,eventName:"recharge_success",dimension:"registered"});return Response.json({verified:true,result:result[0]});}catch(error){await recordAnalytics(env,{eventId:`recharge-failed:${crypto.randomUUID()}`,eventName:"recharge_failed",dimension:"registered"});return Response.json({error:error.message},{status:error.message==="invalid_payment_signature"?400:409});}
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/payments/webhook"){
      try{const rawBody=await readTextBody(request,MAX_WEBHOOK_BODY_BYTES,"webhook_payload_too_large"),result=await new PaymentService(env).webhook(rawBody,request.headers.get("x-razorpay-signature")||"",request.headers.get("x-razorpay-event-id")||"");if(result.paymentId&&["payment.captured","order.paid"].includes(result.eventType))await recordAnalytics(env,{eventId:`recharge-success:${result.paymentId}`,eventName:"recharge_success",dimension:"registered"});return Response.json(result);}catch(error){return Response.json({error:error.message},{status:error.message.includes("signature")?401:error.message==="webhook_payload_too_large"?413:400});}
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/reconnect/request"){
      const claims=await anonymousClaims(request,env);if(!claims)return Response.json({error:"invalid_anonymous_session"},{status:401});const accountToken=request.headers.get("x-account-authorization"),accountRequest=new Request(request.url,{headers:{authorization:accountToken||""}}),user=await verifySupabaseUser(accountRequest,env);if(!user?.emailVerified)return Response.json({error:"verified_account_required"},{status:403});const profileResponse=await supabaseRest(env,user,`/profiles?select=public_id&user_id=eq.${encodeURIComponent(user.id)}&limit=1`),profile=profileResponse.ok?(await profileResponse.json())[0]:null,restrictions=await new RestrictionService(env,env.FETCHER||fetch).find([claims.sub,user.id,profile?.public_id]);if(restrictions.length)return Response.json({error:"account_restricted",status:restrictions[0].status},{status:403});const body=await request.json();return shard(env,"MATCHMAKING").fetch("https://match.internal/reconnect/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({initiatorId:claims.sub,initiatorUserId:user.id,initiatorPublicId:profile?.public_id||null,targetId:String(body.targetPeerId||"")})});
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/reconnect/cancel"){const claims=await anonymousClaims(request,env);if(!claims)return Response.json({error:"invalid_anonymous_session"},{status:401});return shard(env,"MATCHMAKING").fetch("https://match.internal/reconnect/cancel",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({initiatorId:claims.sub})});}
    if(request.method==="GET"&&url.pathname==="/api/v1/reconnect/request"){
      const claims=await anonymousClaims(request,env);if(!claims)return Response.json({error:"invalid_anonymous_session"},{status:401});return shard(env,"MATCHMAKING").fetch(`https://match.internal/reconnect/poll/${claims.sub}`);
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/reconnect/respond"){
      const claims=await anonymousClaims(request,env);if(!claims)return Response.json({error:"invalid_anonymous_session"},{status:401});const body=await request.json();return shard(env,"MATCHMAKING").fetch("https://match.internal/reconnect/respond",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetId:claims.sub,requestId:String(body.requestId||""),accepted:body.accepted===true})});
    }
    if(request.method==="POST"&&url.pathname==="/api/v1/match/search")return proxyJson(request,env,"/search",{authorizeSearch:true,activity:"search_started"});
    if(request.method==="POST"&&url.pathname==="/api/v1/match/cancel")return proxyJson(request,env,"/cancel");
    if(request.method==="POST"&&url.pathname==="/api/v1/match/end")return proxyJson(request,env,"/end");
    if(request.method==="GET"&&url.pathname==="/api/v1/match/result"){const claims=await anonymousClaims(request,env);if(!claims)return Response.json({error:"invalid_anonymous_session"},{status:401});return shard(env,"MATCHMAKING").fetch(`https://match.internal/result/${claims.sub}`);}
    if(request.method==="POST"&&url.pathname==="/api/v1/presence/heartbeat"){const claims=await anonymousClaims(request,env);if(!claims)return Response.json({error:"invalid_anonymous_session"},{status:401});const body=await request.json(),accountToken=request.headers.get("x-account-authorization"),accountRequest=new Request(request.url,{headers:{authorization:accountToken||""}}),account=accountToken?await verifySupabaseUser(accountRequest,env):null;let publicRef=null;if(account?.emailVerified){const response=await supabaseRest(env,account,`/profiles?select=public_id&user_id=eq.${encodeURIComponent(account.id)}&limit=1`);if(response.ok)publicRef=(await response.json())[0]?.public_id||null;}return shard(env,"PRESENCE").fetch("https://presence.internal/status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,identityId:claims.sub,anonymous:!account?.emailVerified,accountUserId:account?.emailVerified?account.id:null,publicRef})});}
    const match = url.pathname.match(/^\/api\/v1\/chat\/([a-zA-Z0-9_-]{8,80})\/socket$/);
    if (match) {
      if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") return Response.json({ error: "websocket_upgrade_required" }, { status: 426 });
      const claims=await anonymousClaims(request,env,webSocketToken(request));if(!claims)return Response.json({error:"invalid_anonymous_session"},{status:401});
      const authorized=await shard(env,"MATCHMAKING").fetch("https://match.internal/authorize-session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId:claims.sub,sessionId:match[1]})});if(!authorized.ok)return Response.json({error:"session_not_authorized"},{status:403});const authorization=await authorized.json();
      const id = env.CHAT_SESSION.idFromName(match[1]);
      const internal=new URL(`https://chat.internal${url.pathname}`),headers=new Headers(request.headers);internal.searchParams.set("identityId",claims.sub);if(authorization.accountUserId)internal.searchParams.set("accountUserId",authorization.accountUserId);if(authorization.accountPublicId)internal.searchParams.set("accountPublicId",authorization.accountPublicId);if(authorization.virtual)internal.searchParams.set("virtual","1");if(authorization.virtualPeer)internal.searchParams.set("virtualPeer",JSON.stringify(authorization.virtualPeer));if(url.searchParams.get("resumeToken"))internal.searchParams.set("resumeToken",url.searchParams.get("resumeToken"));headers.delete("authorization");headers.set("sec-websocket-protocol","random-chat.v1");return env.CHAT_SESSION.get(id).fetch(new Request(internal,{method:"GET",headers}));
    }
    return Response.json({ error: "not_found" }, { status: 404 });
  }
export default {async fetch(request,env){const origin=allowedOrigin(request,env);if(origin===false)return secureResponse(Response.json({error:"origin_not_allowed"},{status:403}),request,env);if(request.method==="OPTIONS"){const response=new Response(null,{status:204,headers:{"access-control-allow-methods":"GET, POST, PUT, DELETE, OPTIONS","access-control-allow-headers":"authorization, x-account-authorization, content-type, x-event-id","access-control-max-age":"86400"}});return secureResponse(response,request,env);}try{const url=new URL(request.url),hasApiBody=["POST","PUT","DELETE"].includes(request.method)&&request.body&&url.pathname!=="/api/v1/payments/webhook";if(hasApiBody){const body=await readTextBody(request,MAX_API_BODY_BYTES);request=new Request(request.url,{method:request.method,headers:request.headers,body});}return secureResponse(await handleRequest(request,env),request,env);}catch(error){if(error.message==="payload_too_large")return secureResponse(Response.json({error:error.message},{status:413}),request,env);const requestId=crypto.randomUUID();console.error("Unhandled request error",{requestId,name:error?.name});return secureResponse(Response.json({error:"internal_error",requestId},{status:500}),request,env);}}};
export { AnonymousIdentityShard,ChatSession,DeviceOwnershipShard,MatchmakingShard,PresenceShard,RateLimitShard };
