import { parseClientEvent,serverEvent } from "../protocol.js";
import { SESSION_DEFAULTS } from "../config/defaults.js";
import { idleDecision,reconnectDecision,skipDecision,timerState } from "../policies/sessionPolicy.js";
import { WalletService } from "../services/WalletService.js";
import { checkContactMessage } from "../../../web/js/contact-guard.js";
import { ContactUnlockService } from "../services/ContactUnlockService.js";
import { SafetyService } from "../services/SafetyService.js";
import { createVirtualParticipantProvider,virtualDelay } from "../services/VirtualParticipantProvider.js";
import { AnalyticsService } from "../services/AnalyticsService.js";
const PARTICIPANTS_KEY="participants",SESSION_KEY="session";
function virtualPeerFrom(value){if(!value||value.length>6000)return null;try{const peer=JSON.parse(value);return peer?.identityId&&peer?.persona&&peer?.config?peer:null}catch{return null}}
function isCurrentConnection(session,attachment){const participant=session.participants?.[attachment?.participantId];return Boolean(participant&&(!participant.connectionId||!attachment.connectionId||participant.connectionId===attachment.connectionId));}
export function migrateParticipantIdentity(session,previousIdentityId,participantId){if(!previousIdentityId||previousIdentityId===participantId)return session;session.participants??={};session.participants[participantId]={...(session.participants[previousIdentityId]||{}),...(session.participants[participantId]||{})};delete session.participants[previousIdentityId];for(const key of ["disconnects","trialConsumed","continueAccepted","contactUnlockAccepted","likes","messageRate","contactState"]){const values=session[key];if(!values||!Object.hasOwn(values,previousIdentityId))continue;values[participantId]=values[previousIdentityId];delete values[previousIdentityId];}return session;}

export class ChatSession{
  constructor(state,env){this.state=state;this.env=env}
  async fetch(request){
    const requestUrl=new URL(request.url);if(request.method==="POST"&&requestUrl.pathname==="/admin/end"){const session=(await this.state.storage.get(SESSION_KEY))||{participants:{}};session.ended=true;this.broadcast("SESSION_ENDED",{reason:"account_restricted"});await this.saveSession(session);return Response.json({ended:true});}
    if(request.headers.get("Upgrade")?.toLowerCase()!=="websocket")return Response.json({error:"websocket_upgrade_required"},{status:426});
    const active=this.state.getWebSockets(),url=requestUrl,requestedToken=url.searchParams.get("resumeToken"),claimedIdentity=url.searchParams.get("identityId"),virtualPeer=virtualPeerFrom(url.searchParams.get("virtualPeer")),requestedAccountUserId=url.searchParams.get("accountUserId");
    const participants=(await this.state.storage.get(PARTICIPANTS_KEY))||{},resumed=Object.entries(participants).find(([,value])=>value.resumeToken===requestedToken),replaced=!resumed&&requestedAccountUserId?Object.entries(participants).find(([,value])=>value.accountUserId===requestedAccountUserId):null;
    if(!resumed&&!replaced&&active.length>=2)return Response.json({error:"session_full"},{status:409});
    if(resumed||replaced)for(const socket of active)if(socket.deserializeAttachment()?.participantId===(replaced?.[0]||resumed?.[0]))try{socket.close(4001,replaced?"account_takeover":"session_resumed")}catch{}
    const previous=replaced?.[1]||resumed?.[1]||{},participantId=resumed?.[0]||(claimedIdentity?.match(/^[a-zA-Z0-9_-]{8,100}$/)?.[0])||crypto.randomUUID(),resumeToken=resumed?.[1].resumeToken||crypto.randomUUID(),connectionId=crypto.randomUUID(),now=Date.now(),accountUserId=previous.accountUserId||requestedAccountUserId||null,accountPublicId=previous.accountPublicId||url.searchParams.get("accountPublicId")||null,virtual=previous.virtual||url.searchParams.get("virtual")==="1";
    if(replaced)delete participants[replaced[0]];participants[participantId]={resumeToken,connectionId,joinedAt:previous.joinedAt||now,accountUserId,accountPublicId,virtual};await this.state.storage.put(PARTICIPANTS_KEY,participants);
    const pair=new WebSocketPair(),[client,server]=Object.values(pair);this.state.acceptWebSocket(server);server.serializeAttachment({participantId,resumeToken,connectionId});
    let session=(await this.state.storage.get(SESSION_KEY))||{participants:{},disconnects:{},trialConsumed:{},ended:false};if(replaced)migrateParticipantIdentity(session,replaced[0],participantId);session.sessionId??=url.pathname.split("/").filter(Boolean).at(-2);session.virtualPeer??=virtualPeer;session.participants[participantId]={...session.participants[participantId],connectionId,lastActivityAt:now,idle:false,accountUserId,accountPublicId,virtual};delete session.disconnects[participantId];
    if(!session.startedAt&&(active.length===1||session.virtualPeer)){session.startedAt=now;for(const participant of Object.values(session.participants))participant.lastActivityAt=now;}await this.saveSession(session);
    server.send(serverEvent("READY",{participantId,resumeToken,resumed:Boolean(resumed||replaced),accountTakeover:Boolean(replaced),...(session.virtualPeer?{peer:{virtual:true,profile:{handle:session.virtualPeer.persona.handle,age:session.virtualPeer.persona.age,region:session.virtualPeer.persona.region,languages:session.virtualPeer.persona.languages}}}:{})}));if(resumed||replaced)this.sendToPeers(server,"PEER_RETURNED",{participantId});
    if(new Set(this.state.getWebSockets().map(socket=>socket.deserializeAttachment()?.participantId).filter(Boolean)).size===2||session.virtualPeer){this.broadcast("CHAT_STARTED",{participantCount:2,virtual:Boolean(session.virtualPeer)});this.broadcast("TIMER_STATE",timerState(session.startedAt,now,SESSION_DEFAULTS));if(!session.connectionCounted){session.connectionCounted=true;await this.recordActivity(session.virtualPeer?"virtual_connection_started":"connection_started");}if(session.virtualPeer&&!session.virtualOpeningDecided){const provider=createVirtualParticipantProvider(this.env,session.virtualPeer.config,this.env.VIRTUAL_RANDOM||Math.random),opening=provider.opening();session.virtualOpeningDecided=true;session.virtualOpeningSent=Boolean(opening);if(opening)server.send(serverEvent("MESSAGE_RECEIVED",{from:session.virtualPeer.identityId,text:opening,virtual:true}));}await this.saveSession(session);}
    await this.scheduleNextAlarm(session,now);return new Response(null,{status:101,webSocket:client,headers:{"Sec-WebSocket-Protocol":"random-chat.v1"}});
  }
  async webSocketMessage(socket,raw){
    const parsed=parseClientEvent(raw);if(!parsed.ok)return socket.send(serverEvent("MESSAGE_REJECTED",{code:parsed.code}));
    const event=parsed.event,attachment=socket.deserializeAttachment(),now=Date.now();let session=(await this.state.storage.get(SESSION_KEY))||{participants:{},disconnects:{}};if(!isCurrentConnection(session,attachment)){try{socket.close(4001,"connection_replaced")}catch{}return;}
    session.participants[attachment.participantId]={...session.participants[attachment.participantId],lastActivityAt:now,idle:false,warned:false};
    if(event.type==="CHAT_MESSAGE")await this.handleMessage(socket,attachment.participantId,event,session,now);
    else if(event.type==="HELLO"||event.type==="SESSION_RESUME")socket.send(serverEvent("READY",{participantId:attachment.participantId,resumeToken:attachment.resumeToken,resumed:event.type==="SESSION_RESUME"}));
    else if(event.type==="HEARTBEAT"||event.type==="ACTIVITY")socket.send(serverEvent("TIMER_STATE",{...timerState(session.startedAt||now,now,SESSION_DEFAULTS),idle:false}));
    else if(event.type==="NEXT_REQUEST")await this.handleNext(socket,attachment.participantId,session,now);
    else if(event.type==="SESSION_END"){session.ended=true;this.broadcast("SESSION_ENDED",{reason:"peer_ended",by:attachment.participantId});}
    else if(event.type==="CONTINUE_ACCEPT")await this.handleContinue(socket,attachment.participantId,session,now,true);
    else if(event.type==="CONTINUE_DECLINE")await this.handleContinue(socket,attachment.participantId,session,now,false);
    else if(event.type==="CONTACT_UNLOCK_REQUEST")await this.handleContactUnlock(socket,attachment.participantId,session,now,"request");
    else if(event.type==="CONTACT_UNLOCK_ACCEPT")await this.handleContactUnlock(socket,attachment.participantId,session,now,"accept");
    else if(event.type==="CONTACT_UNLOCK_DECLINE")await this.handleContactUnlock(socket,attachment.participantId,session,now,"decline");
    else if(event.type==="LIKE")await this.handleSafetyAction(socket,attachment.participantId,session,"like");
    else if(event.type==="REPORT")await this.handleSafetyAction(socket,attachment.participantId,session,"report",event.payload.reason);
    else if(event.type==="BLOCK")await this.handleSafetyAction(socket,attachment.participantId,session,"block");
    await this.saveSession(session);await this.scheduleNextAlarm(session,now);
  }
  async handleMessage(socket,participantId,event,session,now){
    if(session.acceptedEventIds?.[event.eventId])return socket.send(serverEvent("MESSAGE_ACCEPTED",{idempotent:true},event.eventId));
    if(session.pendingMessageReversals?.[event.eventId]){await this.reverseUndeliveredMessage(session,event.eventId).catch(()=>{});return socket.send(serverEvent("MESSAGE_REJECTED",{code:"charge_reversal_pending"},event.eventId));}
    session.messageRate??={};const recent=(session.messageRate[participantId]||[]).filter(timestamp=>now-timestamp<10000);if(recent.length>=20){session.messageRate[participantId]=recent;return socket.send(serverEvent("RATE_LIMITED",{reason:"message_rate",retryAt:recent[0]+10000},event.eventId));}recent.push(now);session.messageRate[participantId]=recent;
    const peerAvailable=Boolean(session.virtualPeer)||this.state.getWebSockets().some(candidate=>candidate!==socket);if(!peerAvailable)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"peer_unavailable"},event.eventId));
    if(session.freeExpiredAt&&!session.paidActive)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"continuation_required"},event.eventId));
    if(!(session.contactUnlockedUntil&&now<session.contactUnlockedUntil)){session.contactState??={};const contact=checkContactMessage(event.payload.text,session.contactState[participantId]);session.contactState[participantId]=contact.state;if(contact.blocked){socket.send(serverEvent("MESSAGE_REJECTED",{code:"contact_blocked",message:"Contact details and links aren't allowed in this chat.",repeated:contact.repeated},event.eventId));if(contact.repeated)socket.send(serverEvent("RATE_LIMITED",{reason:"contact_bypass"}));return;}}
    const spam=await this.checkSpam(participantId,session.sessionId,event.payload.text);if(!spam.allowed){socket.send(serverEvent("RATE_LIMITED",{reason:"repeated_message",retryAt:spam.retryAt},event.eventId));return;}
    if(session.paidActive){const participant=session.participants[participantId];if(participant.virtual)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"virtual_sender_invalid"},event.eventId));if(!participant.accountUserId)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"account_required"},event.eventId));try{await new WalletService({url:this.env.SUPABASE_URL,serviceKey:this.env.SUPABASE_SERVICE_ROLE_KEY,fetcher:this.env.FETCHER||fetch}).apply({userId:participant.accountUserId,delta:-SESSION_DEFAULTS.paidMessageCredits,type:"paid_message",reason:"Delivered paid chat message",idempotencyKey:`message:${session.sessionId}:${event.eventId}:${participant.accountUserId}`,metadata:{sessionId:session.sessionId,eventId:event.eventId}});}catch(error){if(!error.message.includes("insufficient")){socket.send(serverEvent("MESSAGE_REJECTED",{code:"charge_unavailable"},event.eventId));return;}session.paymentHoldUntil=now+SESSION_DEFAULTS.continuationHoldSeconds*1000;socket.send(serverEvent("PAYMENT_HOLD",{reason:"insufficient_credits",holdSeconds:SESSION_DEFAULTS.continuationHoldSeconds},event.eventId));return this.sendToPeers(socket,"PAYMENT_HOLD",{reason:"peer_payment_pause",holdSeconds:SESSION_DEFAULTS.continuationHoldSeconds});}session.paymentHoldUntil=null;}
    if(session.virtualPeer){session.acceptedEventIds??={};session.acceptedEventIds[event.eventId]=now;socket.send(serverEvent("MESSAGE_ACCEPTED",{},event.eventId));session.virtualHumanHasSpoken=true;await this.recordAnalytics(`message:${session.sessionId}:${event.eventId}`,"message_sent","virtual");await this.qualifyTrial(session,"message");return this.replyAsVirtual(socket,event.payload.text,session);}
    const delivered=this.sendToPeers(socket,"MESSAGE_RECEIVED",{from:participantId,text:event.payload.text},event.eventId);if(delivered){if(session.paidActive)session.lastPaidMessageAt=now;session.acceptedEventIds??={};session.acceptedEventIds[event.eventId]=now;if(Object.keys(session.acceptedEventIds).length>200)delete session.acceptedEventIds[Object.keys(session.acceptedEventIds)[0]];socket.send(serverEvent("MESSAGE_ACCEPTED",{},event.eventId));await this.recordAnalytics(`message:${session.sessionId}:${event.eventId}`,session.paidActive?"paid_message_sent":"message_sent",session.paidActive?"paid":"real");if(!session.paidActive)await this.qualifyTrial(session,"message");}else{if(session.paidActive){const participant=session.participants[participantId];session.pendingMessageReversals??={};session.pendingMessageReversals[event.eventId]={userId:participant.accountUserId,participantId,amount:SESSION_DEFAULTS.paidMessageCredits,createdAt:now};await this.reverseUndeliveredMessage(session,event.eventId).catch(()=>{});}socket.send(serverEvent("MESSAGE_REJECTED",{code:session.pendingMessageReversals?.[event.eventId]?"charge_reversal_pending":"peer_unavailable"},event.eventId));}
  }
  async reverseUndeliveredMessage(session,eventId){const pending=session.pendingMessageReversals?.[eventId];if(!pending)return;await new WalletService({url:this.env.SUPABASE_URL,serviceKey:this.env.SUPABASE_SERVICE_ROLE_KEY,fetcher:this.env.FETCHER||fetch}).apply({userId:pending.userId,delta:pending.amount,type:"paid_message_reversal",reason:"Undelivered paid chat message",idempotencyKey:`message-reversal:${session.sessionId}:${eventId}:${pending.userId}`,metadata:{sessionId:session.sessionId,eventId}});delete session.pendingMessageReversals[eventId];if(!Object.keys(session.pendingMessageReversals).length)delete session.pendingMessageReversals;}
  async replyAsVirtual(socket,text,session){const provider=createVirtualParticipantProvider(this.env,session.virtualPeer.config,this.env.VIRTUAL_RANDOM||Math.random),reply=await provider.reply(text,session.virtualPeer.persona);if(!reply)return;const safety=checkContactMessage(reply,{}),safeReply=safety.blocked?"tell me more?":reply;await virtualDelay(session.virtualPeer.persona,this.env.VIRTUAL_RANDOM||Math.random,this.env.VIRTUAL_WAITER);socket.send(serverEvent("MESSAGE_RECEIVED",{from:session.virtualPeer.identityId,text:safeReply,virtual:true}));}
  async checkSpam(identityId,sessionId,text){if(!this.env?.ANONYMOUS||text.trim().length<20)return{allowed:true};const normalized=text.toLowerCase().replace(/\s+/g," ").replace(/[^a-z0-9 ]/g,"").trim(),digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(normalized)),fingerprint=[...new Uint8Array(digest)].slice(0,12).map(value=>value.toString(16).padStart(2,"0")).join(""),namespace=this.env.ANONYMOUS,stub=namespace.get(namespace.idFromName("global")),response=await stub.fetch("https://anonymous.internal/spam-fingerprint",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId,sessionId,fingerprint})});return response.json();}
  async handleContinue(socket,participantId,session,now,accepted){if(session.virtualPeer)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"virtual_continuation_unavailable"}));if(!session.freeExpiredAt||session.ended)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"continuation_not_available"}));if(!accepted){session.ended=true;return this.broadcast("CONTINUE_NOT_ACCEPTED",{by:participantId});}const participant=session.participants[participantId];if(!participant?.accountUserId)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"verified_account_required"}));session.continueAccepted??={};session.continueAccepted[participantId]=true;const participantIds=Object.keys(session.participants);if(participantIds.length===2&&participantIds.every(id=>session.continueAccepted[id])){session.paidActive=true;session.paymentHoldUntil=null;session.lastPaidMessageAt=now;this.broadcast("CONTINUE_ACTIVATED",{messageCredits:SESSION_DEFAULTS.paidMessageCredits});}else socket.send(serverEvent("CONTINUE_REQUESTED",{waitingForPeer:true}));}
  async handleContactUnlock(socket,participantId,session,now,action){if(session.ended)return;if(session.virtualPeer)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"virtual_contact_unlock_unavailable"}));if(action==="decline"){session.contactUnlockAccepted={};return this.broadcast("CONTACT_UNLOCK_ENDED",{reason:"declined",by:participantId});}const participant=session.participants[participantId];if(!participant?.accountUserId)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"verified_account_required"}));session.contactUnlockAccepted??={};session.contactUnlockAccepted[participantId]=true;if(action==="request")return this.sendToPeers(socket,"CONTACT_UNLOCK_REQUEST",{by:participantId,costEach:SESSION_DEFAULTS.contactUnlockCredits});const ids=Object.keys(session.participants);if(ids.length!==2||!ids.every(id=>session.contactUnlockAccepted[id]))return socket.send(serverEvent("CONTACT_UNLOCK_REQUEST",{waitingForPeer:true,costEach:SESSION_DEFAULTS.contactUnlockCredits}));try{await new ContactUnlockService({url:this.env.SUPABASE_URL,serviceKey:this.env.SUPABASE_SERVICE_ROLE_KEY,fetcher:this.env.FETCHER||fetch}).activate({sessionId:session.sessionId,leftUserId:session.participants[ids[0]].accountUserId,rightUserId:session.participants[ids[1]].accountUserId});}catch(error){session.contactUnlockAccepted={};return this.broadcast("CONTACT_UNLOCK_ENDED",{reason:error.message.includes("insufficient")?"insufficient_credits":"charge_failed"});}session.contactUnlockedUntil=now+SESSION_DEFAULTS.contactUnlockSeconds*1000;session.contactState={};await this.recordAnalytics(`contact-unlock:${session.sessionId}`,"contact_unlock_success","paid");this.broadcast("CONTACT_UNLOCKED",{seconds:SESSION_DEFAULTS.contactUnlockSeconds});}
  async handleSafetyAction(socket,participantId,session,action,reason){if(session.ended)return;const peerId=Object.keys(session.participants).find(id=>id!==participantId)||session.virtualPeer?.identityId;if(!peerId)return;const actor=session.participants[participantId]||{},target=session.participants[peerId]||{},actorRef=actor.accountPublicId||participantId,targetRef=target.accountPublicId||peerId,safety=new SafetyService({url:this.env.SUPABASE_URL,serviceKey:this.env.SUPABASE_SERVICE_ROLE_KEY,fetcher:this.env.FETCHER||fetch});try{if(action==="like"){session.likes??={};if(session.likes[participantId])return socket.send(serverEvent("MESSAGE_REJECTED",{code:"like_already_sent"}));await safety.like(session.sessionId,actorRef,targetRef);session.likes[participantId]=true;await this.recordAnalytics(`like:${session.sessionId}:${participantId}`,"like_sent",session.virtualPeer?"virtual":"real");socket.send(serverEvent("LIKE_ACCEPTED"));return this.sendToPeers(socket,"LIKE_RECEIVED",{message:"They liked this chat 👍"});}if(action==="report"){await safety.report(session.sessionId,actorRef,targetRef,reason);await this.avoidPair(participantId,peerId);await this.recordAnalytics(`report:${session.sessionId}:${participantId}`,"report_sent",session.virtualPeer?"virtual":"real");socket.send(serverEvent("REPORT_ACCEPTED",{message:"Thanks. Your report was received."}));session.ended=true;return this.sendToPeers(socket,"SESSION_ENDED",{reason:"peer_left"});}if(!actor.accountUserId)return socket.send(serverEvent("MESSAGE_REJECTED",{code:"registered_account_required"}));await safety.block(actor.accountUserId,targetRef);await this.avoidPair(participantId,peerId);await this.recordAnalytics(`block:${session.sessionId}:${participantId}`,"block_created",session.virtualPeer?"virtual":"real");socket.send(serverEvent("BLOCK_ACCEPTED"));session.ended=true;this.sendToPeers(socket,"SESSION_ENDED",{reason:"peer_left"});}catch(error){socket.send(serverEvent("MESSAGE_REJECTED",{code:`${action}_failed`}));}}
  async avoidPair(identityId,peerId){if(!this.env?.MATCHMAKING)return;const namespace=this.env.MATCHMAKING,stub=namespace.get(namespace.idFromName("global"));await stub.fetch("https://match.internal/avoid",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId,peerId})});}
  async handleNext(socket,participantId,session,now){
    await this.recordAnalytics(`next:${session.sessionId}:${participantId}`,"next_clicked",session.virtualPeer?"virtual":"real");
    const peerId=Object.keys(session.participants||{}).find(id=>id!==participantId);const reason=session.disconnects?.[peerId]?"peer_disconnected":session.participants?.[peerId]?.idle?"peer_idle":null;
    const decision=skipDecision({startedAt:session.startedAt||now,now,reason},SESSION_DEFAULTS);if(!decision.allowed)return socket.send(serverEvent("MATCH_COOLDOWN",decision));
    const abuse=await this.recordSkip(participantId);if(!abuse.allowed){await this.recordAnalytics(`skip-cooldown:${session.sessionId}:${participantId}`,"skip_cooldown_triggered","total");return socket.send(serverEvent("RATE_LIMITED",{retryAt:abuse.cooldownUntil,reason:"skip_abuse"}));}
    session.ended=true;this.broadcast("SESSION_ENDED",{reason:"next_requested",by:participantId});
  }
  async recordSkip(identityId){
    if(!this.env?.MATCHMAKING)return{allowed:true};const namespace=this.env.MATCHMAKING,stub=namespace.get(namespace.idFromName("global"));const response=await stub.fetch("https://match.internal/skip",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId})});return response.json();
  }
  async recordActivity(type){if(!this.env?.ANONYMOUS)return;const namespace=this.env.ANONYMOUS,stub=namespace.get(namespace.idFromName("global"));await stub.fetch("https://anonymous.internal/activity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type})});}
  async recordAnalytics(eventId,eventName,dimension="total",value=0){if(!this.env?.SUPABASE_URL||!this.env?.SUPABASE_SERVICE_ROLE_KEY||(this.env.FETCHER&&!this.env.ANALYTICS_FETCHER))return;try{await new AnalyticsService(this.env,this.env.ANALYTICS_FETCHER||fetch).record({eventId,eventName,dimension,value});}catch{}}
  async qualifyTrial(session,reason){session.trialConsumed??={};if(!this.env?.ANONYMOUS)return;const namespace=this.env.ANONYMOUS,stub=namespace.get(namespace.idFromName("global"));for(const identityId of Object.keys(session.participants||{})){if(session.trialConsumed[identityId])continue;const response=await stub.fetch("https://anonymous.internal/consume",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId,sessionId:session.sessionId,reason})});if(response.ok||response.status===409){session.trialConsumed[identityId]=true;await this.recordAnalytics(`trial:${session.sessionId}:${identityId}`,"free_connection_consumed","free");}}}
  async webSocketClose(socket,code,reason){
    const attachment=socket.deserializeAttachment(),now=Date.now();let session=(await this.state.storage.get(SESSION_KEY))||{participants:{},disconnects:{}};if(!isCurrentConnection(session,attachment))return;session.disconnects[attachment.participantId]=now;await this.saveSession(session);this.sendToPeers(socket,"PEER_DISCONNECTED",{participantId:attachment.participantId,code,reason:String(reason||"").slice(0,120)});this.sendToPeers(socket,"RECONNECT_GRACE",{seconds:SESSION_DEFAULTS.reconnectGraceSeconds});await this.scheduleNextAlarm(session,now);
  }
  webSocketError(socket){return this.webSocketClose(socket,1011,"socket_error")}
  async alarm(){
    const now=Date.now(),session=await this.state.storage.get(SESSION_KEY);if(!session)return;
    for(const eventId of Object.keys(session.pendingMessageReversals||{}))await this.reverseUndeliveredMessage(session,eventId).catch(()=>{});
    if(session.ended){await this.saveSession(session);await this.scheduleNextAlarm(session,now);return;}
    for(const [participantId,disconnectedAt] of Object.entries(session.disconnects||{}))if(reconnectDecision(disconnectedAt,now,SESSION_DEFAULTS).expired){session.ended=true;this.broadcast("SESSION_ENDED",{reason:"reconnect_timeout",participantId});}
    for(const [participantId,participant] of Object.entries(session.participants||{})){const idle=idleDecision(participant.lastActivityAt,now,SESSION_DEFAULTS);if(idle.state==="warning"&&!participant.warned){participant.warned=true;this.sendToParticipant(participantId,"TIMER_STATE",{idleWarning:true,message:"Still there? Tap to stay available.",graceRemainingSeconds:idle.graceRemainingSeconds});}if(idle.state==="idle"&&!participant.idle){participant.idle=true;this.sendToParticipant(participantId,"TIMER_STATE",{idle:true});this.sendToParticipant(participantId,"PEER_IDLE",{participantId},true);}}
    if(session.startedAt&&now-session.startedAt>=30_000)await this.qualifyTrial(session,"duration_30_seconds");
    if(session.startedAt&&timerState(session.startedAt,now,SESSION_DEFAULTS).remainingSeconds===0&&!session.freeExpiredAt&&!session.ended){session.freeExpiredAt=now;this.broadcast("TIMER_STATE",timerState(session.startedAt,now,SESSION_DEFAULTS));if(session.virtualPeer){session.ended=true;this.broadcast("SESSION_ENDED",{reason:"virtual_free_time_complete"});}else{session.continuationHoldUntil=now+SESSION_DEFAULTS.continuationHoldSeconds*1000;this.broadcast("CONTINUE_REQUESTED",{holdSeconds:SESSION_DEFAULTS.continuationHoldSeconds,messageCredits:SESSION_DEFAULTS.paidMessageCredits});}}
    if(!session.paidActive&&session.continuationHoldUntil&&now>=session.continuationHoldUntil){session.ended=true;this.broadcast("SESSION_ENDED",{reason:"continuation_timeout"});}
    if(session.paidActive&&session.paymentHoldUntil&&now>=session.paymentHoldUntil){session.ended=true;this.broadcast("SESSION_ENDED",{reason:"payment_hold_timeout"});}
    if(session.contactUnlockedUntil&&now>=session.contactUnlockedUntil){session.contactUnlockedUntil=null;session.contactUnlockAccepted={};this.broadcast("CONTACT_UNLOCK_ENDED",{reason:"expired"});}
    if(session.paidActive&&session.lastPaidMessageAt&&now-session.lastPaidMessageAt>=SESSION_DEFAULTS.paidIdleSeconds*1000){session.ended=true;this.broadcast("SESSION_ENDED",{reason:"paid_idle_timeout"});}
    await this.saveSession(session);await this.scheduleNextAlarm(session,now);
  }
  sendToParticipant(participantId,type,payload,toPeers=false){for(const socket of this.state.getWebSockets()){const same=socket.deserializeAttachment()?.participantId===participantId;if((!toPeers&&same)||(toPeers&&!same))socket.send(serverEvent(type,payload));}}
  sendToPeers(source,type,payload,eventId){let delivered=0;for(const socket of this.state.getWebSockets())if(socket!==source)try{socket.send(serverEvent(type,payload,eventId));delivered++;}catch{}return delivered}
  broadcast(type,payload){for(const socket of this.state.getWebSockets())socket.send(serverEvent(type,payload))}
  async saveSession(session){let releaseIdentity;if(session.ended){delete session.contactState;delete session.messageRate;if(!session.matchReleased&&session.sessionId){releaseIdentity=Object.keys(session.participants||{})[0];session.matchReleased=Boolean(releaseIdentity);}}await this.state.storage.put(SESSION_KEY,session);if(releaseIdentity&&this.env?.MATCHMAKING){const namespace=this.env.MATCHMAKING,stub=namespace.get(namespace.idFromName("global"));await stub.fetch("https://match.internal/end",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identityId:releaseIdentity,sessionId:session.sessionId})}).catch(()=>{});}}
  async scheduleNextAlarm(session,now){const pendingReversals=Object.keys(session.pendingMessageReversals||{}).length;if(session.ended&&!pendingReversals)return;const deadlines=[];if(pendingReversals)deadlines.push(now+1000);if(!session.ended&&session.startedAt&&!session.freeExpiredAt){deadlines.push(session.startedAt+SESSION_DEFAULTS.freeSeconds*1000);if(Object.keys(session.trialConsumed||{}).length<Object.keys(session.participants||{}).length)deadlines.push(session.startedAt+30_000);}if(!session.ended&&session.continuationHoldUntil&&!session.paidActive)deadlines.push(session.continuationHoldUntil);if(!session.ended&&session.paidActive&&session.lastPaidMessageAt)deadlines.push(session.lastPaidMessageAt+SESSION_DEFAULTS.paidIdleSeconds*1000);if(!session.ended&&session.paymentHoldUntil)deadlines.push(session.paymentHoldUntil);if(!session.ended&&session.contactUnlockedUntil)deadlines.push(session.contactUnlockedUntil);if(!session.ended)for(const participant of Object.values(session.participants||{}))if(!participant.idle)deadlines.push(participant.lastActivityAt+(participant.warned?SESSION_DEFAULTS.idleWarningSeconds+SESSION_DEFAULTS.idleGraceSeconds:SESSION_DEFAULTS.idleWarningSeconds)*1000);if(!session.ended)for(const value of Object.values(session.disconnects||{}))deadlines.push(value+SESSION_DEFAULTS.reconnectGraceSeconds*1000);const next=Math.min(...deadlines.map(value=>Math.max(value,now+1)));if(Number.isFinite(next))await this.state.storage.setAlarm(next);}
}
