const base=import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8787/api/v1";
async function call(session,path,options={}){const response=await fetch(`${base}/admin${path}`,{...options,headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`,...options.headers}}),data=await response.json();if(!response.ok)throw new Error(data.error||"Admin request failed");return data;}
async function rawCall(session,path,options={}){const response=await fetch(`${base}${path}`,{...options,headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`,...options.headers}}),data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data;}
async function uploadRadioTrack(session,{roomPublicId,title,artistName,durationSeconds,audioFile,artworkFile}){const form=new FormData();form.append("roomPublicId",roomPublicId);form.append("title",title);form.append("artistName",artistName||"");form.append("durationSeconds",String(durationSeconds));form.append("audio",audioFile);if(artworkFile)form.append("artwork",artworkFile);const response=await fetch(`${base}/admin/radio/tracks`,{method:"POST",headers:{authorization:`Bearer ${session.access_token}`},body:form}),data=await response.json();if(!response.ok)throw new Error(data.error||"Upload failed");return data;}
export const adminApi={
  dashboard:session=>call(session,"/dashboard"),users:session=>call(session,"/users"),reports:session=>call(session,"/reports"),grievances:session=>call(session,"/grievances"),feedback:session=>call(session,"/feedback"),deletions:session=>call(session,"/deletions"),restrictions:session=>call(session,"/restrictions"),offers:session=>call(session,"/offers"),coupons:session=>call(session,"/coupons"),audit:session=>call(session,"/audit"),ads:session=>call(session,"/ads"),virtual:session=>call(session,"/virtual"),flags:session=>call(session,"/flags"),video:session=>call(session,"/video"),ledger:(session,userId)=>call(session,`/users/${encodeURIComponent(userId)}/ledger`),gamesRevenue:session=>call(session,"/games/revenue"),gamesRounds:session=>call(session,"/games/rounds"),jackpotRounds:session=>call(session,"/games/jackpot-rounds"),triviaRounds:session=>call(session,"/games/trivia-rounds"),wheelSegments:session=>call(session,"/games/wheel-segments"),updateWheelSegments:(session,segments)=>call(session,"/games/wheel-segments",{method:"PUT",body:JSON.stringify({segments})}),triviaSchedule:session=>call(session,"/games/trivia-schedule"),scheduleTrivia:(session,triviaDate,questions)=>call(session,"/games/trivia-schedule",{method:"POST",body:JSON.stringify({triviaDate,questions})}),
  radioChannels:session=>rawCall(session,"/radio/channels"),radioQueue:(session,roomPublicId)=>rawCall(session,`/party-rooms/${encodeURIComponent(roomPublicId)}/radio/tracks`),uploadRadioTrack:(session,payload)=>uploadRadioTrack(session,payload),setRadioArtistLinks:(session,payload)=>call(session,"/radio/artist-links",{method:"PUT",body:JSON.stringify(payload)}),
  updateGrievance:(session,id,status)=>call(session,`/grievances/${encodeURIComponent(id)}`,{method:"POST",body:JSON.stringify({status})}),updateFeedback:(session,id,status)=>call(session,`/feedback/${encodeURIComponent(id)}`,{method:"POST",body:JSON.stringify({status})}),updateDeletion:(session,id,status,note)=>call(session,`/deletions/${encodeURIComponent(id)}`,{method:"POST",body:JSON.stringify({status,note})}),updateAds:(session,expectedVersion,config)=>call(session,"/ads",{method:"PUT",body:JSON.stringify({expectedVersion,config})}),updateVirtual:(session,expectedVersion,config)=>call(session,"/virtual",{method:"PUT",body:JSON.stringify({expectedVersion,config})}),updateFlags:(session,expectedVersion,config)=>call(session,"/flags",{method:"PUT",body:JSON.stringify({expectedVersion,config})}),updateVideo:(session,expectedVersion,config)=>call(session,"/video",{method:"PUT",body:JSON.stringify({expectedVersion,config})}),adjustWallet:(session,payload)=>call(session,"/wallet",{method:"POST",body:JSON.stringify(payload)}),restrict:(session,payload)=>call(session,"/restrictions",{method:"POST",body:JSON.stringify(payload)}),savePromotion:(session,type,payload)=>call(session,"/promotions",{method:"POST",body:JSON.stringify({type,payload})})
};
