import { authConfigured,currentSession } from "./auth.js";
import { adminApi } from "./admin-api.js";
const app=document.querySelector("#app");let session,current,message="";

function shell(){app.innerHTML=`<main class="admin-shell"><header class="admin-top"><a class="brand" href="/"><span class="brand-mark">R</span> Random Chat Admin</a></header><p class="eyebrow">Advertisement controls</p><h1 style="font-size:clamp(2.5rem,7vw,4.5rem)">Keep monetisation adjustable.</h1><p id="admin-status" class="storage-warning" hidden></p><section class="panel" style="width:100%"><form id="ad-config-form"><div class="form-grid"><label class="field"><span>Provider key</span><input name="provider" pattern="[a-z0-9_-]{2,32}" required></label><label class="field"><span>Ad-free above Credits</span><input name="threshold" type="number" min="1" max="1000000" required></label><label class="field"><span>Interstitial every scans</span><input name="frequency" type="number" min="1" max="100" required></label><label class="field"><span><input name="enabled" type="checkbox"> Ads enabled</span></label></div><fieldset class="field"><legend>Placements</legend><div class="chips"><label><input name="top" type="checkbox"> Top banner</label><label><input name="bottom" type="checkbox"> Bottom banner</label><label><input name="desktopSide" type="checkbox"> Desktop side</label><label><input name="interstitial" type="checkbox"> Interstitial</label></div></fieldset><p class="muted">Changes use optimistic versioning and create an admin audit record. Provider secrets remain in platform secret storage.</p><button class="btn btn-primary">Save ad configuration</button></form></section></main>`;}
function status(text,isError=false){const node=document.querySelector("#admin-status");node.hidden=!text;node.textContent=text;node.style.borderColor=isError?"var(--brand)":"var(--line)";}
function fill(){if(!current)return;const form=document.querySelector("#ad-config-form"),config=current.config;form.elements.provider.value=config.provider;form.elements.threshold.value=config.adFreeBalanceThreshold;form.elements.frequency.value=config.interstitialEveryScans;form.elements.enabled.checked=config.enabled;for(const key of ["top","bottom","desktopSide","interstitial"])form.elements[key].checked=config.placements[key];status(message||`Loaded configuration version ${current.version}.`);}
async function load(){shell();if(!authConfigured)return status("Supabase is not configured. Configure it, then sign in with the super-admin account.",true);session=await currentSession();if(!session)return status("Sign in from the Account page with the configured super-admin account, then return here.",true);try{current=await adminApi.ads(session);fill();}catch(error){status(error.message,true);}}
document.addEventListener("submit",async event=>{if(event.target.id!=="ad-config-form")return;event.preventDefault();if(!current)return;const form=event.target,config={enabled:form.elements.enabled.checked,provider:form.elements.provider.value,adFreeBalanceThreshold:Number(form.elements.threshold.value),interstitialEveryScans:Number(form.elements.frequency.value),placements:Object.fromEntries(["top","bottom","desktopSide","interstitial"].map(key=>[key,form.elements[key].checked]))};status("Saving…");try{current=await adminApi.updateAds(session,current.version,config);message="Ad configuration saved and audited.";fill();}catch(error){status(error.message,true);}});
load().catch(error=>status(error.message,true));
