import { adDecision } from "../../worker/src/policies/adPolicy.js";
const base=import.meta.env?.VITE_API_BASE_URL||"http://127.0.0.1:8787/api/v1";

class HouseAdProvider{
  mount(slot){const card=document.createElement("div");card.className="ad-card";card.setAttribute("aria-label","Advertisement");const label=document.createElement("span");label.textContent="Advertisement";const message=document.createElement("strong");message.textContent="Your ad could be here";card.append(label,message);slot.replaceChildren(card);}
}
class DisabledAdProvider{mount(slot){slot.remove();return false;}}
const providers={house:()=>new HouseAdProvider(),disabled:()=>new DisabledAdProvider()};
export function registerAdProvider(name,factory){const normalized=String(name||"").trim().toLowerCase();if(!/^[a-z0-9_-]{2,32}$/.test(normalized)||["house","disabled"].includes(normalized)||typeof factory!=="function")throw new Error("invalid_ad_provider_registration");const provider=factory();if(!provider||typeof provider.mount!=="function")throw new Error("invalid_ad_provider_registration");providers[normalized]=factory;return()=>{delete providers[normalized]};}
export function adProviderFor(name){try{const provider=(providers[name]||providers.disabled)();return provider&&typeof provider.mount==="function"?provider:providers.disabled();}catch{return providers.disabled();}}
function safeMount(provider,slot){try{return provider.mount(slot)!==false}catch{slot.remove();return false}}
export async function loadPublicAdSnapshot(fetcher=fetch){const response=await fetcher(`${base}/config/public`),data=await response.json();if(!response.ok)throw new Error(data.error||"public_config_failed");if(!Number.isSafeInteger(data.version)||!data.ads)throw new Error("invalid_public_config");return{config:data.ads,version:data.version,flags:data.flags||{},membership:data.membership||null,adEarning:data.adEarning||null};}
export async function loadPublicAdConfig(fetcher=fetch){return(await loadPublicAdSnapshot(fetcher)).config;}

const PRIVATE_AD_CACHE_MS=5*60*1000;
const privateAdCache=new Map();
async function fetchPrivateAd(slot,fetcher=fetch){const cached=privateAdCache.get(slot);if(cached&&Date.now()-cached.at<PRIVATE_AD_CACHE_MS)return cached.ad;try{const response=await fetcher(`${base}/ads/private?slot=${encodeURIComponent(slot)}`),data=await response.json();const ad=response.ok?data.ad||null:null;privateAdCache.set(slot,{ad,at:Date.now()});return ad;}catch{privateAdCache.set(slot,{ad:null,at:Date.now()});return null;}}
function recordAdEvent(adId,type,fetcher=fetch){try{fetcher(`${base}/ads/private/event`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({adId,type}),keepalive:true}).catch(()=>{});}catch{}}
function mountPrivateAd(slotEl,ad){const link=document.createElement("a");link.className="ad-card ad-card-private";link.href=ad.targetUrl;link.target="_blank";link.rel="noopener noreferrer sponsored";link.setAttribute("aria-label",ad.title||"Advertisement");const img=document.createElement("img");img.src=ad.imageUrl;img.alt=ad.title||"";img.loading="lazy";link.append(img);if(ad.title){const caption=document.createElement("span");caption.className="ad-card-title";caption.textContent=ad.title;link.append(caption);}link.addEventListener("click",()=>recordAdEvent(ad.id,"click"));slotEl.replaceChildren(link);recordAdEvent(ad.id,"load");}
export async function mountRewardAdSlot(container){const ad=await fetchPrivateAd("reward");if(!ad){container.replaceChildren();return false;}mountPrivateAd(container,ad);return true;}
export function mountAds(root,{config,registered=false,balance=0,scanCount=0}={}){root.querySelectorAll("[data-ad-slot]").forEach(slot=>slot.remove());const decision=adDecision({registered,balance,scanCount,config});if(!decision.placements.length)return decision;const main=root.querySelector("main");if(!main)return decision;const provider=adProviderFor(decision.provider);for(const placement of decision.placements){if(placement==="interstitial"){const key=`random-chat.ad-scan.${scanCount}`;if(sessionStorage.getItem(key))continue;sessionStorage.setItem(key,"shown");const overlay=document.createElement("aside"),content=document.createElement("div");overlay.className="ad-interstitial";overlay.dataset.adSlot=placement;const close=document.createElement("button");close.className="btn btn-ghost";close.textContent="Continue";close.addEventListener("click",()=>overlay.remove());if(!safeMount(provider,content))continue;overlay.append(content,close);document.body.append(overlay);fetchPrivateAd(placement).then(ad=>{if(ad)mountPrivateAd(content,ad);});continue;}const slot=document.createElement("aside");slot.className=`ad-slot ad-slot-${placement}`;slot.dataset.adSlot=placement;if(!safeMount(provider,slot))continue;if(placement==="top")main.prepend(slot);else main.append(slot);fetchPrivateAd(placement).then(ad=>{if(ad&&slot.isConnected)mountPrivateAd(slot,ad);});}return decision;}
