import { views } from "./views.js";
import { getAnonymousIdentity } from "./anonymous-identity.js";
import { loadPreferences, savePreferences } from "./preferences.js";
import { localHistory } from "./local-history.js";
import { checkStoragePersistence } from "./storage-health.js";
import { ChatTabLease } from "./tabs.js";
import { checkContactMessage } from "./contact-guard.js";
import { loadPublicAdConfig,mountAds } from "./ads.js";

const app=document.querySelector("#app");
const state={identity:getAnonymousIdentity(),preferences:loadPreferences(),conversations:[],favourites:[],storageLimited:false,accountSession:null,accountProfile:null,wallet:null,walletLedger:[],accountMessage:"",passwordRecovery:false,adConfig:null,scanCount:Number(sessionStorage.getItem("random-chat.scan-count")||0)};
let timerId,tabLease;
let authModule,accountApiModule,accountInitialized=false;
let messages=[{sender:"peer",text:"Hey! What made you smile today?",at:new Date().toISOString()}];
let clientContactState={};
const routeName=()=>{const name=location.hash.replace(/^#\/?/,"");return views[name]?name:"home"};
const navigate=name=>{location.hash=`#/${name}`};
const selectedChips=name=>[...document.querySelectorAll(`[data-chip-group="${name}"] [aria-pressed="true"]`)].map(chip=>chip.textContent);
function appendMessage(sender,text){const bubble=document.createElement("div");bubble.className=`bubble${sender==="me"?" mine":""}`;bubble.textContent=text;document.querySelector("#chat-log")?.append(bubble);messages.push({sender,text,at:new Date().toISOString()});}
async function saveCurrentConversation(){if(messages.length<2)return;await localHistory.saveConversation({id:crypto.randomUUID(),peerId:"demo-peer-quiet-river",peerName:"QuietRiver482",endedAt:new Date().toISOString(),messages:[...messages]});state.conversations=await localHistory.listConversations();}
async function loadAuth(){return authModule??=await import("./auth.js")}
async function loadAccountApi(){return(accountApiModule??=await import("./account-api.js")).accountApi}
async function loadRazorpay(){if(window.Razorpay)return window.Razorpay;await new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.onload=resolve;script.onerror=()=>reject(new Error("Could not load secure checkout"));document.head.append(script);});return window.Razorpay;}
async function refreshAccount(session,message=""){state.accountSession=session;state.accountMessage=message;state.accountProfile=null;state.wallet=null;state.walletLedger=[];if(session){try{const accountApi=await loadAccountApi();const [profile,wallet,ledger]=await Promise.all([accountApi.profile(session),accountApi.wallet(session),accountApi.ledger(session)]);state.accountProfile=profile;state.wallet=wallet.wallet;state.walletLedger=ledger.entries;let deviceId=localStorage.getItem("random-chat.account-device.v1");if(!deviceId){deviceId=crypto.randomUUID();localStorage.setItem("random-chat.account-device.v1",deviceId);}await accountApi.claimDevice(session,deviceId);}catch(error){state.accountMessage=error.message;}}if(routeName()==="account")render();}
async function ensureAccountAuth(){if(accountInitialized)return;accountInitialized=true;const auth=await loadAuth();auth.onAuthChange((session,event)=>{if(event==="PASSWORD_RECOVERY")state.passwordRecovery=true;refreshAccount(session);});await refreshAccount(await auth.currentSession());}
async function accountAction(action,success){try{state.accountMessage="Working…";render();await action();state.accountMessage=success;}catch(error){state.accountMessage=error.message;}render();}
function bind(){
  if(state.passwordRecovery&&routeName()==="account"&&!document.querySelector("#update-password-form")){const panel=document.querySelector(".panel");panel?.insertAdjacentHTML("afterbegin",`<form id="update-password-form" class="auth-card"><h3>Choose a new password</h3><div class="field"><label>New password</label><input name="password" type="password" minlength="8" required autocomplete="new-password"></div><button class="btn btn-primary">Update password</button></form>`);}
  if(state.accountSession&&state.wallet&&routeName()==="account"){const summary=document.createElement("section");summary.className="wallet-summary";const title=document.createElement("strong");title.textContent=`${state.wallet.balance.toLocaleString("en-IN")} Credits`;const caption=document.createElement("span");caption.textContent="Current server balance";summary.append(title,caption);const list=document.createElement("div");list.className="wallet-ledger";for(const entry of state.walletLedger.slice(0,8)){const row=document.createElement("div");const reason=document.createElement("span");reason.textContent=entry.reason;const amount=document.createElement("strong");amount.textContent=`${entry.delta>0?"+":""}${entry.delta.toLocaleString("en-IN")}`;row.append(reason,amount);list.append(row);}summary.append(list);document.querySelector(".panel h2")?.after(summary);}
  document.querySelectorAll("[data-route]").forEach(el=>el.addEventListener("click",()=>navigate(el.dataset.route)));
  document.querySelectorAll("[data-chip-group]").forEach(group=>group.addEventListener("click",event=>{const chip=event.target.closest(".chip");if(!chip)return;const limit=group.dataset.chipGroup==="languages"?3:5;if(chip.ariaPressed==="false"&&group.querySelectorAll('[aria-pressed="true"]').length>=limit)return;chip.ariaPressed=chip.ariaPressed==="false"?"true":"false";}));
  document.querySelector("#onboarding-form")?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);state.preferences=savePreferences({age:form.get("age"),gender:form.get("gender"),name:form.get("name"),languages:selectedChips("languages"),interests:selectedChips("interests")});state.scanCount+=1;sessionStorage.setItem("random-chat.scan-count",String(state.scanCount));navigate("searching");});
  document.querySelector("#demo-match")?.addEventListener("click",()=>{clientContactState={};navigate("chat");});
  document.querySelector("#chat-form")?.addEventListener("submit",event=>{event.preventDefault();const input=document.querySelector("#chat-input");const value=input.value.trim();if(!value)return;const contact=checkContactMessage(value,clientContactState);clientContactState=contact.state;if(contact.blocked){input.setCustomValidity("Contact details and links aren't allowed in this chat.");input.reportValidity();return;}input.setCustomValidity("");appendMessage("me",value);input.value="";});
  document.querySelector("#chat-input")?.addEventListener("input",event=>event.currentTarget.setCustomValidity(""));
  document.querySelector("#favourite-peer")?.addEventListener("click",async event=>{await localHistory.saveFavourite({peerId:"demo-peer-quiet-river",displayName:"QuietRiver482",savedAt:new Date().toISOString()});state.favourites=await localHistory.listFavourites();event.currentTarget.textContent="♥";});
  document.querySelector("#end-chat")?.addEventListener("click",async()=>{await saveCurrentConversation();navigate("history");});
  document.querySelector("#clear-history")?.addEventListener("click",async()=>{await localHistory.clearAllConversations();state.conversations=[];render();});
  document.querySelectorAll("[data-delete-conversation]").forEach(button=>button.addEventListener("click",async()=>{await localHistory.clearConversation(button.dataset.deleteConversation);state.conversations=await localHistory.listConversations();render();}));
  document.querySelector("#clear-favourites")?.addEventListener("click",async()=>{await localHistory.clearFavourites();state.favourites=[];render();});
  document.querySelector("#signup-form")?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);accountAction(async()=>(await loadAuth()).signUp(form.get("email"),form.get("password")),"Check your inbox to verify your email, then sign in.");});
  document.querySelector("#signin-form")?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);accountAction(async()=>(await loadAuth()).signIn(form.get("email"),form.get("password")),"Signed in.");});
  document.querySelector("#reset-password")?.addEventListener("click",()=>{const email=document.querySelector("#signin-form [name=email]")?.value;if(!email){state.accountMessage="Enter your email in the sign-in form first.";return render();}accountAction(async()=>(await loadAuth()).sendPasswordReset(email),"Password reset email sent.");});
  document.querySelector("#signout")?.addEventListener("click",()=>accountAction(async()=>(await loadAuth()).signOut(),"Signed out."));
  document.querySelector("#username-form")?.addEventListener("submit",event=>{event.preventDefault();const username=new FormData(event.currentTarget).get("username");accountAction(async()=>{state.accountProfile=await(await loadAccountApi()).claimUsername(state.accountSession,username);},"Username saved.");});
  const rechargeForm=document.querySelector("#recharge-form");if(rechargeForm&&!rechargeForm.elements.coupon){const coupon=document.createElement("input");coupon.name="coupon";coupon.maxLength=32;coupon.autocomplete="off";coupon.placeholder="Promo code (optional)";rechargeForm.querySelector("small")?.before(coupon);}
  document.querySelector("#recharge-form")?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget),amountRupees=Number(form.get("amount")),couponCode=String(form.get("coupon")||"").trim()||null;accountAction(async()=>{const api=await loadAccountApi(),order=await api.createPaymentOrder(state.accountSession,amountRupees*100,couponCode),Razorpay=await loadRazorpay();await new Promise((resolve,reject)=>{const checkout=new Razorpay({key:order.keyId,amount:order.amountPaise,currency:order.currency,order_id:order.orderId,name:"Random Chat India",description:`${order.credits.toLocaleString("en-IN")} Credits${order.offer?` · ${order.offer}`:""}`,prefill:{email:state.accountSession.user.email},handler:async result=>{try{await api.verifyPayment(state.accountSession,result);await refreshAccount(state.accountSession,"Recharge verified and credited.");resolve();}catch(error){reject(error);}},modal:{ondismiss:()=>reject(new Error("Payment cancelled"))},theme:{color:"#6c4cff"}});checkout.open();});},"Opening secure checkout…");});
  document.querySelector("#update-password-form")?.addEventListener("submit",event=>{event.preventDefault();const password=new FormData(event.currentTarget).get("password");accountAction(async()=>{await(await loadAuth()).updatePassword(password);state.passwordRecovery=false;},"Password updated.");});
}
function activateChat(){if(routeName()!=="chat")return;messages=[{sender:"peer",text:"Hey! What made you smile today?",at:new Date().toISOString()}];tabLease?.close();tabLease=new ChatTabLease();tabLease.onMoved=()=>{const notice=document.querySelector("#tab-moved");if(notice)notice.hidden=false;document.querySelectorAll("#chat-form input,#chat-form button").forEach(control=>control.disabled=true);clearInterval(timerId);};tabLease.claim();let seconds=120;timerId=setInterval(()=>{const timer=document.querySelector("#chat-timer");if(!timer||--seconds<0)return clearInterval(timerId);timer.textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;},1000);}
function render(){clearInterval(timerId);if(routeName()!=="chat"){tabLease?.close();tabLease=null;}app.innerHTML=views[routeName()](state);bind();activateChat();if(state.adConfig)mountAds(document,{config:state.adConfig,registered:Boolean(state.accountSession),balance:state.wallet?.balance||0,scanCount:state.scanCount});if(routeName()==="account")ensureAccountAuth().catch(error=>{state.accountMessage=error.message;});window.scrollTo(0,0);}
async function hydrate(){const [health,conversations,favourites,ads]=await Promise.all([checkStoragePersistence(),localHistory.listConversations(),localHistory.listFavourites(),loadPublicAdConfig().catch(()=>null)]);state.storageLimited=health.limited;state.conversations=conversations;state.favourites=favourites;state.adConfig=ads;render();}
window.addEventListener("hashchange",render);window.addEventListener("beforeunload",()=>tabLease?.close());render();hydrate().catch(()=>{state.storageLimited=true;render();});
