import { views } from "./views.js";
import { getAnonymousIdentity } from "./anonymous-identity.js";
import { loadPreferences, savePreferences } from "./preferences.js";
import { localHistory } from "./local-history.js";
import { checkStoragePersistence } from "./storage-health.js";
import { ChatTabLease } from "./tabs.js";
import { checkContactMessage } from "./contact-guard.js";
import { loadPublicAdConfig,mountAds } from "./ads.js";
import { publicStats,recordClientEvent } from "./analytics.js";
import { cancelFavouriteReconnect,cancelMatch,endMatch,heartbeatPresence,issueAnonymousSession,pollMatchResult,pollReconnect,requestFavouriteReconnect,respondReconnect,startMatchSearch } from "./match-api.js";
import { RealtimeChatClient } from "./realtime-client.js";
import { LANGUAGES,APP_CONFIG } from "./config.js";
import { preferenceFee } from "../../worker/src/policies/preferencePolicy.js";

const app=document.querySelector("#app");
const state={identity:getAnonymousIdentity(),preferences:loadPreferences(),matchPreferences:{},conversations:[],favourites:[],storageLimited:false,accountSession:null,accountProfile:null,wallet:null,walletLedger:[],accountMessage:"",passwordRecovery:false,adConfig:null,publicStats:null,scanCount:Number(sessionStorage.getItem("random-chat.scan-count")||0),anonymousSession:null,match:null,searchError:"",searchMode:"random"};
let tabLease,searchPollId,presenceTimer,reconnectPollTimer,realtime,finishingChat=false,nextRequested=false,handlingReconnect=false;
let authModule,accountApiModule,accountInitialization;
let messages=[];
const pendingMessages=new Map();
let clientContactState={};
const routeName=()=>{const name=location.hash.replace(/^#\/?/,"");return views[name]?name:"home"};
const navigate=name=>{location.hash=`#/${name}`};
const selectedChips=name=>[...document.querySelectorAll(`[data-chip-group="${name}"] [aria-pressed="true"]`)].map(chip=>chip.textContent);
function bubble(sender,text){const node=document.createElement("div");node.className=`bubble${sender==="me"?" mine":""}`;node.textContent=text;return node;}
function appendMessage(sender,text){document.querySelector("#chat-log")?.append(bubble(sender,text));messages.push({sender,text,at:new Date().toISOString()});}
function restoreMessages(){const log=document.querySelector("#chat-log");if(!log||!messages.length)return;log.replaceChildren(...messages.map(message=>bubble(message.sender,message.text)));}
function chatNotice(message,actions=[]){const notice=document.querySelector("#chat-notice");if(!notice)return;notice.hidden=!message;notice.replaceChildren();if(!message)return;const text=document.createElement("span");text.textContent=message;notice.append(text);for(const [label,type] of actions){const button=document.createElement("button");button.type="button";button.className="btn btn-ghost";button.dataset.socketAction=type;button.textContent=label;notice.append(button);}}
async function saveCurrentConversation(){if(messages.length<2)return;const virtual=state.match?.virtual===true,profile=state.match?.virtualProfile||{};await localHistory.saveConversation({id:crypto.randomUUID(),peerId:state.match?.peerId||"unknown-peer",peerName:virtual?(profile.handle||"Virtual participant"):"New person",endedAt:new Date().toISOString(),messages:[...messages]});state.conversations=await localHistory.listConversations();}
async function ensureAnonymousSession(){return state.anonymousSession??=await issueAnonymousSession(state.identity);}
async function openMatch(match){clearTimeout(searchPollId);state.match=match;state.searchError="";state.searchMode="random";messages=[];pendingMessages.clear();finishingChat=false;nextRequested=false;navigate("chat");}
async function pollSearch(){if(routeName()!=="searching"||!state.anonymousSession)return;try{const result=await pollMatchResult(state.anonymousSession.token);if(result.status==="matched")return openMatch(result);if(result.status==="idle"&&state.searchMode!=="reconnect")throw new Error("Search ended before a match was found.");searchPollId=setTimeout(pollSearch,1000);}catch(error){state.searchError=error.message;render();}}
async function beginSearch(){clearTimeout(searchPollId);state.searchError="";state.searchMode="random";render();try{await ensureAccountAuth().catch(()=>{});await ensureAnonymousSession();const result=await startMatchSearch({anonymousToken:state.anonymousSession.token,accountSession:state.accountSession,profile:{age:state.preferences.age,gender:state.preferences.gender,languages:state.preferences.languages,interests:state.preferences.interests},preferences:state.matchPreferences});if(result.status==="matched")return openMatch(result);searchPollId=setTimeout(pollSearch,700);}catch(error){const labels={account_required:"Your free anonymous connections are used. Sign in with a verified account to continue.",verified_account_required_for_preferences:"Sign in with a verified account to use paid matching preferences.",insufficient_credits:"You need more Credits for this match option."};state.searchError=labels[error.message]||error.message;render();}}
async function cancelCurrentSearch(){clearTimeout(searchPollId);if(state.anonymousSession){const cancel=state.searchMode==="reconnect"?cancelFavouriteReconnect:cancelMatch;await cancel(state.anonymousSession.token).catch(()=>{});}state.searchError="";state.searchMode="random";navigate("home");}
async function startFavouriteReconnect(peerId){await ensureAccountAuth();if(!state.accountSession?.user?.email_confirmed_at){state.accountMessage="Sign in and verify your email before reconnecting.";return navigate("account");}await ensureAnonymousSession();const result=await requestFavouriteReconnect({anonymousToken:state.anonymousSession.token,accountSession:state.accountSession,targetPeerId:peerId});if(result.status==="offline")throw new Error("That favourite is not online right now.");state.searchMode="reconnect";state.searchError="Waiting for your favourite to accept…";navigate("searching");searchPollId=setTimeout(pollSearch,700);}
async function maintainPresence(){try{await ensureAnonymousSession();const route=routeName(),status=route==="chat"?"chatting":route==="searching"?"waiting":"online";await heartbeatPresence(state.anonymousSession.token,status,{accountSession:state.accountSession});}catch{}presenceTimer=setTimeout(maintainPresence,20000);}
async function checkIncomingReconnect(){if(!handlingReconnect){try{await ensureAnonymousSession();const {request}=await pollReconnect({anonymousToken:state.anonymousSession.token});if(request){handlingReconnect=true;const accepted=confirm("A saved favourite wants to reconnect for a new two-minute chat. Accept?");const result=await respondReconnect({anonymousToken:state.anonymousSession.token,requestId:request.requestId,accepted});if(accepted&&result.status==="accepted")await openMatch({status:"matched",sessionId:result.sessionId,peerId:request.initiatorId,reconnect:true});handlingReconnect=false;}}catch{handlingReconnect=false;}}reconnectPollTimer=setTimeout(checkIncomingReconnect,5000);}
async function finishChat(reason="ended",destination="history",notifyServer=true){if(finishingChat)return;finishingChat=true;if(notifyServer)realtime?.send("SESSION_END");realtime?.stop();realtime=null;await saveCurrentConversation();if(state.anonymousSession&&state.match?.sessionId)await endMatch(state.anonymousSession.token,state.match.sessionId).catch(()=>{});state.match=null;pendingMessages.clear();finishingChat=false;navigate(destination);if(destination==="searching")beginSearch();}
function handleRealtimeEvent(event){const payload=event.payload||{};if(event.type==="MESSAGE_RECEIVED")appendMessage("peer",String(payload.text||""));if(event.type==="MESSAGE_ACCEPTED"){const text=pendingMessages.get(event.eventId);if(text){appendMessage("me",text);pendingMessages.delete(event.eventId);}}if(event.type==="MESSAGE_REJECTED"||event.type==="RATE_LIMITED"){pendingMessages.delete(event.eventId);chatNotice(payload.message||payload.code||payload.reason||"Message was not accepted.");}if(event.type==="MATCH_COOLDOWN"){nextRequested=false;chatNotice(`You can find someone new in ${payload.remainingSeconds||1} seconds.`);}if(event.type==="TIMER_STATE"&&Number.isFinite(payload.remainingSeconds)){const timer=document.querySelector("#chat-timer"),seconds=Math.max(0,payload.remainingSeconds);if(timer)timer.textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;}if(event.type==="CONTINUE_REQUESTED")chatNotice(`Both people must accept to continue. Each delivered message costs ${payload.messageCredits||10} Credits.`,[["Continue","CONTINUE_ACCEPT"],["End","CONTINUE_DECLINE"]]);if(event.type==="CONTINUE_ACTIVATED")chatNotice("Paid continuation is active.");if(event.type==="PAYMENT_HOLD")chatNotice("Chat is paused because a payment could not be completed.");if(event.type==="CONTACT_UNLOCK_REQUEST")chatNotice(`The other person wants to unlock contact sharing for ${payload.costEach||500} Credits each.`,[["Accept","CONTACT_UNLOCK_ACCEPT"],["Decline","CONTACT_UNLOCK_DECLINE"]]);if(event.type==="CONTACT_UNLOCKED")chatNotice(`Contact sharing is unlocked for ${payload.seconds||300} seconds.`);if(event.type==="CONTACT_UNLOCK_ENDED")chatNotice("Contact sharing is locked again.");if(event.type==="LIKE_ACCEPTED")chatNotice("Like sent privately.");if(event.type==="LIKE_RECEIVED")chatNotice("They liked this chat 👍");if(event.type==="REPORT_ACCEPTED")chatNotice("Report received. This chat is ending.");if(event.type==="BLOCK_ACCEPTED")chatNotice("Blocked. This chat is ending.");if(event.type==="PEER_DISCONNECTED")chatNotice("The other person disconnected. Waiting briefly for them to return…");if(event.type==="PEER_RETURNED")chatNotice("");if(event.type==="SESSION_ENDED"){const destination=nextRequested?"searching":"history";nextRequested=false;finishChat(payload.reason,destination,false).catch(()=>{});}}
async function loadAuth(){return authModule??=await import("./auth.js")}
async function loadAccountApi(){return(accountApiModule??=await import("./account-api.js")).accountApi}
async function loadRazorpay(){if(window.Razorpay)return window.Razorpay;await new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.onload=resolve;script.onerror=()=>reject(new Error("Could not load secure checkout"));document.head.append(script);});return window.Razorpay;}
async function refreshAccount(session,message=""){state.accountSession=session;state.accountMessage=message;state.accountProfile=null;state.wallet=null;state.walletLedger=[];if(session){try{const accountApi=await loadAccountApi();const [profile,wallet,ledger]=await Promise.all([accountApi.profile(session),accountApi.wallet(session),accountApi.ledger(session)]);state.accountProfile=profile;state.wallet=wallet.wallet;state.walletLedger=ledger.entries;let deviceId=localStorage.getItem("random-chat.account-device.v1");if(!deviceId){deviceId=crypto.randomUUID();localStorage.setItem("random-chat.account-device.v1",deviceId);}await accountApi.claimDevice(session,deviceId);}catch(error){state.accountMessage=error.message;}}if(routeName()==="account")render();}
async function ensureAccountAuth(){if(!accountInitialization)accountInitialization=(async()=>{const auth=await loadAuth();auth.onAuthChange((session,event)=>{if(event==="PASSWORD_RECOVERY")state.passwordRecovery=true;refreshAccount(session);});await refreshAccount(await auth.currentSession());})();try{return await accountInitialization}catch(error){accountInitialization=null;throw error}}
async function accountAction(action,success){try{state.accountMessage="Working…";render();await action();state.accountMessage=success;}catch(error){state.accountMessage=error.message;}render();}
function mountMatchPreferences(){const form=document.querySelector("#onboarding-form");if(!form||document.querySelector("#match-preferences"))return;const section=document.createElement("fieldset");section.id="match-preferences";section.className="field full match-preferences";const legend=document.createElement("legend");legend.textContent="Optional matching preferences · paid only on an exact match";section.append(legend);const field=(label,name,element)=>{const wrapper=document.createElement("label");wrapper.className="field";const caption=document.createElement("span");caption.textContent=label;element.name=name;wrapper.append(caption,element);section.append(wrapper);return element;},select=(placeholder,values)=>{const node=document.createElement("select"),first=document.createElement("option");first.value="";first.textContent=placeholder;node.append(first);for(const value of values){const option=document.createElement("option");option.value=value;option.textContent=value;node.append(option);}return node;};field("Gender","targetGender",select("Any gender",["Male","Female","Other"]));const min=field("Minimum age","ageMin",document.createElement("input")),max=field("Maximum age","ageMax",document.createElement("input"));for(const input of [min,max]){input.type="number";input.min="18";input.max="100";input.placeholder="Any";}field("Language","targetLanguage",select("Any language",LANGUAGES));field("Radius","radiusKm",select("Any distance",APP_CONFIG.radiusOptionsKm.map(value=>String(value))));const common=document.createElement("label");common.className="preference-check";const checkbox=document.createElement("input");checkbox.type="checkbox";checkbox.name="commonInterest";const commonText=document.createElement("span");commonText.textContent="Require at least one common interest";common.append(checkbox,commonText);section.append(common);const price=document.createElement("small");price.id="preference-price";price.className="muted";section.append(price);const update=()=>{try{const value=readMatchPreferences(form,false),fee=preferenceFee(value);price.textContent=fee?`Exact mutual match: ${fee} Credits. Full 30/45-second human search; random fallback costs 0.`:"Random matching has no preference fee.";}catch{price.textContent="Choose gender and a complete age range before using radius.";}};section.addEventListener("input",update);form.querySelector('label input[type="checkbox"][required]')?.closest("label")?.before(section);update();}
function readMatchPreferences(form,validate=true){const data=new FormData(form),gender=String(data.get("targetGender")||"")||null,ageMin=data.get("ageMin")?Number(data.get("ageMin")):null,ageMax=data.get("ageMax")?Number(data.get("ageMax")):null,language=String(data.get("targetLanguage")||""),radiusKm=data.get("radiusKm")?Number(data.get("radiusKm")):null,value={gender,ageMin,ageMax,language,commonInterest:data.get("commonInterest")==="on",radiusKm};if(validate){const genderInput=form.elements.targetGender;if((ageMin!==null||ageMax!==null)&&!gender){genderInput.setCustomValidity("Choose a gender when using an age preference.");genderInput.reportValidity();throw new Error("invalid_match_preferences");}if(ageMin!==null&&ageMax!==null&&ageMin>ageMax){form.elements.ageMax.setCustomValidity("Maximum age must not be lower than minimum age.");form.elements.ageMax.reportValidity();throw new Error("invalid_match_preferences");}if(radiusKm!==null&&(!gender||ageMin===null||ageMax===null)){genderInput.setCustomValidity("Radius requires gender and a complete age range.");genderInput.reportValidity();throw new Error("invalid_match_preferences");}}return value;}
function bind(){
  mountMatchPreferences();
  if(state.accountSession&&routeName()==="account"&&!document.querySelector("#account-data-controls")){const section=document.createElement("section");section.id="account-data-controls";section.className="auth-card";section.style.marginTop="26px";const heading=document.createElement("h3");heading.textContent="Your data";const copy=document.createElement("p");copy.className="muted";copy.textContent="Download the account, wallet and payment data held by the server. Chat history remains only in this browser.";const download=document.createElement("button");download.id="export-account-data";download.type="button";download.className="btn btn-ghost";download.textContent="Download my data";const deletion=document.createElement("form");deletion.id="delete-account-form";deletion.className="field";deletion.style.marginTop="18px";const label=document.createElement("label");label.htmlFor="delete-confirm";label.textContent="Request account deletion";const confirm=document.createElement("input");confirm.id="delete-confirm";confirm.name="confirm";confirm.required=true;confirm.pattern="DELETE";confirm.autocomplete="off";confirm.placeholder="Type DELETE to confirm";const reason=document.createElement("textarea");reason.name="reason";reason.maxLength=500;reason.placeholder="Reason (optional)";const submit=document.createElement("button");submit.className="btn btn-ghost";submit.textContent="Request deletion";const note=document.createElement("small");note.className="muted";note.textContent="Active chats end immediately. Financial records may be retained where legally required while other account data is processed for deletion.";deletion.append(label,confirm,reason,submit,note);section.append(heading,copy,download,deletion);document.querySelector("#signout")?.before(section);}
  if(routeName()==="chat"&&!document.querySelector("#chat-actions")){const controls=document.createElement("div");controls.id="chat-actions";controls.className="chat-actions";const add=(id,label)=>{const button=document.createElement("button");button.id=id;button.type="button";button.className="btn btn-ghost";button.textContent=label;controls.append(button);};add("next-chat","Next");add("like-peer","Like");const verified=Boolean(state.accountSession?.user?.email_confirmed_at);if(!state.match?.virtual&&verified)add("contact-unlock","Unlock contact");const select=document.createElement("select");select.id="report-reason";select.setAttribute("aria-label","Report reason");for(const [value,label] of [["spam","Spam"],["harassment","Harassment"],["inappropriate","Inappropriate"],["underage","Underage"],["scam","Scam"],["threats","Threats"],["other","Other"]]){const option=document.createElement("option");option.value=value;option.textContent=label;select.append(option);}controls.append(select);add("report-peer","Report");if(!state.match?.virtual&&verified)add("block-peer","Block");document.querySelector("#chat-form")?.before(controls);}
  if(routeName()==="favourites"){document.querySelectorAll(".saved-list .saved-item").forEach((row,index)=>{const favourite=state.favourites[index];if(!favourite)return;const button=document.createElement("button");button.type="button";button.className="btn btn-ghost";button.dataset.reconnectPeer=favourite.peerId;button.textContent="Reconnect";row.lastElementChild?.replaceWith(button);});}
  if(state.passwordRecovery&&routeName()==="account"&&!document.querySelector("#update-password-form")){const panel=document.querySelector(".panel");panel?.insertAdjacentHTML("afterbegin",`<form id="update-password-form" class="auth-card"><h3>Choose a new password</h3><div class="field"><label>New password</label><input name="password" type="password" minlength="8" required autocomplete="new-password"></div><button class="btn btn-primary">Update password</button></form>`);}
  if(state.accountSession&&state.wallet&&routeName()==="account"){const summary=document.createElement("section");summary.className="wallet-summary";const title=document.createElement("strong");title.textContent=`${state.wallet.balance.toLocaleString("en-IN")} Credits`;const caption=document.createElement("span");caption.textContent="Current server balance";summary.append(title,caption);const list=document.createElement("div");list.className="wallet-ledger";for(const entry of state.walletLedger.slice(0,8)){const row=document.createElement("div");const reason=document.createElement("span");reason.textContent=entry.reason;const amount=document.createElement("strong");amount.textContent=`${entry.delta>0?"+":""}${entry.delta.toLocaleString("en-IN")}`;row.append(reason,amount);list.append(row);}summary.append(list);document.querySelector(".panel h2")?.after(summary);}
  document.querySelectorAll("[data-route]").forEach(el=>el.addEventListener("click",()=>{const destination=el.dataset.route;if(routeName()==="chat"&&destination!=="chat")return finishChat("navigation",destination);if(routeName()==="searching"&&destination!=="searching")return cancelCurrentSearch();navigate(destination);}));
  document.querySelectorAll("[data-chip-group]").forEach(group=>group.addEventListener("click",event=>{const chip=event.target.closest(".chip");if(!chip)return;const limit=group.dataset.chipGroup==="languages"?3:5;if(chip.ariaPressed==="false"&&group.querySelectorAll('[aria-pressed="true"]').length>=limit)return;chip.ariaPressed=chip.ariaPressed==="false"?"true":"false";}));
  document.querySelector("#onboarding-form")?.addEventListener("submit",async event=>{event.preventDefault();const element=event.currentTarget;for(const input of element.querySelectorAll("input,select"))input.setCustomValidity("");try{state.matchPreferences=readMatchPreferences(element);}catch{return;}const form=new FormData(element);state.preferences=savePreferences({age:form.get("age"),gender:form.get("gender"),name:form.get("name"),languages:selectedChips("languages"),interests:selectedChips("interests")});if(preferenceFee(state.matchPreferences)>0&&!state.accountSession){await ensureAccountAuth().catch(()=>{});if(!state.accountSession?.user?.email_confirmed_at){state.accountMessage="Sign in and verify your email before using paid matching preferences.";return navigate("account");}}state.scanCount+=1;sessionStorage.setItem("random-chat.scan-count",String(state.scanCount));recordClientEvent("onboarding_completed").catch(()=>{});navigate("searching");beginSearch();});
  document.querySelector("#cancel-search")?.addEventListener("click",()=>cancelCurrentSearch());
  document.querySelector("#chat-form")?.addEventListener("submit",event=>{event.preventDefault();const input=document.querySelector("#chat-input"),value=input.value.trim();if(!value)return;const contact=checkContactMessage(value,clientContactState);clientContactState=contact.state;if(contact.blocked){input.setCustomValidity("Contact details and links aren't allowed in this chat.");input.reportValidity();return;}input.setCustomValidity("");const eventId=crypto.randomUUID();if(!realtime?.send("CHAT_MESSAGE",{text:value},eventId)){chatNotice("The connection is not ready. Try again in a moment.");return;}pendingMessages.set(eventId,value);input.value="";});
  document.querySelector("#chat-input")?.addEventListener("input",event=>event.currentTarget.setCustomValidity(""));
  document.querySelector("#favourite-peer")?.addEventListener("click",async event=>{if(!state.match?.peerId||state.match.virtual)return;await localHistory.saveFavourite({peerId:state.match.peerRef||state.match.peerId,displayName:"New person",savedAt:new Date().toISOString()});state.favourites=await localHistory.listFavourites();event.currentTarget.textContent="♥";});
  document.querySelector("#end-chat")?.addEventListener("click",()=>finishChat("user_ended"));
  document.querySelector("#next-chat")?.addEventListener("click",()=>{nextRequested=realtime?.send("NEXT_REQUEST")===true;if(nextRequested)chatNotice("Finding someone new…");});
  document.querySelector("#like-peer")?.addEventListener("click",()=>realtime?.send("LIKE"));
  document.querySelector("#contact-unlock")?.addEventListener("click",()=>{if(realtime?.send("CONTACT_UNLOCK_REQUEST"))chatNotice("Contact unlock request sent. Waiting for the other person.");});
  document.querySelector("#report-peer")?.addEventListener("click",()=>{const reason=document.querySelector("#report-reason")?.value||"other";realtime?.send("REPORT",{reason});});
  document.querySelector("#block-peer")?.addEventListener("click",()=>{if(confirm("Block this person across your account and end the chat?"))realtime?.send("BLOCK");});
  document.querySelector("#chat-notice")?.addEventListener("click",event=>{const button=event.target.closest("[data-socket-action]");if(button)realtime?.send(button.dataset.socketAction);});
  document.querySelector("#clear-history")?.addEventListener("click",async()=>{await localHistory.clearAllConversations();state.conversations=[];render();});
  document.querySelectorAll("[data-delete-conversation]").forEach(button=>button.addEventListener("click",async()=>{await localHistory.clearConversation(button.dataset.deleteConversation);state.conversations=await localHistory.listConversations();render();}));
  document.querySelector("#clear-favourites")?.addEventListener("click",async()=>{await localHistory.clearFavourites();state.favourites=[];render();});
  document.querySelectorAll("[data-reconnect-peer]").forEach(button=>button.addEventListener("click",()=>startFavouriteReconnect(button.dataset.reconnectPeer).catch(error=>alert(error.message))));
  document.querySelector("#signup-form")?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);recordClientEvent("signup_started").catch(()=>{});accountAction(async()=>(await loadAuth()).signUp(form.get("email"),form.get("password")),"Check your inbox to verify your email, then sign in.");});
  document.querySelector("#signin-form")?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);accountAction(async()=>(await loadAuth()).signIn(form.get("email"),form.get("password")),"Signed in.");});
  document.querySelector("#reset-password")?.addEventListener("click",()=>{const email=document.querySelector("#signin-form [name=email]")?.value;if(!email){state.accountMessage="Enter your email in the sign-in form first.";return render();}accountAction(async()=>(await loadAuth()).sendPasswordReset(email),"Password reset email sent.");});
  document.querySelector("#signout")?.addEventListener("click",()=>accountAction(async()=>(await loadAuth()).signOut(),"Signed out."));
  document.querySelector("#export-account-data")?.addEventListener("click",()=>accountAction(async()=>{const data=await(await loadAccountApi()).exportData(state.accountSession),blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`random-chat-data-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);},"Your data export was downloaded."));
  document.querySelector("#delete-account-form")?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);if(form.get("confirm")!=="DELETE")return;accountAction(async()=>{await(await loadAccountApi()).requestDeletion(state.accountSession,String(form.get("reason")||""));},"Deletion request received. You can no longer start new chats while it is processed.");});
  document.querySelector("#username-form")?.addEventListener("submit",event=>{event.preventDefault();const username=new FormData(event.currentTarget).get("username");accountAction(async()=>{state.accountProfile=await(await loadAccountApi()).claimUsername(state.accountSession,username);},"Username saved.");});
  const rechargeForm=document.querySelector("#recharge-form");if(rechargeForm&&!rechargeForm.elements.coupon){const coupon=document.createElement("input");coupon.name="coupon";coupon.maxLength=32;coupon.autocomplete="off";coupon.placeholder="Promo code (optional)";rechargeForm.querySelector("small")?.before(coupon);}
  document.querySelector("#recharge-form")?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget),amountRupees=Number(form.get("amount")),couponCode=String(form.get("coupon")||"").trim()||null;accountAction(async()=>{const api=await loadAccountApi(),order=await api.createPaymentOrder(state.accountSession,amountRupees*100,couponCode),Razorpay=await loadRazorpay();await new Promise((resolve,reject)=>{const checkout=new Razorpay({key:order.keyId,amount:order.amountPaise,currency:order.currency,order_id:order.orderId,name:"Random Chat India",description:`${order.credits.toLocaleString("en-IN")} Credits${order.offer?` · ${order.offer}`:""}`,prefill:{email:state.accountSession.user.email},handler:async result=>{try{await api.verifyPayment(state.accountSession,result);await refreshAccount(state.accountSession,"Recharge verified and credited.");resolve();}catch(error){reject(error);}},modal:{ondismiss:()=>reject(new Error("Payment cancelled"))},theme:{color:"#6c4cff"}});checkout.open();});},"Opening secure checkout…");});
  document.querySelector("#update-password-form")?.addEventListener("submit",event=>{event.preventDefault();const password=new FormData(event.currentTarget).get("password");accountAction(async()=>{await(await loadAuth()).updatePassword(password);state.passwordRecovery=false;},"Password updated.");});
}
function activateChat(){if(routeName()!=="chat"||!state.match||!state.anonymousSession)return;clientContactState={};tabLease?.close();tabLease=new ChatTabLease();tabLease.onMoved=()=>{const notice=document.querySelector("#tab-moved");if(notice)notice.hidden=false;document.querySelectorAll("#chat-form input,#chat-form button").forEach(control=>control.disabled=true);realtime?.stop();realtime=null;};tabLease.claim();restoreMessages();if(!realtime){realtime=new RealtimeChatClient({onEvent:handleRealtimeEvent,onStatus:status=>{if(status==="reconnecting")chatNotice("Connection interrupted. Reconnecting…");if(status==="reconnect_failed"){chatNotice("Could not reconnect. This chat has ended.");finishChat("reconnect_failed","history",false).catch(()=>{});}if(status==="connected")chatNotice("");}});realtime.connect({sessionId:state.match.sessionId,token:state.anonymousSession.token});}}
function render(){if(routeName()!=="chat"){tabLease?.close();tabLease=null;}app.innerHTML=views[routeName()](state);bind();activateChat();if(state.adConfig)mountAds(document,{config:state.adConfig,registered:Boolean(state.accountSession),balance:state.wallet?.balance||0,scanCount:state.scanCount});if(routeName()==="account")ensureAccountAuth().catch(error=>{state.accountMessage=error.message;});else if(routeName()==="onboarding")ensureAccountAuth().catch(()=>{});window.scrollTo(0,0);}
async function hydrate(){const [health,conversations,favourites,ads,stats]=await Promise.all([checkStoragePersistence(),localHistory.listConversations(),localHistory.listFavourites(),loadPublicAdConfig().catch(()=>null),publicStats().catch(()=>null),recordClientEvent("landing_view").catch(()=>null)]);state.storageLimited=health.limited;state.conversations=conversations;state.favourites=favourites;state.adConfig=ads;state.publicStats=stats;render();maintainPresence();checkIncomingReconnect();}
window.addEventListener("hashchange",render);window.addEventListener("beforeunload",()=>{clearTimeout(presenceTimer);clearTimeout(reconnectPollTimer);tabLease?.close();realtime?.stop();});render();hydrate().catch(()=>{state.storageLimited=true;render();});
