import { locationForRadius } from "./geolocation.js";
const base=import.meta.env?.VITE_API_BASE_URL||"http://127.0.0.1:8787/api/v1";
async function jsonCall(path,{token,accountToken,fetcher=fetch,apiBase=base,...options}={}){const response=await fetcher(`${apiBase}${path}`,{...options,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{"content-type":"application/json"}),...(accountToken?{"x-account-authorization":`Bearer ${accountToken}`} : {}),...options.headers}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"match_request_failed");return data;}
export function issueAnonymousSession(identity,options={}){return jsonCall("/anonymous/session",{...options,method:"POST",body:JSON.stringify({anonymousId:identity.id,localSecret:identity.secret})});}
export function pollMatchResult(token,options={}){return jsonCall("/match/result",{...options,token});}
export function cancelMatch(token,options={}){return jsonCall("/match/cancel",{...options,token,method:"POST",body:"{}"});}
export function endMatch(token,sessionId,options={}){return jsonCall("/match/end",{...options,token,method:"POST",body:JSON.stringify({sessionId})});}
export function chatSocketUrl(sessionId,{apiBase=base,resumeToken}={}){const url=new URL(`${apiBase}/chat/${encodeURIComponent(sessionId)}/socket`);url.protocol=url.protocol==="https:"?"wss:":"ws:";if(resumeToken)url.searchParams.set("resumeToken",resumeToken);return url.toString();}
export async function startMatchSearch({anonymousToken,accountSession,profile,preferences={},blockedPeerIds=[],fetcher=fetch,locationOptions,apiBase=base}={}){const safePreferences={...preferences},safeProfile={...profile};let locationDenied=false;if(safePreferences.radiusKm){try{safeProfile.location=await locationForRadius(locationOptions);}catch{delete safePreferences.radiusKm;locationDenied=true;}}const data=await jsonCall("/match/search",{apiBase,fetcher,token:anonymousToken,accountToken:accountSession?.access_token,method:"POST",body:JSON.stringify({profile:safeProfile,preferences:safePreferences,blockedPeerIds})});return{...data,locationDenied};}
export async function requestFavouriteReconnect({anonymousToken,accountSession,targetPeerId,fetcher=fetch}){const response=await fetcher(`${base}/reconnect/request`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${anonymousToken}`,"x-account-authorization":`Bearer ${accountSession.access_token}`},body:JSON.stringify({targetPeerId})}),data=await response.json();if(!response.ok)throw new Error(data.error||"reconnect_request_failed");return data;}
export async function pollReconnect({anonymousToken,fetcher=fetch}){const response=await fetcher(`${base}/reconnect/request`,{headers:{authorization:`Bearer ${anonymousToken}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"reconnect_poll_failed");return data;}
export async function respondReconnect({anonymousToken,requestId,accepted,fetcher=fetch}){const response=await fetcher(`${base}/reconnect/respond`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${anonymousToken}`},body:JSON.stringify({requestId,accepted})}),data=await response.json();if(!response.ok)throw new Error(data.error||"reconnect_response_failed");return data;}
