import { chatSocketUrl } from "./match-api.js";

export class RealtimeChatClient{
  constructor({WebSocketImpl=WebSocket,onEvent=()=>{},onStatus=()=>{},setTimer=setTimeout,clearTimer=clearTimeout,now=Date.now,apiBase}={}){this.WebSocketImpl=WebSocketImpl;this.onEvent=onEvent;this.onStatus=onStatus;this.setTimer=setTimer;this.clearTimer=clearTimer;this.now=now;this.apiBase=apiBase;this.stopped=true;this.reconnectTimer=null;this.resumeToken=null;}
  connect({sessionId,token}){this.sessionId=sessionId;this.token=token;this.startedAt=this.now();this.stopped=false;this.open();}
  open(){if(this.stopped)return;const url=chatSocketUrl(this.sessionId,{apiBase:this.apiBase,resumeToken:this.resumeToken}),socket=new this.WebSocketImpl(url,["random-chat.v1",`rc-auth.${this.token}`]);this.socket=socket;this.onStatus("connecting");socket.addEventListener("open",()=>this.onStatus(this.resumeToken?"reconnecting":"connected"));socket.addEventListener("message",event=>{let value;try{value=JSON.parse(event.data)}catch{return}if(value?.v!==1||typeof value.type!=="string")return;if(value.type==="READY"&&value.payload?.resumeToken)this.resumeToken=value.payload.resumeToken;this.onEvent(value);});socket.addEventListener("close",()=>{if(this.stopped)return;if(this.now()-this.startedAt>=30000){this.stopped=true;return this.onStatus("reconnect_failed");}this.onStatus("reconnecting");this.reconnectTimer=this.setTimer(()=>this.open(),1000);});socket.addEventListener("error",()=>this.onStatus("connection_error"));}
  send(type,payload={},eventId){if(!this.socket||this.socket.readyState!==1)return false;this.socket.send(JSON.stringify({v:1,type,...(eventId?{eventId}:{}),...(Object.keys(payload).length?{payload}:{})}));return true;}
  stop(){this.stopped=true;if(this.reconnectTimer)this.clearTimer(this.reconnectTimer);this.reconnectTimer=null;this.socket?.close(1000,"client_end");}
}
