export class AccountPrivacyService{
  constructor(env,fetcher=fetch){this.env=env;this.fetcher=(...args)=>fetcher(...args)}
  headers(){return{apikey:this.env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${this.env.SUPABASE_SERVICE_ROLE_KEY}`,"content-type":"application/json"}}
  async request(path,options={}){const response=await this.fetcher(`${this.env.SUPABASE_URL}/rest/v1${path}`,{...options,headers:{...this.headers(),...options.headers}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"privacy_request_failed");return data}
  async export(userId){const encoded=encodeURIComponent(userId),[profiles,wallets,ledger,payments,blocks,deletionRequests]=await Promise.all([this.request(`/profiles?select=public_id,username,created_at,updated_at&user_id=eq.${encoded}`),this.request(`/wallets?select=balance,version,updated_at&user_id=eq.${encoded}`),this.request(`/wallet_ledger?select=delta,balance_after,entry_type,reason,created_at&user_id=eq.${encoded}&order=created_at.asc`),this.request(`/payment_orders?select=provider,amount_paise,credit_amount,currency,status,created_at,updated_at&user_id=eq.${encoded}&order=created_at.asc`),this.request(`/blocks?select=blocked_ref,created_at&blocker_user_id=eq.${encoded}`),this.request(`/account_deletion_requests?select=id,status,requested_at,completed_at&user_id=eq.${encoded}`)]);return{generatedAt:new Date().toISOString(),profile:profiles[0]||null,wallet:wallets[0]||null,ledger,payments,blocks,deletionRequests,chatHistory:"Stored only in the browser and not available in this server export."}}
  requestDeletion(userId,reason){return this.request("/rpc/request_account_deletion",{method:"POST",body:JSON.stringify({target_user_id:userId,target_reason:reason})})}
  deletionRequested(userId){return this.request(`/account_deletion_requests?select=status&user_id=eq.${encodeURIComponent(userId)}&status=in.(pending,processing)&limit=1`)}
  async grievance({email,category,description}){const rows=await this.request("/grievances",{method:"POST",headers:{prefer:"return=representation"},body:JSON.stringify({email,category,description})});return rows[0]}
}
