import { normalizeAdConfig } from "../policies/adPolicy.js";
import { normalizeVirtualConfig } from "../policies/virtualPolicy.js";
import { normalizeFlags } from "../policies/flagPolicy.js";
import { normalizeVideoConfig } from "../policies/videoPolicy.js";
let cachedAds=null,adsCachedUntil=0,cachedVirtual=null,virtualCachedUntil=0,cachedFlags=null,flagsCachedUntil=0,cachedVideo=null,videoCachedUntil=0;
export class ConfigService{
  constructor(env,fetcher=fetch){this.env=env;this.fetcher=fetcher}
  headers(){return{apikey:this.env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${this.env.SUPABASE_SERVICE_ROLE_KEY}`,"content-type":"application/json"}}
  async row(key){const response=await this.fetcher(`${this.env.SUPABASE_URL}/rest/v1/app_config?key=eq.${key}&select=value,version,updated_at&limit=1`,{headers:this.headers()});if(!response.ok)throw new Error(`${key}_config_lookup_failed`);const [row]=await response.json();if(!row)throw new Error(`${key}_config_missing`);return row}
  async ads(now=Date.now()){if(cachedAds&&adsCachedUntil>now)return cachedAds;const row=await this.row("ads");cachedAds={config:normalizeAdConfig(row.value),version:row.version,updatedAt:row.updated_at};adsCachedUntil=now+30000;return cachedAds}
  async virtual(now=Date.now()){if(cachedVirtual&&virtualCachedUntil>now)return cachedVirtual;const row=await this.row("virtual");cachedVirtual={config:normalizeVirtualConfig(row.value),version:row.version,updatedAt:row.updated_at};virtualCachedUntil=now+30000;return cachedVirtual}
  async flags(now=Date.now()){if(cachedFlags&&flagsCachedUntil>now)return cachedFlags;const row=await this.row("flags");cachedFlags={config:normalizeFlags(row.value),version:row.version,updatedAt:row.updated_at};flagsCachedUntil=now+15000;return cachedFlags}
  async updateAds({adminId,expectedVersion,config}){const normalized=normalizeAdConfig(config),response=await this.fetcher(`${this.env.SUPABASE_URL}/rest/v1/rpc/update_ad_config`,{method:"POST",headers:this.headers(),body:JSON.stringify({admin_id:adminId,expected_version:expectedVersion,new_value:normalized})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"ad_config_update_failed");cachedAds=null;adsCachedUntil=0;const row=Array.isArray(data)?data[0]:data;return{config:normalizeAdConfig(row.value),version:row.version,updatedAt:row.updated_at}}
  async updateVirtual({adminId,expectedVersion,config}){const normalized=normalizeVirtualConfig(config),response=await this.fetcher(`${this.env.SUPABASE_URL}/rest/v1/rpc/update_virtual_config`,{method:"POST",headers:this.headers(),body:JSON.stringify({admin_id:adminId,expected_version:expectedVersion,new_value:normalized})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"virtual_config_update_failed");cachedVirtual=null;virtualCachedUntil=0;const row=Array.isArray(data)?data[0]:data;return{config:normalizeVirtualConfig(row.value),version:row.version,updatedAt:row.updated_at}}
  async updateFlags({adminId,expectedVersion,config}){const normalized=normalizeFlags(config),response=await this.fetcher(`${this.env.SUPABASE_URL}/rest/v1/rpc/update_feature_flags`,{method:"POST",headers:this.headers(),body:JSON.stringify({admin_id:adminId,expected_version:expectedVersion,new_value:normalized})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"flags_update_failed");cachedFlags=null;flagsCachedUntil=0;const row=Array.isArray(data)?data[0]:data;return{config:normalizeFlags(row.value),version:row.version,updatedAt:row.updated_at}}
  async video(now=Date.now()){if(cachedVideo&&videoCachedUntil>now)return cachedVideo;const row=await this.row("video");cachedVideo={config:normalizeVideoConfig(row.value),version:row.version,updatedAt:row.updated_at};videoCachedUntil=now+15000;return cachedVideo}
  async updateVideo({adminId,expectedVersion,config}){const normalized=normalizeVideoConfig(config),response=await this.fetcher(`${this.env.SUPABASE_URL}/rest/v1/rpc/update_video_config`,{method:"POST",headers:this.headers(),body:JSON.stringify({admin_id:adminId,expected_version:expectedVersion,new_value:normalized})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"video_config_update_failed");cachedVideo=null;videoCachedUntil=0;const row=Array.isArray(data)?data[0]:data;return{config:normalizeVideoConfig(row.value),version:row.version,updatedAt:row.updated_at}}
}
export function clearConfigCache(){cachedAds=null;adsCachedUntil=0;cachedVirtual=null;virtualCachedUntil=0;cachedFlags=null;flagsCachedUntil=0;cachedVideo=null;videoCachedUntil=0;}
