import { selectRandomCandidate } from "../policies/randomMatchPolicy.js";
import { approximateDistanceBand,hasPaidPreferences,isExactPreferencePair,preferenceFee,preferenceTimeoutSeconds,satisfiesPreference } from "../policies/preferencePolicy.js";
import { selectVirtualPersona,virtualPublicProfile,virtualWaitMs } from "../policies/virtualPolicy.js";

export class MatchmakingService{
  constructor(data={}){this.queue=data.queue||[];this.active=data.active||{};this.results=data.results||{};this.skipHistory=data.skipHistory||{};this.recentAvoids=data.recentAvoids||{};this.reconnectRequests=data.reconnectRequests||{}}
  match(entry,candidate,uuid,exact){
    this.queue=this.queue.filter(item=>item.identityId!==entry.identityId&&item.identityId!==candidate.identityId);const sessionId=uuid(),mode=entry.mode||"text";
    this.active[entry.identityId]={sessionId,peerId:candidate.identityId,accountUserId:entry.accountUserId||null,accountPublicId:entry.accountPublicId||null,virtual:false,mode,peerHandle:candidate.profile?.handle||null};this.active[candidate.identityId]={sessionId,peerId:entry.identityId,accountUserId:candidate.accountUserId||null,accountPublicId:candidate.accountPublicId||null,virtual:false,mode,peerHandle:entry.profile?.handle||null};
    const resultFor=(owner,peer)=>{const requested=hasPaidPreferences(owner.preferences),peerReference=peer.accountPublicId?{peerRef:peer.accountPublicId}:{},peerHandle=peer.profile?.handle?{peerHandle:peer.profile.handle}:{},peerTheme={...(peer.profile?.patternId?{peerThemePattern:peer.profile.patternId}:{}),...(peer.profile?.paletteId?{peerThemePalette:peer.profile.paletteId}:{})};if(!requested)return{status:"matched",sessionId,peerId:peer.identityId,mode,...peerReference,...peerHandle,...peerTheme};const criteriaSatisfied=exact&&satisfiesPreference(owner,peer),result={status:"matched",sessionId,peerId:peer.identityId,mode,...peerReference,...peerHandle,...peerTheme,criteriaSatisfied,preferenceFee:criteriaSatisfied?preferenceFee(owner.preferences):0,matchMode:criteriaSatisfied?"preference":"random_fallback"};if(criteriaSatisfied&&owner.preferences?.radiusKm)result.approximateDistance=approximateDistanceBand(owner.profile,peer.profile);return result;};
    this.results[entry.identityId]=resultFor(entry,candidate);this.results[candidate.identityId]=resultFor(candidate,entry);return this.results[entry.identityId];
  }
  canFallback(entry,now){return!hasPaidPreferences(entry.preferences)||now-entry.queuedAt>=preferenceTimeoutSeconds(entry.preferences)*1000}
  search(seeker,now=Date.now,uuid=()=>crypto.randomUUID()){
    if(this.active[seeker.identityId])return{status:"already_active",...this.active[seeker.identityId]};
    const previousAccountClaim=seeker.accountUserId?Object.entries(this.active).find(([identityId,claim])=>identityId!==seeker.identityId&&claim.accountUserId===seeker.accountUserId):null;
    if(previousAccountClaim){const [previousIdentityId,claim]=previousAccountClaim,peerId=claim.peerId,previousResult=this.results[previousIdentityId]||{status:"matched",sessionId:claim.sessionId,peerId};delete this.active[previousIdentityId];delete this.results[previousIdentityId];this.active[seeker.identityId]={...claim,accountPublicId:seeker.accountPublicId||claim.accountPublicId||null};if(this.active[peerId]?.peerId===previousIdentityId)this.active[peerId].peerId=seeker.identityId;this.results[seeker.identityId]={...previousResult,status:"matched",sessionId:claim.sessionId,peerId,accountTakeover:true,previousIdentityId};if(this.results[peerId]?.peerId===previousIdentityId)this.results[peerId].peerId=seeker.identityId;return this.results[seeker.identityId];}
    const previousIdentity=this.queue.find(item=>item.identityId===seeker.identityId),previousAccount=seeker.accountUserId?this.queue.find(item=>item.identityId!==seeker.identityId&&item.accountUserId===seeker.accountUserId):null,previous=previousIdentity||previousAccount;this.queue=this.queue.filter(entry=>entry.identityId!==seeker.identityId&&(!seeker.accountUserId||entry.accountUserId!==seeker.accountUserId));
    const current=now();for(const [key,value] of Object.entries(this.recentAvoids))if(value.expiresAt<=current)delete this.recentAvoids[key];const avoided=Object.values(this.recentAvoids).filter(value=>value.identityId===seeker.identityId).map(value=>value.peerId),entry={...seeker,blockedPeerIds:[...(seeker.blockedPeerIds||[]),...avoided],queuedAt:previous?.queuedAt??current};const eligible=this.queue.filter(candidate=>selectRandomCandidate(entry,[candidate],this.active));
    const exact=eligible.filter(candidate=>isExactPreferencePair(entry,candidate)).sort((a,b)=>a.queuedAt-b.queuedAt)[0];if(exact)return this.match(entry,exact,uuid,true);
    if(this.canFallback(entry,current)){const candidate=eligible.filter(item=>this.canFallback(item,current)).sort((a,b)=>a.queuedAt-b.queuedAt)[0];if(candidate)return this.match(entry,candidate,uuid,false);}
    this.queue.push(entry);return{status:"searching",preferenceTimeoutAt:hasPaidPreferences(entry.preferences)?entry.queuedAt+preferenceTimeoutSeconds(entry.preferences)*1000:undefined};
  }
  result(identityId,now=Date.now,uuid=()=>crypto.randomUUID()){if(this.results[identityId])return this.results[identityId];const entry=this.queue.find(item=>item.identityId===identityId);if(!entry)return{status:"idle"};if(this.canFallback(entry,now())){const candidates=this.queue.filter(item=>item.identityId!==identityId&&this.canFallback(item,now()));const candidate=selectRandomCandidate(entry,candidates,this.active);if(candidate)return this.match(entry,candidate,uuid,false);}return{status:"searching",preferenceTimeoutAt:hasPaidPreferences(entry.preferences)?entry.queuedAt+preferenceTimeoutSeconds(entry.preferences)*1000:undefined};}
  cancel(identityId){const before=this.queue.length;this.queue=this.queue.filter(entry=>entry.identityId!==identityId);delete this.results[identityId];return{status:before===this.queue.length?"idle":"cancelled"}}
  avoid(identityId,peerId,now=Date.now){const current=now();this.recentAvoids[`${identityId}:${peerId}`]={identityId,peerId,expiresAt:current+30*60*1000};this.recentAvoids[`${peerId}:${identityId}`]={identityId:peerId,peerId:identityId,expiresAt:current+30*60*1000};if(this.active[identityId]?.peerId===peerId)delete this.active[identityId];if(this.active[peerId]?.peerId===identityId)delete this.active[peerId];delete this.results[identityId];delete this.results[peerId];return{avoided:true,expiresAt:current+30*60*1000}}
  requestReconnect({requestId,initiatorId,initiatorUserId,initiatorPublicId,targetId,targetUserId,targetPublicId},now=Date.now){const current=now(),sameAccount=Boolean(initiatorUserId&&initiatorUserId===targetUserId),samePublicIdentity=Boolean(initiatorPublicId&&initiatorPublicId===targetPublicId);if(initiatorId===targetId||sameAccount||samePublicIdentity||this.active[initiatorId]||this.active[targetId])return{status:"unavailable"};this.reconnectRequests[requestId]={requestId,initiatorId,initiatorUserId,initiatorPublicId:initiatorPublicId||null,targetId,targetUserId:targetUserId||null,targetPublicId:targetPublicId||null,createdAt:current,expiresAt:current+120000};return{status:"requested",requestId,expiresAt:current+120000}}
  cancelReconnect(initiatorId){let cancelled=0;for(const [id,request] of Object.entries(this.reconnectRequests))if(request.initiatorId===initiatorId){delete this.reconnectRequests[id];cancelled++;}return{status:cancelled?"cancelled":"idle",cancelled}}
  pendingReconnect(targetId,now=Date.now){const current=now();for(const [id,request] of Object.entries(this.reconnectRequests))if(request.expiresAt<=current)delete this.reconnectRequests[id];return Object.values(this.reconnectRequests).find(request=>request.targetId===targetId)||null}
  activateReconnect(requestId,targetId,uuid=()=>crypto.randomUUID(),now=Date.now){const current=now(),request=this.reconnectRequests[requestId];if(!request||request.targetId!==targetId||request.expiresAt<=current)return{status:"expired"};if(this.active[request.initiatorId]||this.active[targetId])return{status:"unavailable"};const sessionId=uuid();this.active[request.initiatorId]={sessionId,peerId:targetId,accountUserId:request.initiatorUserId,accountPublicId:request.initiatorPublicId,virtual:false};this.active[targetId]={sessionId,peerId:request.initiatorId,accountUserId:request.targetUserId,accountPublicId:request.targetPublicId,virtual:false};this.results[request.initiatorId]={status:"matched",sessionId,peerId:targetId,...(request.targetPublicId?{peerRef:request.targetPublicId}:{}),reconnect:true};this.results[targetId]={status:"matched",sessionId,peerId:request.initiatorId,...(request.initiatorPublicId?{peerRef:request.initiatorPublicId}:{}),reconnect:true};delete this.reconnectRequests[requestId];return{status:"accepted",sessionId,request};}
  virtualFallback(identityId,config,now=Date.now,uuid=()=>crypto.randomUUID(),random=Math.random,forcePersonaId=null){const entry=this.queue.find(item=>item.identityId===identityId),current=now();if(!entry||this.active[identityId])return this.results[identityId]||{status:"idle"};if(entry.mode==="video")return{status:"searching"};if(!forcePersonaId&&current-entry.queuedAt<virtualWaitMs(entry,config))return{status:"searching",virtualFallbackAt:entry.queuedAt+virtualWaitMs(entry,config)};if(!forcePersonaId&&Object.values(this.active).filter(claim=>claim.virtualPeer).length>=config.maxConcurrent)return{status:"searching",virtualCapacityReached:true};const persona=selectVirtualPersona(config,random,current,forcePersonaId);if(!persona)return{status:"searching"};const sessionId=uuid(),peerId=`virtual-${persona.personaId}`,virtualPeer={identityId:peerId,persona,config:{provider:config.provider,model:config.model,greetProbability:config.greetProbability,greetings:config.greetings}};this.queue=this.queue.filter(item=>item.identityId!==identityId);this.active[identityId]={sessionId,peerId,accountUserId:entry.accountUserId||null,accountPublicId:entry.accountPublicId||null,virtual:false,virtualPeer};const result={status:"matched",sessionId,peerId,virtual:true,virtualProfile:virtualPublicProfile(persona),preferenceFee:0,matchMode:"virtual_fallback"};this.results[identityId]=result;return result;}
  restrict(targetRef){const matches=(identityId,entry)=>identityId===targetRef||entry?.accountUserId===targetRef||entry?.accountPublicId===targetRef;const removed=this.queue.filter(entry=>matches(entry.identityId,entry)).map(entry=>entry.identityId);this.queue=this.queue.filter(entry=>!matches(entry.identityId,entry));const sessions=new Set(Object.entries(this.active).filter(([identityId,claim])=>matches(identityId,claim)).map(([,claim])=>claim.sessionId));for(const [identityId,claim] of Object.entries(this.active))if(sessions.has(claim.sessionId)){delete this.active[identityId];delete this.results[identityId];removed.push(identityId);}return{restricted:true,removed:[...new Set(removed)],sessionsEnded:sessions.size,sessionIds:[...sessions]};}
  end(identityId,sessionId){const claim=this.active[identityId];if(!claim||claim.sessionId!==sessionId)return{status:"not_active"};const peerId=claim.peerId;delete this.active[identityId];if(this.active[peerId]?.sessionId===sessionId)delete this.active[peerId];delete this.results[identityId];delete this.results[peerId];return{status:"ended",peerId}}
  snapshot(){return{queue:this.queue,active:this.active,results:this.results,skipHistory:this.skipHistory,recentAvoids:this.recentAvoids,reconnectRequests:this.reconnectRequests}}
}
