import { RazorpayService } from "./RazorpayService.js";
const MAX_WEBHOOK_BODY_BYTES=256*1024,PROVIDER_REFERENCE=/^[a-zA-Z0-9_-]{1,128}$/,ORDER_REFERENCE=/^order_[a-zA-Z0-9]{1,100}$/,PAYMENT_REFERENCE=/^pay_[a-zA-Z0-9]{1,100}$/,REFUND_REFERENCE=/^rfnd_[a-zA-Z0-9]{1,100}$/;
export class PaymentService{
  constructor(env,fetcher=fetch){this.env=env;this.fetcher=(...args)=>fetcher(...args);this.razorpay=new RazorpayService({keyId:env.RAZORPAY_KEY_ID,keySecret:env.RAZORPAY_KEY_SECRET,webhookSecret:env.RAZORPAY_WEBHOOK_SECRET,fetcher:this.fetcher})}
  serviceHeaders(){return{apikey:this.env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${this.env.SUPABASE_SERVICE_ROLE_KEY}`,"content-type":"application/json"}}
  async database(path,options={}){const response=await this.fetcher(`${this.env.SUPABASE_URL}/rest/v1${path}`,{...options,headers:{...this.serviceHeaders(),...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"payment_database_failed");return data}
  async createOrder(user,amountPaise,couponCode=null){if(!user.emailVerified)throw new Error("email_verification_required");if(!Number.isSafeInteger(amountPaise)||amountPaise<5000)throw new Error("minimum_recharge_50");const receipt=`rc_${crypto.randomUUID().replaceAll("-","").slice(0,28)}`;const order=await this.razorpay.createOrder({amountPaise,receipt,notes:{user_id:user.id}});if(!ORDER_REFERENCE.test(order.id||"")||order.amount!==amountPaise||order.currency!=="INR"||order.status!=="created")throw new Error("invalid_provider_order");const [quote]=await this.database("/rpc/prepare_payment_order",{method:"POST",body:JSON.stringify({target_user_id:user.id,target_provider_order_id:order.id,target_receipt:receipt,target_amount_paise:amountPaise,target_coupon_code:couponCode})});return{keyId:this.env.RAZORPAY_KEY_ID,orderId:order.id,amountPaise,currency:"INR",credits:quote.credit_amount,offer:quote.offer_name||null,coupon:quote.coupon_code||null} }
  async verifyCheckout({user,orderId,paymentId,signature}){if(!ORDER_REFERENCE.test(orderId)||!PAYMENT_REFERENCE.test(paymentId)||!/^[a-f0-9]{64}$/i.test(signature))throw new Error("invalid_payment_signature");const rows=await this.database(`/payment_orders?select=user_id,amount_paise&provider_order_id=eq.${encodeURIComponent(orderId)}&limit=1`);if(!rows[0]||rows[0].user_id!==user.id)throw new Error("payment_order_not_found");if(!await this.razorpay.verifyCheckout({orderId,paymentId,signature}))throw new Error("invalid_payment_signature");const [payment,order]=await Promise.all([this.razorpay.payment(paymentId),this.razorpay.order(orderId)]),amount=rows[0].amount_paise;if(payment.order_id!==orderId||payment.amount!==amount||payment.currency!=="INR"||payment.status!=="captured"||order.id!==orderId||order.amount!==amount||order.currency!=="INR"||order.status!=="paid")throw new Error("payment_not_captured");return this.credit({eventId:`checkout:${paymentId}`,eventType:"checkout.verified",orderId,paymentId,status:payment.status})}
  credit({eventId,eventType,orderId,paymentId,status}){return this.database("/rpc/record_payment_credit",{method:"POST",body:JSON.stringify({target_provider_event_id:eventId,target_event_type:eventType,target_provider_order_id:orderId,target_provider_payment_id:paymentId,target_status:status})})}
  refund({eventId,paymentId,refundId,amountPaise}){return this.database("/rpc/record_payment_refund",{method:"POST",body:JSON.stringify({target_provider_event_id:eventId,target_provider_payment_id:paymentId,target_provider_refund_id:refundId,refund_amount_paise:amountPaise})})}
  async webhook(rawBody,signature,eventId,{onSubscriptionEvent}={}){if(new TextEncoder().encode(rawBody).byteLength>MAX_WEBHOOK_BODY_BYTES)throw new Error("webhook_payload_too_large");if(!PROVIDER_REFERENCE.test(eventId))throw new Error("invalid_webhook_event_id");if(!/^[a-f0-9]{64}$/i.test(signature)||!await this.razorpay.verifyWebhook(rawBody,signature))throw new Error("invalid_webhook_signature");const event=JSON.parse(rawBody);let paymentId=null;if(event.event==="payment.captured"||event.event==="order.paid"){const payment=event.payload?.payment?.entity;if(!PAYMENT_REFERENCE.test(payment?.id||"")||!ORDER_REFERENCE.test(payment?.order_id||"")||payment.status!=="captured")throw new Error("invalid_payment_event");paymentId=payment.id;await this.credit({eventId,eventType:event.event,orderId:payment.order_id,paymentId:payment.id,status:payment.status});}else if(event.event==="refund.processed"){const refund=event.payload?.refund?.entity;if(!REFUND_REFERENCE.test(refund?.id||"")||!PAYMENT_REFERENCE.test(refund?.payment_id||"")||!Number.isSafeInteger(refund.amount)||refund.amount<=0)throw new Error("invalid_refund_event");await this.refund({eventId,paymentId:refund.payment_id,refundId:refund.id,amountPaise:refund.amount});}else if(event.event.startsWith("subscription.")&&onSubscriptionEvent){await onSubscriptionEvent(event.event,event.payload?.subscription?.entity);}return{accepted:true,eventType:event.event,paymentId};}
}
