import { PREFERENCE_PRICING } from "../config/defaults.js";
const GENDERS=new Set(["Male","Female","Other"]);
const RADII=new Set([5,10,25,50,100]);
const list=value=>Array.isArray(value)?value.filter(item=>typeof item==="string").map(item=>item.trim()).filter(Boolean).slice(0,5):[];
export function normalizeMatchProfile(value={},now=Date.now){const current=typeof now==="function"?now():now,age=Number(value.age),location=value.location||{},lat=Number(location.latitude),lng=Number(location.longitude),capturedAt=Number(location.capturedAt),fresh=Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lng)&&lng>=-180&&lng<=180&&Number.isFinite(capturedAt)&&capturedAt>=current-600000&&capturedAt<=current+60000;return{age:Number.isInteger(age)&&age>=18&&age<=100?age:null,gender:GENDERS.has(value.gender)?value.gender:null,languages:list(value.languages).slice(0,3),interests:list(value.interests),location:fresh?{latitude:lat,longitude:lng,capturedAt}:null};}
export function normalizePaidPreferences(value={}){const gender=GENDERS.has(value.gender)?value.gender:null,ageMin=Number(value.ageMin),ageMax=Number(value.ageMax),language=typeof value.language==="string"?value.language.trim().slice(0,40):"",radius=Number(value.radiusKm);const normalized={gender,ageMin:Number.isInteger(ageMin)&&ageMin>=18&&ageMin<=100?ageMin:null,ageMax:Number.isInteger(ageMax)&&ageMax>=18&&ageMax<=100?ageMax:null,language,commonInterest:value.commonInterest===true,radiusKm:RADII.has(radius)?radius:null};if((normalized.ageMin!==null||normalized.ageMax!==null)&&!gender)throw new Error("age_preference_requires_gender");if(normalized.ageMin!==null&&normalized.ageMax!==null&&normalized.ageMin>normalized.ageMax)throw new Error("invalid_age_range");if(normalized.radiusKm!==null&&(!gender||normalized.ageMin===null||normalized.ageMax===null))throw new Error("radius_preference_requires_gender_age");return normalized;}
export function preferenceFee(preferences={}){const value=normalizePaidPreferences(preferences);let fee=value.gender?(value.radiusKm!==null?PREFERENCE_PRICING.genderAgeRadiusCredits:value.ageMin!==null||value.ageMax!==null?PREFERENCE_PRICING.genderAgeCredits:PREFERENCE_PRICING.genderCredits):0;if(value.language)fee+=PREFERENCE_PRICING.languageAddonCredits;if(value.commonInterest)fee+=PREFERENCE_PRICING.interestAddonCredits;return fee;}
export function hasPaidPreferences(preferences={}){return preferenceFee(preferences)>0;}
export function distanceKm(left,right){if(!left||!right)return Infinity;const radians=value=>value*Math.PI/180,dLat=radians(right.latitude-left.latitude),dLng=radians(right.longitude-left.longitude),a=Math.sin(dLat/2)**2+Math.cos(radians(left.latitude))*Math.cos(radians(right.latitude))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
export function satisfiesPreference(seeker,candidate){const request=normalizePaidPreferences(seeker.preferences),profile=normalizeMatchProfile(candidate.profile),own=normalizeMatchProfile(seeker.profile);if(request.gender&&profile.gender!==request.gender)return false;if(request.ageMin!==null&&(profile.age===null||profile.age<request.ageMin))return false;if(request.ageMax!==null&&(profile.age===null||profile.age>request.ageMax))return false;if(request.language&&!profile.languages.some(item=>item.toLocaleLowerCase("en-IN")===request.language.toLocaleLowerCase("en-IN")))return false;if(request.commonInterest){const ownInterests=new Set(own.interests.map(item=>item.toLocaleLowerCase("en-IN")));if(!profile.interests.some(item=>ownInterests.has(item.toLocaleLowerCase("en-IN"))))return false;}if(request.radiusKm!==null&&distanceKm(own.location,profile.location)>request.radiusKm*1.1)return false;return true;}
export function isExactPreferencePair(left,right){return satisfiesPreference(left,right)&&satisfiesPreference(right,left);}
export function preferenceTimeoutSeconds(preferences={}){return normalizePaidPreferences(preferences).radiusKm===null?PREFERENCE_PRICING.nonGeoTimeoutSeconds:PREFERENCE_PRICING.geoTimeoutSeconds;}
export function approximateDistanceBand(left,right){const distance=distanceKm(normalizeMatchProfile(left).location,normalizeMatchProfile(right).location);if(!Number.isFinite(distance))return null;const low=Math.floor(distance/5)*5;return distance<5?"Under 5 km":`${low}–${low+5} km`;}
