import { generateRedditHandle } from "./handlePool.js";
export const DEFAULT_VIRTUAL_CONFIG=Object.freeze({enabled:false,provider:"disabled",model:"",maxConcurrent:0,fallbackSeconds:10,greetProbability:0.55,greetings:["hi","hie","hey"],personas:[]});
const ID=/^[a-z0-9_-]{2,40}$/;
export function normalizeVirtualConfig(value={}){
  const provider=String(value.provider||"disabled").trim().toLowerCase(),model=String(value.model||"").trim().slice(0,120),maxConcurrent=Number(value.maxConcurrent??0),fallbackSeconds=Number(value.fallbackSeconds??15),greetProbability=Number(value.greetProbability??0.55);
  if(!ID.test(provider))throw new Error("invalid_virtual_provider");if(!Number.isSafeInteger(maxConcurrent)||maxConcurrent<0||maxConcurrent>10000)throw new Error("invalid_virtual_capacity");if(!Number.isSafeInteger(fallbackSeconds)||fallbackSeconds<5||fallbackSeconds>300)throw new Error("invalid_virtual_fallback");if(!Number.isFinite(greetProbability)||greetProbability<0||greetProbability>1)throw new Error("invalid_virtual_greet_probability");
  const greetings=(Array.isArray(value.greetings)?value.greetings:DEFAULT_VIRTUAL_CONFIG.greetings).map(item=>String(item).trim().toLowerCase()).filter(item=>/^[a-z]{2,8}$/.test(item)).slice(0,10);if(!greetings.length)throw new Error("invalid_virtual_greetings");
  const personas=(Array.isArray(value.personas)?value.personas:[]).slice(0,100).map(normalizePersona);
  return{enabled:value.enabled===true,provider,model,maxConcurrent,fallbackSeconds,greetProbability,greetings,personas};
}
export function normalizePersona(value){const personaId=String(value.personaId||"").trim().toLowerCase(),handle=String(value.handle||"").trim(),age=Number(value.age),gender=String(value.gender||"").trim(),languages=(value.languages||[]).map(String).slice(0,3),interests=(value.interests||[]).map(String).slice(0,5),delayMinMs=Number(value.delayMinMs??500),delayMaxMs=Number(value.delayMaxMs??1500),activeHours=(Array.isArray(value.activeHours)?value.activeHours:[]).map(Number),greetProbability=value.greetProbability===undefined?null:Number(value.greetProbability);if(!ID.test(personaId)||!/^[A-Za-z0-9_]{3,24}$/.test(handle)||!Number.isSafeInteger(age)||age<18||age>100||!languages.length||!Number.isSafeInteger(delayMinMs)||!Number.isSafeInteger(delayMaxMs)||delayMinMs<0||delayMaxMs<delayMinMs||delayMaxMs>5000||activeHours.some(hour=>!Number.isSafeInteger(hour)||hour<0||hour>23)||(greetProbability!==null&&(!Number.isFinite(greetProbability)||greetProbability<0||greetProbability>1)))throw new Error("invalid_virtual_persona");return{personaId,handle,age,gender,region:String(value.region||"India").slice(0,40),languages,interests,tone:String(value.tone||"friendly").slice(0,80),verbosity:String(value.verbosity||"short").slice(0,20),curiosity:Number(value.curiosity??0.7),humor:Number(value.humor??0.4),delayMinMs,delayMaxMs,activeHours:[...new Set(activeHours)].slice(0,24),greetProbability};}
export function personaGreetProbability(persona,config){if(persona.greetProbability!==null&&persona.greetProbability!==undefined)return persona.greetProbability;return persona.gender==="Female"?config.greetProbability*0.4:config.greetProbability;}
export function virtualWaitMs(entry,config){return(hasPaidPreferencesSafe(entry)?entry.preferences.radiusKm?45000:30000:config.fallbackSeconds*1000);}
function hasPaidPreferencesSafe(entry){const p=entry?.preferences||{};return Boolean(p.gender||p.minAge||p.maxAge||p.language||p.interest||p.radiusKm);}
export function selectVirtualPersona(config,random=Math.random,now=Date.now(),forcePersonaId=null){const normalized=normalizeVirtualConfig(config);if(!normalized.enabled||normalized.provider==="disabled"||normalized.maxConcurrent===0||!normalized.personas.length)return null;const istHour=new Date(now+19800000).getUTCHours(),active=normalized.personas.filter(persona=>!persona.activeHours.length||persona.activeHours.includes(istHour));if(!active.length)return null;const forced=forcePersonaId?active.find(persona=>persona.personaId===forcePersonaId):null,chosen=forced||active[Math.min(active.length-1,Math.floor(random()*active.length))];return{...chosen,handle:generateRedditHandle(random)};}
export function virtualPublicProfile(persona){return{handle:persona.handle,age:persona.age,gender:persona.gender,region:persona.region,languages:persona.languages,interests:persona.interests};}
