import { pathToFileURL } from "node:url";
import { requireReleaseRevision,writeLaunchReport } from "./launch-report.mjs";

async function read(response){const data=await response.json().catch(()=>({}));return{response,data}}
export async function runStagingSmoke({apiUrl,webOrigin,expectedRevision,fetcher=fetch}){if(!apiUrl||!webOrigin)throw new Error("STAGING_API_URL and STAGING_WEB_ORIGIN are required");const revision=requireReleaseRevision(expectedRevision),base=apiUrl.replace(/\/$/,""),site=new URL(webOrigin).origin;if(new URL(base).protocol!=="https:"||new URL(site).protocol!=="https:")throw new Error("Staging URLs must use HTTPS");const results=[];const frontend=await fetcher(site,{redirect:"error"});results.push({name:"frontend",status:frontend.status});if(!frontend.ok)throw new Error(`frontend failed with ${frontend.status}`);const hsts=frontend.headers.get("strict-transport-security")||"",csp=frontend.headers.get("content-security-policy")||"",apiOrigin=new URL(base).origin,websocketOrigin=apiOrigin.replace(/^https:/,"wss:");if(!/max-age=\d+/.test(hsts))throw new Error("frontend missing HSTS");if(!csp.includes(`connect-src`)||!csp.split(";").find(value=>value.trim().startsWith("connect-src"))?.split(/\s+/).includes(apiOrigin)||!csp.split(";").find(value=>value.trim().startsWith("connect-src"))?.split(/\s+/).includes(websocketOrigin))throw new Error("frontend CSP missing exact API HTTPS/WSS origins");if(/localhost|127\.0\.0\.1|http:\/\//i.test(csp))throw new Error("frontend CSP contains a local or insecure production origin");async function request(name,path,options={}){const {response,data}=await read(await fetcher(`${base}${path}`,{...options,headers:{origin:site,...options.headers}}));results.push({name,status:response.status});if(!response.ok)throw new Error(`${name} failed with ${response.status}`);if(response.headers.get("access-control-allow-origin")!==site)throw new Error(`${name} missing exact CORS origin`);return{response,data}}
  const frontendRelease=await read(await fetcher(`${site}/release.json`,{redirect:"error",headers:{"cache-control":"no-cache"}}));results.push({name:"frontend release",status:frontendRelease.response.status});if(!frontendRelease.response.ok||frontendRelease.data.revision!==revision)throw new Error("staging frontend revision does not match RELEASE_REVISION");
  const health=await request("health","/health");if(health.data.phase<23)throw new Error("staging Worker is behind Phase 23");if(health.data.revision!==revision)throw new Error("staging Worker revision does not match RELEASE_REVISION");
  await request("public config","/config/public");await request("public stats","/stats/public");const compliance=await request("compliance","/compliance/public");if(!compliance.data.grievanceOfficer?.configured)throw new Error("grievance officer is not configured");
  const preflight=await request("preflight","/grievances",{method:"OPTIONS",headers:{"access-control-request-method":"POST","access-control-request-headers":"content-type"}});if(!preflight.response.headers.get("access-control-allow-methods")?.includes("POST"))throw new Error("preflight does not allow POST");
  const hostile=await fetcher(`${base}/health`,{headers:{origin:"https://not-allowed.invalid"}});results.push({name:"unknown origin rejection",status:hostile.status});if(hostile.status!==403)throw new Error("unknown origin was not rejected");return results;}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const apiUrl=process.env.STAGING_API_URL,webOrigin=process.env.STAGING_WEB_ORIGIN,expectedRevision=process.env.RELEASE_REVISION;runStagingSmoke({apiUrl,webOrigin,expectedRevision}).then(async results=>{for(const item of results)console.log(`${item.name}: ${item.status}`);if(process.env.SMOKE_REPORT_PATH){const report={kind:"staging-smoke",revision:requireReleaseRevision(expectedRevision),completedAt:new Date().toISOString(),webUrl:new URL(webOrigin).origin,apiUrl:apiUrl.replace(/\/$/,""),checks:results};await writeLaunchReport(process.env.SMOKE_REPORT_PATH,report);console.log(`Report written to ${process.env.SMOKE_REPORT_PATH}`);}console.log("Staging smoke checks passed.");}).catch(error=>{console.error(error.message);process.exitCode=1;});}
