create table if not exists public.likes(id bigint generated always as identity primary key,session_id text not null,actor_ref text not null,target_ref text not null,created_at timestamptz not null default now(),unique(session_id,actor_ref));
create table if not exists public.reputation_scores(target_ref text primary key,like_count bigint not null default 0,updated_at timestamptz not null default now());
create table if not exists public.reports(id bigint generated always as identity primary key,session_id text not null,reporter_ref text not null,target_ref text not null,reason text not null,weight integer not null,created_at timestamptz not null default now(),unique(session_id,reporter_ref));
create index if not exists reports_target_created_idx on public.reports(target_ref,created_at desc);
create table if not exists public.risk_scores(target_ref text primary key,recent_score numeric not null default 0,lifetime_score bigint not null default 0,unique_reporters bigint not null default 0,last_report_at timestamptz,updated_at timestamptz not null default now());
create table if not exists public.blocks(id bigint generated always as identity primary key,blocker_user_id uuid not null references auth.users(id) on delete cascade,blocked_ref text not null,created_at timestamptz not null default now(),unique(blocker_user_id,blocked_ref));
alter table public.likes enable row level security;alter table public.reputation_scores enable row level security;alter table public.reports enable row level security;alter table public.risk_scores enable row level security;alter table public.blocks enable row level security;
revoke all on public.likes,public.reputation_scores,public.reports,public.risk_scores,public.blocks from anon,authenticated;grant select,delete on public.blocks to authenticated;
create policy "users read own blocks" on public.blocks for select to authenticated using ((select auth.uid())=blocker_user_id);create policy "users remove own blocks" on public.blocks for delete to authenticated using ((select auth.uid())=blocker_user_id);

create or replace function public.record_like(target_session_id text,target_actor_ref text,target_ref text) returns boolean language plpgsql security definer set search_path='' as $$
begin insert into public.likes(session_id,actor_ref,target_ref) values(target_session_id,target_actor_ref,target_ref) on conflict do nothing;if not found then return false;end if;insert into public.reputation_scores(target_ref,like_count) values(target_ref,1) on conflict(target_ref) do update set like_count=reputation_scores.like_count+1,updated_at=now();return true;end;$$;
create or replace function public.record_report(target_session_id text,target_reporter_ref text,target_ref text,target_reason text) returns table(weight integer,recent_score numeric,idempotent boolean) language plpgsql security definer set search_path='' as $$
declare reason_weight integer;previous_time timestamptz;was_new boolean;
begin reason_weight:=case target_reason when 'spam' then 1 when 'contact_bypass' then 2 when 'harassment' then 2 when 'inappropriate' then 3 when 'scam' then 4 when 'threats' then 5 when 'underage' then 5 else 1 end;insert into public.reports(session_id,reporter_ref,target_ref,reason,weight) values(target_session_id,target_reporter_ref,target_ref,target_reason,reason_weight) on conflict do nothing;was_new:=found;if not was_new then select r.weight,s.recent_score,true into weight,recent_score,idempotent from public.reports r left join public.risk_scores s on s.target_ref=r.target_ref where r.session_id=target_session_id and r.reporter_ref=target_reporter_ref;return next;return;end if;select updated_at into previous_time from public.risk_scores where risk_scores.target_ref=record_report.target_ref for update;insert into public.risk_scores(target_ref,recent_score,lifetime_score,unique_reporters,last_report_at) values(target_ref,reason_weight,reason_weight,1,now()) on conflict(target_ref) do update set recent_score=risk_scores.recent_score*power(0.5,greatest(extract(epoch from(now()-risk_scores.updated_at))/86400,0)/30)+reason_weight,lifetime_score=risk_scores.lifetime_score+reason_weight,unique_reporters=(select count(distinct reporter_ref) from public.reports where reports.target_ref=record_report.target_ref),last_report_at=now(),updated_at=now();select reason_weight,s.recent_score,false into weight,recent_score,idempotent from public.risk_scores s where s.target_ref=record_report.target_ref;return next;end;$$;
create or replace function public.create_block(target_blocker uuid,target_blocked text) returns boolean language plpgsql security definer set search_path='' as $$begin if length(target_blocked)<8 then raise exception 'invalid_block_target';end if;insert into public.blocks(blocker_user_id,blocked_ref) values(target_blocker,target_blocked) on conflict do nothing;return found;end;$$;
revoke all on function public.record_like(text,text,text),function public.record_report(text,text,text,text),function public.create_block(uuid,text) from public,anon,authenticated;
grant execute on function public.record_like(text,text,text),function public.record_report(text,text,text,text),function public.create_block(uuid,text) to service_role;
